WIP - refactoring updates
RedHatInsights/edge-api pull request #104
Opened 2021-07-18 17:40 UTC by maxamillion

Signed-off-by: Adam Miller <admiller@redhat.com>

2021-07-18 17:41 UTC, maxamillion commented
@biancarosa @acosferreira I didn't get a chance to actually test this so I'm not sure where there be dragons just yet, but this is the changeset I had in mind for the refactor plus/minus bugfixes after I get some testing in.

2021-07-19 14:27 UTC, biancarosa commented on pkg/models/commits.go
> +	RepoID               uint      `json:"RepoID"`
```suggestion
	RepoID               *uint      `json:"RepoID"`
```

This one needs to be a pointer, running against postgresql it violates a fk contrainst.

2021-07-19 14:34 UTC, biancarosa requested changes

2021-07-19 14:34 UTC, biancarosa commented on pkg/commits/repobuilder.go
> +	db.DB.First(&update, ur.ID)
We can rename ur to ut here

2021-07-19 14:34 UTC, biancarosa commented on pkg/commits/repobuilder.go
> +	db.DB.Save(&update)
It might be good to check if there were any errors in the resulting transaction to avoid weird problems further down the process

2021-07-19 14:34 UTC, biancarosa commented on pkg/commits/repobuilder.go
> +	db.DB.Save(&updateDone)
Same here. I'm not too worried about errors on the select because it needs an existing UpdateTransaction, but saves are dangerous

2021-07-19 14:34 UTC, biancarosa commented on pkg/commits/repobuilder.go
> +	DownloadExtractVersionRepo(c, path)
I just realized we're not checking errors here and things can go south silently

2021-07-19 14:34 UTC, biancarosa commented on pkg/updates/updates.go
> +const UpdateContextKey key = 0
I might be wrong on how context keys work, but I think we need a different key than 0 for UpdateContextKey because we're using 0 for commits (and I just realized that image and pagination are sharing one, so this can be weird if we use then in the same request).

Maybe it'd be best to centralize all context keys in a package to make it easier to read which ones are in use and you don't run the risk of trying to access an object and accessing another.

2021-07-19 16:34 UTC, maxamillion commented on pkg/updates/updates.go
> +const UpdateContextKey key = 0
I honestly don't know, I just assumed since they were each a different context that it would be fine ... is that all a shared instantiation? (my understand of how the context works is very introductory)

2021-07-19 17:48 UTC, biancarosa commented on pkg/updates/updates.go
> +const UpdateContextKey key = 0
yeah, we have one context per request and it's shared, unless you specifically create a new context for a specific transaction

2021-07-19 19:09 UTC, biancarosa reviewed
Now I think that, with my suggestions, the references to Repo.ID are breaking because they aren't expecting a pointer to a uint, but a uint

2021-07-20 12:49 UTC, biancarosa approved these changes
LGTM! Awesome refactor, this is great :)

2021-07-20 13:50 UTC, merged