Theedge 2136 update all devices from group
RedHatInsights/edge-api pull request #1065
Opened 2022-05-18 06:59 UTC by acosferreira

# Description

Include a new route to be able to update all devices from a group.

Fixes # (THEEDGE-2136)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-05-18 14:34 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
35ab3765-28c9-44b3-b1cb-1970a715249c
5aedfff9-e868-4176-ab96-2dde2bc71709

2022-05-18 15:11 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
b145596a-9c24-47c3-922f-24b63e99d661
cbb632b1-46e5-48a8-be39-25c9ea1a90a3

2022-05-18 22:08 UTC, thom-at-redhat requested changes

2022-05-18 22:08 UTC, thom-at-redhat commented on pkg/services/updates.go
> +			s.log.WithField("message", errNotify.Error()).Error("Error to send notification")
Error sending device notification?  Account? and should the message below be combined with this one?

2022-05-18 22:08 UTC, thom-at-redhat commented on pkg/services/updates.go
> +					s.log.WithField("error", err.Error()).Error("Device was not found in our database")
Device was not found in this account?

2022-05-18 22:08 UTC, thom-at-redhat commented on pkg/services/updates.go
> +						s.log.Debug("No old commits found")
Do we want to add the search criteria to the log message as fields?

2022-05-18 22:08 UTC, thom-at-redhat commented on pkg/services/updates.go
> +					err := errors.NewBadRequest(err.Error())
Should err be reused  in this way?

2022-05-18 22:51 UTC, acosferreira commented on pkg/services/updates.go
> +						s.log.Debug("No old commits found")
I dont think so, is all related to the current device uuid

2022-05-19 22:52 UTC, thom-at-redhat approved these changes

2022-05-19 23:19 UTC, thom-at-redhat commented
@mergifyio unqueue

2022-05-19 23:49 UTC, thom-at-redhat commented
@mergifyio requeue

2022-05-20 00:03 UTC, merged