Add validation to package names when creating image.
RedHatInsights/edge-api pull request #1079
Opened 2022-05-24 13:02 UTC by mgold1234

related to issue THEEDGE-1813

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [V] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [V] I have added tests that prove my fix is effective or that my feature works
- [V] New and existing unit tests pass locally with my changes
- [V] I run `go fmt ./...` to check that my code is properly formatted
- [V] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-05-24 13:10 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
72efb296-ffcb-401c-bebc-8a931d726d8b
c2c177b4-fb0f-41af-afc8-1af0f6833fc0

2022-05-24 18:02 UTC, omaciel commented on pkg/models/images.go
> +	InvalidPackageName = "this package name doesn't exist at package list"
I think it should say "... in the package list"?

2022-05-25 17:02 UTC, acosferreira commented
@mgold1234 I'd like to suggest to validate the packages with the image-builder list before send to creation as we are doing on UI.
{imagebuilder_url}/v1/packages?distribution=rhel-85&architecture=x86_64&search=badrpm will return 0, this mean the package not exists and you should not continue with the process.

you can:

loop on packages list
call imagebuilder Packages validator
if return from imagebuilder >0 
continue
else
return invalid package selected 

you can add it on validate request, given we should not proceed the process with a invalid package in a list.

for more context: 
https://console.stage.redhat.com/#/default/GetPackages

2022-05-25 17:14 UTC, acosferreira requested changes
Left comment

2022-05-25 19:27 UTC, ldjebran commented
@acosferreira originally this issue was raised as understood because custom packages are not validated at all , and we cannot make search for them for the moment. rhel packages are searched in the UI, but the custom packages are not.

@tpapaioa please explain what we are expecting when resolving bug THEEDGE-1813.   

as "badrpm" package name maybe a valid custom package name.

2022-05-26 18:22 UTC, loadtheaccumulator requested changes
I have some questions and recommendations.

2022-05-26 18:22 UTC, loadtheaccumulator commented on pkg/models/images.go
> +	existingpackages := []string{
Consider camelCase for existingpackages

2022-05-26 18:22 UTC, loadtheaccumulator commented on pkg/models/images.go
> +	existingpackages := []string{
Can this be made configurable? Ana has a PR that includes RHEL9, so this might need ongoing maintenance as we add additional OSes and versions.

2022-05-26 18:22 UTC, loadtheaccumulator commented on pkg/models/images.go
>  func (i *Image) ValidateRequest() error {
What's the idea behind it being here? I'm thinking this logical function should be in services.Images() instead of models.Images().

2022-05-31 09:00 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	url := fmt.Sprintf("%s/api/image-builder/v1/packages?distribution=%s&architecture=%s&search=%s", cfg.ImageBuilderConfig.URL, dist, arch, packageName)
we should return error if packageName == "" 
we should return error if arch == "" 
we should return error if dist == ""

2022-05-31 09:01 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	req.Header.Add("Content-Type", "application/json")
we do not need line as we are not passing any content

2022-05-31 09:05 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +		return nil, err
we need to log the error

2022-05-31 09:13 UTC, ldjebran commented on pkg/services/images.go
> +			return err
we should not return this error, as the validation errors are returned to user, as the client is logging it's errors we do not need  to log here , we can return a global error as "Unknown validation error occurred"

2022-05-31 09:17 UTC, ldjebran requested changes
Very good, left some comment for the changes needed.

2022-05-31 19:29 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +	if searchResult.Meta.Count == 0 {
I think the validation should be !=1 because if return more than one (example vim) will fail because the IB will not know which should be installed.
What do you think?

2022-05-31 19:41 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	if searchResult.Meta.Count == 0 {
This function here is pure client function to if function packages   search we should not validate here (as this function may be used for other purpose) so we need to return the the ib results and remove this block.

2022-05-31 19:50 UTC, ldjebran commented on pkg/services/images.go
> +	packages := image.Packages
move package validation code to a function 

```go
func validateImagePackages(image models.Image) error {
...
}
```

2022-06-02 13:58 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	if searchResult.Meta.Count != 1 {
remove this if block

2022-06-02 19:43 UTC, acosferreira reviewed
lgtm

2022-06-02 20:17 UTC, loadtheaccumulator requested changes

2022-06-02 20:17 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +	Meta MetaCount `json:"meta"`
What's the purpose of MetaCount versus just making this Count int `json:"count"` here?

2022-06-02 20:17 UTC, loadtheaccumulator commented on pkg/services/errors.go
> +type PackageNameDoesntExists struct{}
Typo. Suggesting PackageNameDoesNotExist to make singular and avoid the contraction in Doesnt.

2022-06-02 20:17 UTC, loadtheaccumulator commented on pkg/services/errors.go
> +func (e *PackageNameDoesntExists) Error() string {
same typo

2022-06-02 20:17 UTC, loadtheaccumulator commented on pkg/services/images.go
> +			return new(PackageNameDoesntExists)
See typo above

2022-06-03 07:43 UTC, ldjebran commented on pkg/services/images.go
> +		}
@mgold1234 this has not been resolved

2022-06-03 07:43 UTC, ldjebran commented on pkg/services/images.go
> +	packages := image.Packages
@mgold1234 this has not been resolved

2022-06-03 07:54 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	Meta MetaCount `json:"meta"`
@mgold1234 but anyway we are missing the data section with packages names, to be able to make a valide validation later.

```go

type MetaCount struct {
	Count int `json:"count"`
}
type SearchPackage struct {
	Name string `json:"name"`
}

type SearchPackageResult struct {
	Meta MetaCount `json:"meta"`
        Data []SearchPackage  `json:"data"`
}
```

2022-06-07 08:11 UTC, ldjebran commented on pkg/services/images.go
> +	return &res, err
I was waiting for this code 

```go
res, err := ib.SearchPackage(pack, arch, dist)
if err != nil {
      return errors.new(""validation error")
}
for _, package : = range res.Data {
     if package == pack {
         return nil
     }
     
     return errors.New(fmt.Sprintf("Package %s not found ", pack))
}

```

2022-06-07 08:14 UTC, ldjebran commented on pkg/services/images.go
> +		if (*count).Meta.Count != 1 {
Think the right condition is 
```suggestion
		if (*count).Meta.Count == 0 {
```

2022-06-08 11:05 UTC, ldjebran commented on pkg/services/images.go
> +func (s *ImageService) ValidateImagePackage(pack string, image *models.Image) error {
let's rename "pack" to "packageName"

2022-06-08 11:07 UTC, ldjebran reviewed
It looks very good, 
remaining:
-  One minor comment about rename to packageName 
- Add unittests for validation function

2022-06-08 21:13 UTC, loadtheaccumulator approved these changes
/lgtm

2022-06-08 21:13 UTC, loadtheaccumulator commented on pkg/services/images.go
> +func (s *ImageService) ValidateImagePackage(pack string, image *models.Image) error {
+1 on that rename

2022-06-09 08:18 UTC, ldjebran commented on pkg/services/images_test.go
> +				mockImageBuilderClient.EXPECT().ComposeCommit(&image).Return(&image, nil)
The unit-test are not passing because the app is waiting that the image contain everything needed to proceed further , but if fail.
as the next steps are not needed, and the needed steps are when ComposeCommit is reached without errors.
we can put that ComposeCommit will return an error (expectedErr) , and expect that expectedErr will be returned.
that way our code will stop just after ComposeCommit in our code.

```go
expectedErr := fmt.Errorf("failed to create commit for image")
mockImageBuilderClient.EXPECT().ComposeCommit(&image).Return(&image, expectedErr)
...
err := service.CreateImage(&image, account, orgID, requestID)
Expect(err).To(HaveOccurred())
Expect(err.Error()).To(Equal(expectedErr.Error()))
```
recap:  The most important here is that image-builder client SearchPackage is called, and that we have passed the validation step without errors when SearchPackage return the right data. 


```

2022-06-09 08:24 UTC, ldjebran commented on pkg/routes/images.go
> +		respondWithAPIError(w, ctxServices.Log, errors.NewBadRequest(err.Error()))
Think you can simply remove your changes, as this does not apply to this PR only , and may done as a standalone PR.

2022-06-09 11:53 UTC, ldjebran commented on pkg/services/images_test.go
> +				mockImageService.EXPECT().CreateImage(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
look at my suggestion https://github.com/RedHatInsights/edge-api/pull/1079#discussion_r893210678

2022-06-09 19:54 UTC, mgold1234 commented
/retest

2022-06-10 08:14 UTC, ldjebran approved these changes

2022-06-10 08:32 UTC, ldjebran commented
closing this PR as one of the CI processes is hanging, a new PR has been created https://github.com/RedHatInsights/edge-api/pull/1138

2022-06-10 08:32 UTC, closed without merging