Theedge 2165 add rhel9 support
RedHatInsights/edge-api pull request #1085
Opened 2022-05-26 17:50 UTC by acosferreira

# Description

Add support to RHELX image creation based on distribution value.

Fixes # (THEEDGE-2165)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-05-26 18:02 UTC, loadtheaccumulator requested changes
have some questions

2022-05-26 18:02 UTC, loadtheaccumulator commented on pkg/services/images.go
> +	oSTreeRefDistribution = regexp.MustCompile(`[a-zA-Z]+`)
oSTree... is that naming intentional or a typo?

2022-05-30 14:02 UTC, ldjebran commented on pkg/models/required_image_packages.json
> +{   "8":["ansible"],
why not save them as map and as go lang var we may prefer refering them as per distribution and not as per major version

eg:
  ```go 
var distributionsPackages = map[string][]string{"rhel-84": {"packege1", "package2"}}
```

Think we should keep it very simple and do not rely on calculations, as we have no standard to follow. and we do not know the major version is for for which  dist.

2022-05-30 14:12 UTC, ldjebran commented on pkg/services/images.go
> +		defaultOstree := fmt.Sprintf("%s/%s/x86_64/edge", osTreeDistribution, osTreeVersion)
Do not a reason we are calculating the ostree ref , as we we have no standard to follow, 
vote to keep it very simple and readable a map dist => ostree ref  will be very sufficient

```go
var distributionsRefs = map[string]string{
	// I am not afraid to repeat values
	"rhel-84": "rhel/8/x86_64/edge",
	"rhel-85": "rhel/8/x86_64/edge",
	"rhel-90": "rhel/9/x86_64/edge",
}
```

2022-05-30 14:21 UTC, ldjebran reviewed
Think we should keep the initial data very simple , and avoid values calculation.

2022-05-31 08:27 UTC, ldjebran commented on pkg/models/images.go
> +	}
doing so we are modifying the original config slice, what we should not do.

propose 

```go
        requiredPackages := make([]string, 0, len(distributionPackages)+len(config.RequiredPackages))
	requiredPackages = append(requiredPackages, config.RequiredPackages...)
	requiredPackages = append(requiredPackages, distributionPackages...)
```

2022-05-31 08:35 UTC, ldjebran commented on pkg/services/images.go
> +			image.Commit.OSTreeRef = refs
if the image.Distribution does not exist in config.DistributionsRefs   refs will equal ""
think we still  need more cases.

2022-05-31 08:40 UTC, ldjebran commented on config/repo_config.go
> +
Think we still need Default distribution 
```go
const RHEL84 = "rhel-84"
const RHEL85 = "rhel-85"
const RHEL86 = "rhel-86"
const RHEL90 = "rhel-90"

const DefaultDistribution = RHEL85 

```

2022-05-31 18:43 UTC, acosferreira commented on pkg/services/images.go
> +			image.Commit.OSTreeRef = refs
I think in this case if the distribution doesn't exists we should fail the image creation instead set a default, what do you think?

2022-05-31 19:37 UTC, ldjebran commented on pkg/services/images.go
> +			image.Commit.OSTreeRef = refs
Yes let's fail it

2022-05-31 20:09 UTC, acosferreira commented on config/repo_config.go
> +const DefaultDistribution = "rhel-85"
Agreed, we should use the last stable version

2022-05-31 22:02 UTC, loadtheaccumulator approved these changes
lgtm

2022-05-31 22:14 UTC, merged