[WIP] Added fleetkick.sh to inject a kickstart into an ISO, added function …
RedHatInsights/edge-api pull request #119
Opened 2021-07-22 15:29 UTC by AaronH88

…in go to call fleetkick.sh.

WIP!
Feature RHELPLAN-88548 & RHELPLAN-90204

Create a script that can inject a kickstart into an ISO,
Call the script in the correct locations.

Blocked by Pull #117 

Co-author @loadtheaccumulator

2021-07-22 17:23 UTC, loadtheaccumulator commented on pkg/images/images.go
> +	cmd := exec.Command(fleetBashScript, kickstart, image, image, ".")
"." will need to be a subdir instead of . to avoid additional content getting rolled into the ISO

2021-07-27 00:45 UTC, loadtheaccumulator requested changes

2021-07-27 00:45 UTC, loadtheaccumulator commented on pkg/images/images.go
> +	fleetBashScript := absPath + "fleetkick.sh"
fleet kick.sh isn't included in the package on compile, right? I'm adding this to be copied to /usr/local/bin in the Dockerfile under another PR.

So this would change to...
   fleetBashScript := "/usr/local/bin/fleetkick.sh"

2021-07-27 00:47 UTC, loadtheaccumulator commented
@AaronH88 How do you feel about abandoning this PR (or just removing the fleetkick.sh file from it? I need to include it with the Dockerfile change so it won't break the build.

2021-07-27 09:27 UTC, AaronH88 commented on pkg/images/images.go
> +	fleetBashScript := absPath + "fleetkick.sh"
Good idea!

2021-07-27 09:28 UTC, AaronH88 commented
> @AaronH88 How do you feel about abandoning this PR (or just removing the fleetkick.sh file from it? I need to include it with the Dockerfile change so it won't break the build.

Which ever is easier!

2021-07-27 19:36 UTC, biancarosa commented
We have some conflicts here, so if @loadtheaccumulator gets his PR #135 working he might get this piece of code on his PR too

2021-07-28 00:48 UTC, loadtheaccumulator commented
I resolved the conflicts, but seeing different errors.

2021-07-28 14:04 UTC, biancarosa approved these changes
LGTM!

2021-07-28 14:24 UTC, loadtheaccumulator approved these changes

2021-07-28 14:29 UTC, merged