Validate image update
RedHatInsights/edge-api pull request #1219
Opened 2022-06-28 17:19 UTC by acosferreira

# Description

Add validation if we can generate the update image based on current distribution

Fixes # ([issue](https://issues.redhat.com/browse/THEEDGE-2178))

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-06-28 17:28 UTC, InsightsDroid commented
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-d0eefe78-1f0a-4209-b2ab-d2aff5e58e09

2022-06-28 18:09 UTC, omaciel commented on pkg/services/images_test.go
> +					Distribution: "rhel-85",
Maybe use constants or variables to hold `rhel-85` and `rhel-90` as it would simplify updating the test, if needed, in the future?

2022-06-30 12:14 UTC, AaronH88 requested changes

2022-06-30 12:14 UTC, AaronH88 commented on config/repo_config.go
> +var UpgradedAvailable = map[string]string{
Hi Ana, great start,

Lets have a chat today to go over this.

At a high level. 
This file is very important and we need to have a level of encapsulation. We should create some functions that return a `Copy()` of these objects, not pointers to the objects themselves, as this could cause a lot of errors in the future if this map was accidentally changed.

Also, we should try and get this data from a central source. Lets speak to the RHEL for Edge team and discover a way to load in these relationships.

Also, I highly recommend reversing the relationship in this map, and having the map be `string` and `[] string`, this way we save the possible upgrade paths. 

Also, we can change the map name to `UpgradePaths`

And finally, once we have this mappings all get up we can then `Discover_path_to_upgrade()` from one version to another, this becomes a search problem that we could solve with Breath First Search, Depth First Search, but I think we should use Dijkstra's shortest path algorithm, as we dont want to find the first path, but we want to find the shortest path from one to another.

Myself and Djebran will set up a call with you today to go over this :smile:

2022-07-14 18:00 UTC, closed without merging