Added kafka producer code as a singleton.
RedHatInsights/edge-api pull request #1225
Opened 2022-06-29 15:26 UTC by AaronH88

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-06-29 15:37 UTC, loadtheaccumulator reviewed
Should this be in a common pkg to be easily used for routes, services, and the microservices?

2022-06-29 15:43 UTC, AaronH88 commented
This needs to be merged after #1224 as the mods have been fixed in 1224

2022-06-29 15:43 UTC, AaronH88 commented
> Should this be in a common pkg to be easily (or more obviously) used for routes, services, and the microservices?

Any suggestions?

2022-06-29 16:09 UTC, AaronH88 commented
will move to `pkg/common/kafka`

2022-07-05 23:34 UTC, loadtheaccumulator requested changes
Some bits need to be added for auth.

2022-07-05 23:34 UTC, loadtheaccumulator commented on pkg/common/kafka/producer.go
> +			p, err := kafka.NewProducer(&kafka.ConfigMap{
@AaronH88 We'll need to include auth info here as well.
Similar to this... https://github.com/grandcentralstation/kafkavents-junit-client/blob/755947996403dc88c65ddbaf61ec4640e04799f3/src/kafkavents/kafka.go#L81-L95

2022-07-07 05:01 UTC, loadtheaccumulator approved these changes
lgtm

2022-07-07 07:35 UTC, merged