Add -cover to test-clean-no-fdo and test-no-fdo
RedHatInsights/edge-api pull request #1254
Opened 2022-07-07 13:46 UTC by lahavyuv86

# Description

Added '-cover' keyword to our test-clean-no-fdo and test-no-fdo commands to print out the percentage of tests coverage

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-07-07 13:49 UTC, omaciel commented
@lahavyuv86  take a list of the files/folders we won't be executing tests against and add them to the `grep` section of the command to exclude them like `$(go list ./… | grep -v -e /test/ -e /unleash/)`. Make sure to only exclude files/folders we know we don't want to run tests against.

2022-07-07 14:57 UTC, omaciel commented on Makefile
> +EXCLUDE_DIRS=-e /cmd/db -e /cmd/kafka -e /cmd/migrate/orgmigration -e /config -e /pkg/clients/imagebuilder/mock_imagebuilder -e /pkg/imagebuilder/mock_imagebuilder -e /pkg/clients/inventory -e /pkg/c
I think we do want to run tests against `/cmd/migrate/orgmigration`, `/pkg/clients/playbookdispatcher`, `/pkg/clients/inventory`, no?

2022-07-07 15:09 UTC, lahavyuv86 commented on Makefile
> +	go test -count=1 -cover $$(go list ./... | grep -v -e /test/ $(EXCLUDE_DIRS)) $(TEST_OPTIONS)
good idea :)

2022-07-07 15:09 UTC, lahavyuv86 commented on Makefile
> +EXCLUDE_DIRS=-e /cmd/db -e /cmd/kafka -e /cmd/migrate/orgmigration -e /config -e /pkg/clients/imagebuilder/mock_imagebuilder -e /pkg/imagebuilder/mock_imagebuilder -e /pkg/clients/inventory -e /pkg/c
@ldjebran can you verify which dirs we can exclude?

2022-07-08 13:35 UTC, AaronH88 commented
We have specific `coverage` commands in this Makefile, I suggest editing them and not adding coverage to our normal test commands

2022-07-08 15:27 UTC, omaciel commented
Thanks @AaronH88  for pointing this out. Is there a reason why we don't run that then during PR checks? I'd love to see coverage information for every new PR as it gives us information about the health of our code changes

2022-07-08 16:16 UTC, ldjebran commented on Makefile
> +EXCLUDE_DIRS=-e /cmd/db -e /cmd/kafka -e /cmd/migrate/orgmigration -e /config -e /pkg/clients/imagebuilder/mock_imagebuilder -e /pkg/imagebuilder/mock_imagebuilder -e /pkg/clients/inventory -e /pkg/c
we should exclude only those that contain no tests

2022-07-08 16:19 UTC, ldjebran commented on Makefile
> +EXCLUDE_DIRS=-e /cmd/db -e /cmd/kafka -e /cmd/migrate/orgmigration -e /config -e /pkg/clients/imagebuilder/mock_imagebuilder -e /pkg/imagebuilder/mock_imagebuilder -e /pkg/clients/inventory -e /pkg/c
/cmd/migrate/orgmigration  contain tests and should not be excluded

2022-07-13 09:05 UTC, AaronH88 requested changes
Suggest moving these changes to the `coverage` command

2022-07-18 08:22 UTC, AaronH88 approved these changes
/lgtm

2022-07-18 08:36 UTC, merged