iso-tar-content: redirect private content to a signed url .
RedHatInsights/edge-api pull request #1257
Opened 2022-07-08 16:59 UTC by ldjebran

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-07-08 17:34 UTC, omaciel requested changes
Basically asking for more tests, as we have code changes that imho should have tests in place, as well as new code that will benefit from having new tests while everything is still fresh in your mind :)

2022-07-08 17:34 UTC, omaciel commented on pkg/services/files/uploader.go
> +func (u *S3Uploader) uploadFileWithACL(fname string, uploadPath string, acl string) (string, error) {
Are there tests for this module/function?

2022-07-08 17:34 UTC, omaciel commented on pkg/routes/imagesets.go
> +func getStorageInstallerIsoURL(installerID uint) string {
How about a simple test?

2022-07-11 15:19 UTC, ldjebran commented on pkg/routes/imagesets.go
> +func getStorageInstallerIsoURL(installerID uint) string {
done

2022-07-11 15:20 UTC, ldjebran commented on pkg/routes/imagesets.go
> +					imageSetInstallerIsoURL := getStorageInstallerIsoURL(i.Installer.ID)
done

2022-07-11 15:20 UTC, ldjebran commented on pkg/routes/imagesets.go
> +	for _, imageDetail := range details.Images {
done

2022-07-11 15:21 UTC, ldjebran commented on pkg/routes/imagesets.go
> +func getStorageInstallerIsoURL(installerID uint) string {
done

2022-07-12 09:30 UTC, AaronH88 commented on pkg/services/files/downloader.go
> +	d.log.Infof(`sourceURL: "%s" successfully downloaded to destinationPath: "%s"`, sourceURL, destinationPath)
I think this should be `d.log.Debug` else we will have lots of info messages when we redirect a `/repo`

2022-07-12 09:31 UTC, AaronH88 commented on pkg/services/files/downloader.go
> +func (d *S3Downloader) DownloadToPath(sourceURL string, destinationPath string) error {
Is this function thread safe? 

Can I run this in 100 `go` workers? My main concern is the `os.Create()` command? Is that thread safe?

2022-07-12 13:01 UTC, AaronH88 commented on pkg/services/files/s3.go
> +	if cfg.Debug {
If we deploy the app in stage with DEBUG=TRUE will this session be able to access S3?

if we need a new param for local development then I suggest adding a new `Dev` config field

2022-07-12 13:03 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +func (u *S3Uploader) UploadFile(fname string, uploadPath string) (string, error) {
This func is a great idea! Love it

2022-07-12 13:07 UTC, AaronH88 commented on pkg/services/repobuilder.go
> +		rb.log.WithFields(log.Fields{"filepath": tarFileName, "imageBuildTarURL": c.ImageBuildTarURL}).Debug("Downloading tar file")
I think this can be a debug message

2022-07-13 08:31 UTC, ldjebran commented on pkg/services/files/downloader.go
> +func (d *S3Downloader) DownloadToPath(sourceURL string, destinationPath string) error {
The os.Create should be an atomic os operation it success or fail, the s3 download manager is thread safe  when writing to file.

2022-07-13 08:33 UTC, ldjebran commented on pkg/services/files/s3.go
> +	if cfg.Debug {
Yes, as we are not changing the behaviour of the s3 session , but only moving the code to an independent location , as the same code got repeated again and again.

2022-07-13 08:53 UTC, AaronH88 commented on pkg/services/files/downloader.go
> +	d.log.Infof(`sourceURL: "%s" successfully downloaded to destinationPath: "%s"`, sourceURL, destinationPath)
Happy with this answer and to keep it the way it currently is

2022-07-13 09:54 UTC, ldjebran commented on pkg/services/files/s3.go
> +func GetNewS3Session() *session.Session {
done

2022-07-13 11:38 UTC, ldjebran commented on pkg/services/files/downloader.go
> +func (d *S3Downloader) DownloadToPath(sourceURL string, destinationPath string) error {
This is the same as for for GetSigned url , will create new issue to investigate on testing s3 functions

2022-07-13 11:41 UTC, ldjebran commented on pkg/services/files/uploader.go
> +func (u *S3Uploader) uploadFileWithACL(fname string, uploadPath string, acl string) (string, error) {
This is the same as for for GetSigned url , will create new issue to investigate on testing s3 functions

2022-07-13 11:44 UTC, ldjebran commented on pkg/services/files/uploader.go
> +func (u *S3Uploader) uploadFileWithACL(fname string, uploadPath string, acl string) (string, error) {
but also here we have a private function

2022-07-13 12:33 UTC, ldjebran commented on pkg/services/files.go
> +func (s *LocalFilesService) GetSignedURL(path string) (string, error) {
done

2022-07-13 12:34 UTC, ldjebran commented on pkg/services/files.go
>  func (s *S3FilesService) GetFile(path string) (io.ReadCloser, error) {
will open an issue about testing app s3 functions

2022-07-13 12:34 UTC, ldjebran commented on pkg/services/files.go
> +func (s *S3FilesService) GetSignedURL(path string) (string, error) {
will open an issue about testing app s3 functions

2022-07-13 12:34 UTC, ldjebran commented on pkg/services/files/downloader.go
> +func (d *S3Downloader) DownloadToPath(sourceURL string, destinationPath string) error {
will open an issue about testing app s3 functions

2022-07-13 12:46 UTC, ldjebran commented
@AaronH88 @omaciel openned an issue THEEDGE-2388 about investigating on unit testing s3 app functions

2022-07-13 13:03 UTC, AaronH88 approved these changes
/lgtm

2022-07-13 13:05 UTC, AaronH88 approved these changes
/lgtm

2022-07-13 13:16 UTC, merged