fix validation for reboot when rebase or upgrad run
RedHatInsights/edge-api pull request #1269
Opened 2022-07-12 23:19 UTC by acosferreira

# Description

The update was failing due a skip task that was using same register.
Ive changed the var and also fix the condition

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-07-12 23:20 UTC, acosferreira commented
@rexwhite can you please help us with the change of template?

2022-07-12 23:29 UTC, loadtheaccumulator approved these changes
lgtm

2022-07-12 23:39 UTC, maxamillion requested changes

2022-07-12 23:39 UTC, maxamillion commented on templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
>        when: ostree_changes_refs=="true"
is the desire here to be a string comparison or should this be a boolean?

2022-07-12 23:39 UTC, maxamillion commented on templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
> +            ('rpmostree_upgrade_out.changed == true and "Staging deployment...done" in rpmostree_upgrade_out.stdout')
I'm not certain these need `'` quotes on each parenthesized conditional, we should be able to wrap the entire conditional covering both parentheses statements and the `or` .... also, one suggestion is to short circuit `rpmostree_upgrade_out.changed == true` by using `bool` the jinja filter like this `rpmostree_upgrade_out.changed|bool` and then we can perform a conditional on whatever the boolean value is in `rpmostree_upgrade_out.changed` just as it was a native boolean type instead of having to do a comparison.

2022-07-12 23:39 UTC, maxamillion commented on templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
>        when: ostree_changes_refs=="true"
same question here about the string vs boolean comparison

2022-07-12 23:39 UTC, maxamillion commented on templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
> +      when: ('rpmostree_rebase_out.changed == true and "Staging deployment...done" in rpmostree_rebase_out.out') or
same question/suggestions as previous conditional

2022-07-13 07:43 UTC, mgold1234 reviewed
/lgtm

2022-07-14 13:47 UTC, maxamillion approved these changes

2022-07-14 13:53 UTC, AaronH88 requested changes
pausing for signing

2022-07-14 14:45 UTC, rexwhite commented
I signed the playbook for you and submitted a PR to @acosferreira

You may need to update your tests since the yml file has changed.

2022-07-14 15:43 UTC, AaronH88 approved these changes
/lgtm

2022-07-14 17:20 UTC, merged