Dont Merge: POC Cypress
RedHatInsights/edge-api pull request #1321
Opened 2022-07-28 16:42 UTC by dmzoneill

# Description

Proof of concept to run cypress

2022-08-01 13:42 UTC, loadtheaccumulator requested changes
I added the Do Not Merge label, so automation won't pick it up until ready on approval.

2022-08-01 13:42 UTC, loadtheaccumulator commented on pr_check.sh
> +# source $CICD_ROOT/deploy_ephemeral_env.sh
Does this break the existing checks, and if so, is this temporary to test Cypress?

2022-08-03 13:48 UTC, elyezer commented on scripts/ephemeral/cypress.sh
> +# git checkout pr-$ghprbPullId
Is this part needed to uncomment so it will run on PR checks with the right branch?

2022-08-03 16:49 UTC, dmzoneill commented on scripts/ephemeral/cypress.sh
> +# git checkout pr-$ghprbPullId
There are X scenarios here.

Firstly, you need to recognize whether the PR is on "Frontend" or the "Backend".

If the PR is on the "Backend", then the basic scenario is to test using cypress from the HEAD of "frontend".
(this is why that's commented out)

If the PR is on the "frontend", then the basic scenario is to test using the PR commit of the "frontend", against of the HEAD of the "backend".

The third scenario, of course, is to use a PR from the FRONTEND and a PR from the BACKEND.
This is tricky.  As you need to provide the PR SHA1 of the opposite repo in order to have this.
We may look at this with the use of a comment or other in the commit message:

against: <SHA1>

2022-08-03 17:12 UTC, loadtheaccumulator commented on pr_check.sh
> +# source $CICD_ROOT/deploy_ephemeral_env.sh
Cool! Thanks!

2022-08-17 17:13 UTC, closed without merging