add fleetkick script and update Dockerfile
RedHatInsights/edge-api pull request #135
Opened 2021-07-27 01:31 UTC by loadtheaccumulator

* Add fleetkick.sh script
* Update Dockerfile to copy fleetkick.sh to /usr/local/bin
* Update Dockerfile to copy templateKickstart.ks to /usr/local/etc
* Update image.go to use /usr/local/etc/templateKickstart.ks

Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

2021-07-27 16:41 UTC, loadtheaccumulator commented on Dockerfile
> +COPY pkg/images/templateKickstart.ks /usr/local/etc
Changing this to copy from builder instead of external env. Testing and will push to PR

2021-07-28 09:29 UTC, AaronH88 commented on pkg/images/images.go
> +	kickTemplatePath := "/usr/local/etc/templateKickstart.ks"
Can we drop these changes to images.go please and continue to pull the templateKickstart location from the env vars.

This makes debugging locally easier without having to build via Docker.

2021-07-28 09:59 UTC, AaronH88 requested changes

2021-07-28 09:59 UTC, AaronH88 commented on pkg/images/images.go
> +	log.Infof("Opening file %s", kickTemplatePath)
take from env var please

2021-07-28 09:59 UTC, AaronH88 commented on pkg/images/images.go
> +	t, err := template.ParseFiles(kickTemplatePath)
and here also, take from env var please

2021-07-28 09:59 UTC, AaronH88 commented on Dockerfile
> +COPY --from=builder /src/mypackage/myapp/pkg/images/fleetkick.sh /usr/local/bin
we are sure that `/usr/local/*` exists on this docker image?

2021-07-28 10:55 UTC, AaronH88 commented on Dockerfile
> +FROM quay.io/loadtheaccumulator/ubi8-isotools:latest
pulling from quay now? Should we set up a team account rather than pull from your own account?

2021-07-28 11:00 UTC, AaronH88 commented on pkg/images/fleetkick.sh
> +    #[[ -e $ISO ]] && 7z x $ISO -o${DIR} || (echo "ERROR: no ISO" && exit 1)
Do you want to keep this commented out code in here?

2021-07-28 12:42 UTC, loadtheaccumulator commented on pkg/images/images.go
> +	kickTemplatePath := "/usr/local/etc/templateKickstart.ks"
Yeah. I don't remember cfg being in there when I changed that, so looks like some changes were in between now and then.

2021-07-28 12:56 UTC, loadtheaccumulator commented on Dockerfile
> +FROM quay.io/loadtheaccumulator/ubi8-isotools:latest
This is temporary. We should be able to skip this step once we are on a Jenkins with subman creds.

2021-07-28 12:59 UTC, omaciel commented on Dockerfile
> +FROM quay.io/loadtheaccumulator/ubi8-isotools:latest
Could we use https://quay.io/repository/cloudservices/ eventually?

2021-07-28 12:59 UTC, loadtheaccumulator commented on pkg/images/fleetkick.sh
> +    #[[ -e $ISO ]] && 7z x $ISO -o${DIR} || (echo "ERROR: no ISO" && exit 1)
I have to do another push, so I can remove it with it.

2021-07-28 13:12 UTC, loadtheaccumulator commented on Dockerfile
> +FROM quay.io/loadtheaccumulator/ubi8-isotools:latest
Yes. If it sticks. I'm hoping this will go away by EOD today. Keeping this image up-to-date with ubi8 will be an extra step we don't want to mess with. We also haven't seen any of this work e2e yet.

2021-07-28 13:18 UTC, loadtheaccumulator commented on Dockerfile
> +COPY --from=builder /src/mypackage/myapp/pkg/images/fleetkick.sh /usr/local/bin
Absolutely...
[jholloway@storage-qe14 ~]$ podman run -it --rm quay.io/loadtheaccumulator/ubi8-isotools:latest /bin/bash
[root@c5dd75841e3f /]# ls /usr/local
bin  etc  games  include  lib  lib64  libexec  sbin  share  src

2021-07-28 13:43 UTC, loadtheaccumulator commented on pkg/images/images.go
> +	kickTemplatePath := "/usr/local/etc/templateKickstart.ks"
File removed from this PR.

2021-07-28 13:56 UTC, AaronH88 commented on Dockerfile
> +COPY --from=builder /src/mypackage/myapp/pkg/images/fleetkick.sh /usr/local/bin
Beautiful!

2021-07-28 13:57 UTC, AaronH88 commented on Dockerfile
> +FROM quay.io/loadtheaccumulator/ubi8-isotools:latest
Nice, makes sense to me now, ty

2021-07-28 13:58 UTC, AaronH88 approved these changes
Looks good to me! OK to merge

2021-07-28 14:06 UTC, biancarosa approved these changes
LGTM! Great work here @loadtheaccumulator! 👏🏻

2021-07-28 14:06 UTC, merged