add retrycreateimage on case when worker stop responding
RedHatInsights/edge-api pull request #1382
Opened 2022-08-16 12:36 UTC by mgold1234

related to- THEEDGE-2419

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-08-16 12:49 UTC, loadtheaccumulator requested changes
RetryCreateImage starts at the beginning. Consider marking the image status as INTERRUPTED in the database and exit the Create or Update so the resume process can pick it up.

We use this line in the interrupt code to set it when the application receives and SIGTERM...
https://github.com/RedHatInsights/edge-api/blob/ca945f0cf65066123ddc5c44af521ba36cedcdd5/pkg/services/images.go#L596

2022-08-16 13:49 UTC, loadtheaccumulator requested changes
Meant to put my comment inline...

2022-08-16 13:49 UTC, loadtheaccumulator commented on pkg/services/images.go
> +				err := s.RetryCreateImage(image)
RetryCreateImage starts at the beginning. Consider marking the image status as INTERRUPTED in the database and exit the Create or Update so the resume process can pick it up.

We use this line in the interrupt code to set it when the application receives a SIGTERM...
https://github.com/RedHatInsights/edge-api/blob/ca945f0cf65066123ddc5c44af521ba36cedcdd5/pkg/services/images.go#L596

2022-08-16 20:51 UTC, mgold1234 commented on pkg/services/images.go
> +				err := s.RetryCreateImage(image)
where I can add this row? before retry create image?

2022-08-17 13:12 UTC, loadtheaccumulator commented on pkg/services/images.go
> +				err := s.RetryCreateImage(image)
In place of retry create image.

2022-08-17 13:13 UTC, loadtheaccumulator commented
Changes look good so far. Just to need to catch anything else that might change the status to ERROR before it exits the build process.

2022-08-17 13:15 UTC, loadtheaccumulator commented
And it might be possible to refactor a bit and leverage the context to exit immediately.

2022-09-07 12:31 UTC, ldjebran commented on pkg/services/images_test.go
> +				mockImageService.EXPECT().UpdateImageStatus(&image).Return(&image, expectedErr)
we should not mock the image service

2022-09-07 12:32 UTC, ldjebran commented on pkg/services/images_test.go
> +				Expect(image.ID).To(Equal(uint(0)))
we should reload the image from the DB, and test it's current status

2022-09-07 12:34 UTC, ldjebran commented on pkg/services/images.go
> +		if strings.Contains(err.Error(), "running this job stopped responding") {
we are missing the logic that we should not put image in interrupted status if image life time exceed 3 hours.

2022-09-08 15:52 UTC, ldjebran commented on pkg/services/images_test.go
> +		//requestID := faker.UUIDHyphenated()
remove the comments

2022-09-08 15:58 UTC, ldjebran submitted a review, later dismissed
lgtm,  @loadtheaccumulator can you make a second pass.

2022-09-08 16:18 UTC, ldjebran commented on pkg/services/images.go
> +			if strings.Contains(err.Error(), "running this job stopped responding") &&
are you sure we are receiving client error with this error text in it ?
as I saw the code we receive 200 even if there is a building error, the client error concern only client failure to connect to host, but in case of building failure we have to check the data received.

2022-09-08 16:25 UTC, ldjebran commented on pkg/services/images.go
> +			if strings.Contains(err.Error(), "running this job stopped responding") &&
you have to begin here https://github.com/RedHatInsights/edge-api/blob/42659319ae79e0c0575cc99ba82f8b89f2c93dad/pkg/clients/imagebuilder/client.go#L311

analyse ComposeStatus  may be add reason field , you have to go to image builder and see the structure returned 
so that you can add the reason why it's failing

2022-09-08 16:29 UTC, ldjebran commented on pkg/services/images.go
> +			if strings.Contains(err.Error(), "running this job stopped responding") &&
image builder ComposeStatus https://github.com/osbuild/image-builder/blob/main/internal/v1/api.yaml#L276
ComposeStatusError https://github.com/osbuild/image-builder/blob/main/internal/v1/api.yaml#L294

2022-09-12 09:39 UTC, AaronH88 commented on pkg/services/images.go
> +				time.Now().Sub(image.CreatedAt.Time).Hours() <= 3 {
@loadtheaccumulator does your interrupted code also check for a 3 hour timeout? Is this a duplication?

2022-09-13 16:04 UTC, loadtheaccumulator commented on pkg/services/images.go
> +				time.Now().Sub(image.CreatedAt.Time).Hours() <= 3 {
@AaronH88 yes. it handles stale interrupted builds.

2022-09-13 16:06 UTC, AaronH88 commented on pkg/services/images.go
> +				time.Now().Sub(image.CreatedAt.Time).Hours() <= 3 {
OK, this is a duplication and is not needed here :smile:

2022-09-14 10:18 UTC, AaronH88 approved these changes
/lgtm

2022-09-14 13:18 UTC, tomershinhar approved these changes
LGTM

2022-09-15 09:04 UTC, mgold1234 commented
/retest

2022-09-15 10:11 UTC, merged