Added Guidlines for PR's in the Contributing.md file.
RedHatInsights/edge-api pull request #1398
Opened 2022-08-19 14:26 UTC by AaronH88

# Description

Added more guidelines for contributing to edge api

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-08-19 14:38 UTC, de1987 commented
Where can I sign? **+1**

Just one addition, we should create a mindset to review often, because PRs might get stalled waiting a long time for reviews.

2022-08-19 15:06 UTC, AaronH88 commented
> Where can I sign? **+1**
> 
> Just one addition, we should create a mindset to review often, because PRs might get stalled waiting a long time for reviews.

Here is how I think it can be enforced: https://github.blog/2018-03-23-require-multiple-reviewers/

Waiting on the team to agree before enforcing anything :smile:

2022-08-19 15:09 UTC, de1987 commented
> > Where can I sign? **+1**
> > Just one addition, we should create a mindset to review often, because PRs might get stalled waiting a long time for reviews.
> 
> Here is how I think it can be enforced: https://github.blog/2018-03-23-require-multiple-reviewers/
> 
> Waiting on the team to agree before enforcing anything smile

Cool!
We might need to update `mergify` conditions too.

2022-08-19 23:07 UTC, loadtheaccumulator reviewed
This is a great start!

2022-08-19 23:07 UTC, loadtheaccumulator commented on CONTRIBUTING.md
> +## Guidlines for submitting a Pull Request
/Guidlines/Guidelines/

2022-08-20 02:26 UTC, loadtheaccumulator requested changes

2022-08-20 02:26 UTC, loadtheaccumulator commented on CONTRIBUTING.md
> +- Squash your commits.
For anyone unfamiliar with git and the concept of squashing, recommending...

"Squash your commits. Each PR should contain only one commit"

2022-08-20 17:30 UTC, omaciel commented on CONTRIBUTING.md
> +In order to succesfully submit a PR we recommend the following guidlines:
s/guidlines/guidelines

2022-08-20 17:31 UTC, omaciel commented on CONTRIBUTING.md
> +- We work off of a +2 system, where every reviewer can give a +1 if they are happy with the changes. 2 reviewers are required to merge a PR, but if you feel your PR is partially complicated, you can
s/partially/particularly

2022-08-20 17:34 UTC, omaciel commented
How about adding guidelines around the name of the PRs themselves? For instance, if the change is related to a JIRA ticket, we could have it start with `THEEDGE-1234:` followed by the description, or the comment itself could add something like `Addresses|Resolves|Fixes THEEDGE-1234.` It could be helpful to generate better release logs automatically?

2022-08-22 08:55 UTC, AaronH88 commented on CONTRIBUTING.md
> +- We work off of a +2 system, where every reviewer can give a +1 if they are happy with the changes. 2 reviewers are required to merge a PR, but if you feel your PR is partially complicated, you can
Ty!

2022-08-22 08:55 UTC, AaronH88 commented on CONTRIBUTING.md
> +In order to succesfully submit a PR we recommend the following guidlines:
Ty!

2022-08-22 08:55 UTC, AaronH88 commented on CONTRIBUTING.md
> +## Guidlines for submitting a Pull Request
Ty!

2022-08-22 08:56 UTC, AaronH88 commented
> How about adding guidelines around the name of the PRs themselves? For instance, if the change is related to a JIRA ticket, we could have it start with `THEEDGE-1234:` followed by the description, or the comment itself could add something like `Addresses|Resolves|Fixes THEEDGE-1234.` It could be helpful to generate better release logs automatically?

Good suggestion. Added, and expanded slightly to include Bugzilla.

2022-08-22 22:34 UTC, loadtheaccumulator commented
@AaronH88 How about a technical debt line about rather than going back to change, consolidate, etc. in a refactor later, just do it then--even if it runs you past Sprint end.

2022-08-23 07:34 UTC, AaronH88 commented
> @AaronH88 How about a technical debt line about rather than going back to change, consolidate, etc. in a refactor later, just do it then--even if it runs you past Sprint end.

Interesting, can I get a sentence from you on how to word that please?

2022-08-23 20:46 UTC, loadtheaccumulator commented
> Interesting, can I get a sentence from you on how to word that please?

"TECHNICAL DEBT: When dropping a // FIXME: or // TODO: in your code, consider going ahead and making that change--even if it means crossing into the next Sprint.

2022-08-24 17:59 UTC, acosferreira commented on CONTRIBUTING.md
> +- Any new PR must have unit tests. Unit tests do not count towards the total number of lines of code.
Can we add a coverage validation to dont allow merge if decreases?

2022-08-29 09:23 UTC, AaronH88 commented on CONTRIBUTING.md
> +- Any new PR must have unit tests. Unit tests do not count towards the total number of lines of code.
Added

2022-08-29 09:24 UTC, AaronH88 commented on CONTRIBUTING.md
> +- Squash your commits.
Added

2022-08-30 15:55 UTC, loadtheaccumulator approved these changes

2022-09-01 08:09 UTC, mgold1234 approved these changes
I like the idea!
/lgtm

2022-09-06 09:45 UTC, ldjebran approved these changes

2022-09-06 09:45 UTC, merged