Fix device creation
RedHatInsights/edge-api pull request #1417
Opened 2022-08-25 18:11 UTC by acosferreira

# Description
fix condition to UUID unique on devices, fix on conflict clause; Adjust tests

Fixes # ([2519](https://issues.redhat.com/browse/THEEDGE-2519))

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-08-25 18:16 UTC, omaciel commented on pkg/services/devices.go
> +	// result := db.DB.Debug().Clauses(clause.OnConflict{DoNothing: true}).Create(&newDevice)
Do you want to keep this commented out?

2022-08-25 18:19 UTC, acosferreira commented on pkg/services/devices.go
> +	// result := db.DB.Debug().Clauses(clause.OnConflict{DoNothing: true}).Create(&newDevice)
I'm still testing if we should really do nothing or update the lastseen

2022-08-25 20:33 UTC, loadtheaccumulator requested changes
I just have the one request for a comment describing what that line is doing and maybe why it's important.

2022-08-25 20:33 UTC, loadtheaccumulator commented on pkg/services/devices.go
> +	result := db.DB.Debug().Where(&models.Device{UUID: newDevice.UUID}).FirstOrCreate(&newDevice)
Please add a comment on what this line is doing and maybe why.

2022-08-29 09:31 UTC, AaronH88 commented on pkg/services/devices.go
> +	s.log.WithFields(log.Fields{
This log (if needed) should be moved down to where the device is actually deleted.

I also think this log should be at the debug level.

2022-08-30 06:59 UTC, acosferreira commented on pkg/services/devices.go
> +	s.log.WithFields(log.Fields{
@AaronH88 i've moved as suggested.
And I've added this log due to the many devices being created and deleted with seconds of difference and be able to capture the log if it happened again.

2022-08-30 08:29 UTC, AaronH88 commented
Good work with this.
Have you considered adding something to the BeforeCreate()  function to ensure all UUID's are unique and devices are not duplicated?

https://github.com/RedHatInsights/edge-api/blob/main/pkg/models/devices.go#L99

2022-08-31 23:35 UTC, loadtheaccumulator commented
If it fixes the immediate problem, I'm good with it but I am concerned that Gorm many-to-many introduces unnecessary complexity and invites future issues for what could be a simple CRUD operation with a two-column table managing the relationship. More in the Jira. :-)

2022-09-05 16:08 UTC, de1987 commented on pkg/models/commits.go
> +	ErrDeviceEsists = errors.New("This UUID already exists")
typo

2022-09-07 00:07 UTC, loadtheaccumulator commented on pkg/services/devices_test.go
> +			result := db.DB.Where(models.Device{UUID: event.Host.ID, OrgID: event.Host.OrgID}).First(&savedDevice).Unscoped()
Why Unscoped() here?

2022-09-07 00:07 UTC, loadtheaccumulator commented on pkg/services/devices_test.go
> +			result := db.DB.Where(models.Device{UUID: event.Host.ID, OrgID: event.Host.OrgID}).First(&savedDevice).Unscoped()
Why Unscoped() here

2022-09-07 00:18 UTC, loadtheaccumulator reviewed
/lgtm

2022-09-07 00:21 UTC, loadtheaccumulator approved these changes

2022-09-09 17:51 UTC, thom-at-redhat commented on pkg/services/updates_test.go
> +			db.DB.Debug().Omit("Devices.*").Debug().Create(&updates[0])
Is the second Debug() required?

2022-09-09 17:52 UTC, thom-at-redhat requested changes
2 comments

2022-09-12 12:18 UTC, thom-at-redhat commented on pkg/models/devices.go
> +		log.Error("device already exists %i", result.RowsAffected)
log UUID?

2022-09-13 11:44 UTC, thom-at-redhat approved these changes

2022-09-13 11:57 UTC, merged