Remove Travis check from mergify since lint is done in Github action
RedHatInsights/edge-api pull request #1507
Opened 2022-09-22 21:39 UTC by thom-at-redhat

# Description

Comment out Travis from Mergify rules
Fixed typo where PR check rerun didn't require 2 approved-reviews

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-09-22 23:28 UTC, acosferreira approved these changes
lgtm

2022-09-23 13:17 UTC, de1987 commented on .github/mergify.yml
> +          - "#approved-reviews-by>=2"
nice catch

2022-09-23 13:18 UTC, de1987 approved these changes

2022-09-23 14:14 UTC, de1987 commented
/retest

2022-09-23 14:18 UTC, AaronH88 requested changes

2022-09-23 14:18 UTC, AaronH88 commented on .github/mergify.yml
> +          - "#approved-reviews-by>=2"
If I understand this condition correctly, this is the ability to run `retest` . I left it at one as I think anyone should be able to request a `retest` and not need a second person to confirm

2022-09-23 14:22 UTC, AaronH88 commented on .github/mergify.yml
> +      # - check-success=Travis CI - Pull Request
Feel free to delete these, not just comment it out. It is highly unlikely travis will be coming back

2022-09-23 14:34 UTC, thom-at-redhat commented on .github/mergify.yml
> +      # - check-success=Travis CI - Pull Request
as we later discussed, will be done in a upcoming patch :-)

2022-09-23 14:37 UTC, merged