Removed unnneeded logs.
RedHatInsights/edge-api pull request #1516
Opened 2022-09-27 16:20 UTC by AaronH88

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-09-27 18:21 UTC, loadtheaccumulator requested changes
quick question...

2022-09-27 18:21 UTC, loadtheaccumulator commented on unleash/features/feature.go
> -	log.WithFields(log.Fields{"feature": ff.Name,
Any thoughts about switching both of these to trace level instead?

2022-09-29 08:38 UTC, AaronH88 commented on unleash/features/feature.go
> -	log.WithFields(log.Fields{"feature": ff.Name,
I dont think so, nether log gives any useful information for debugging.
The log here is triggered every time a feature flag is checked, and we have many feature flags now, we are drowning in these logs.

The log in consumers.go has no use at all, its not attached to an event, its not even attached to an edge event, the only use it had was to make sure we are connected to kafka, but we are well past that stage now.

2022-09-29 14:17 UTC, de1987 approved these changes

2022-10-03 16:45 UTC, loadtheaccumulator approved these changes

2022-10-03 16:58 UTC, merged