Make Github actions lint match Makefile and check all issues
RedHatInsights/edge-api pull request #1560
Opened 2022-10-12 14:09 UTC by thom-at-redhat

# Description

Make Github actions lint match Makefile options and check all issues

Fixes # (issue)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-10-12 17:56 UTC, de1987 requested changes

2022-10-12 17:56 UTC, de1987 commented on pkg/services/files/utils.go
> -// objectIsWithinMemoryLimit returns a bool result from compare an object with Cloudwatch Maximum Log Message Size
could you revert the deletion of this comment?

2022-10-12 18:02 UTC, thom-at-redhat commented on pkg/services/files/utils.go
> -// objectIsWithinMemoryLimit returns a bool result from compare an object with Cloudwatch Maximum Log Message Size
should be reverted.  Please verify and resolve

2022-10-12 18:03 UTC, de1987 approved these changes

2022-10-13 07:39 UTC, ldjebran approved these changes

2022-10-13 12:14 UTC, thom-at-redhat commented
@mergifyio refresh

2022-10-13 12:15 UTC, thom-at-redhat commented
@mergifyio refresh

2022-10-13 12:35 UTC, merged