EDGE1704: add events_test
RedHatInsights/edge-api pull request #1572
Opened 2022-10-15 14:40 UTC by loadtheaccumulator

Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description
Adding unit test for pkg/models/events.go

Fixes # (issue) THEEDGE-1704

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-10-17 15:44 UTC, omaciel requested changes
I'll be happy with comments :P

2022-10-17 15:44 UTC, omaciel commented on pkg/models/events_test.go
> +	ident := edgeBasePayload.GetIdentity()
How about adding a comment to explain the test? It might be beneficial for anyone who might have to maintain or augment this later

2022-10-17 16:22 UTC, de1987 commented on pkg/models/events_test.go
> +	"github.com/magiconair/properties/assert"
https://onsi.github.io/gomega/#using-gomega-with-golangs-xunit-style-tests

2022-10-18 10:07 UTC, AaronH88 commented on pkg/models/events_test.go
> +	Identity:       identity.XRHID{Identity: identity.Identity{OrgID: "1234567890"}},
Please use the defaults for your params,
There is a default org id we can use. 
Feel free to create a default Request ID if one dosent exist

2022-10-18 10:08 UTC, AaronH88 commented on pkg/models/events_test.go
> +	"github.com/magiconair/properties/assert"
I dont believe gomega is a hard requirement for these tests

2022-10-18 12:04 UTC, omaciel requested changes
Almost there... ;)

2022-10-18 16:57 UTC, loadtheaccumulator commented on pkg/models/events_test.go
> +	RequestID:      "1234567890",
I'll reference the struct directly from the assert since it's already defined.

2022-10-18 17:35 UTC, omaciel submitted a review, later dismissed
/lgtm

2022-10-18 20:22 UTC, loadtheaccumulator commented on pkg/models/events_test.go
> +	"github.com/magiconair/properties/assert"
We're using the magiconair lib for existing tests (images_test), and it was less involved than gomega for these two simple tests. The native golang library does not accept the reason as a parameter, so took me back a step.
Let me know if it's a blocker, but the next PRs are delayed and will run into the next Sprint.

2022-10-19 07:44 UTC, AaronH88 approved these changes
/lgtm

2022-10-19 10:10 UTC, thom-at-redhat approved these changes

2022-10-19 10:26 UTC, merged