edge2408: facilitate config allow list for app startups
RedHatInsights/edge-api pull request #1575
Opened 2022-10-17 04:25 UTC by loadtheaccumulator

Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Add a startup log function to only log non-sensitive EdgeConfig fields and redact passwords from REST URLs

Fixes # (issue) THEEDGE-2408

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-10-17 07:15 UTC, mgold1234 submitted a review, later dismissed
/lgtm

2022-10-17 12:42 UTC, ldjebran commented on config/config.go
> +		"EdgeAPIServiceHost":       cfg.EdgeAPIServiceHost,
Maybe we should also add 
```go 
"EdgeCertAPIURL": cfg.EdgeCertAPIBaseURL
```
This will be useful for debug when device updates, what do you think?

2022-10-17 16:35 UTC, de1987 requested changes
Og mentioned and I agree too, it would be great to have some tests for those changes.

2022-10-17 16:35 UTC, de1987 commented on config/config.go
> +		}
I would suggest using clean code practices here.
Create a function and move this to a function to avoid complexity in the code.
It will help being easily readable for future maintainers.

2022-10-18 10:10 UTC, AaronH88 commented on main.go
>  	log.WithFields(configValues).Info("Configuration Values")
Please go ahead and remove this line now so we dont forget :smile:

2022-10-18 10:11 UTC, AaronH88 commented on config/config.go
> +		value := reflect.ValueOf(v)
consider using this on the value of v : https://github.com/RedHatInsights/edge-api/pull/1532/files

2022-10-18 21:50 UTC, loadtheaccumulator commented on config/config.go
> +		value := reflect.ValueOf(v)
Considered, and objectIsWithinMemoryLimit() is not exported for use outside of the files package.
I'd "like" that to be handled in a separate PR.

I rabbit-holed on a circular dependancy between several files when I exported it, and backed out to the scope of this change.

2022-10-18 23:28 UTC, loadtheaccumulator commented on main.go
>  	log.WithFields(configValues).Info("Configuration Values")
That was about being able to see the values in comparison, because we need to spike on fields we want to see.

2022-10-18 23:37 UTC, loadtheaccumulator commented on main.go
>  	log.WithFields(configValues).Info("Configuration Values")
And I can’t forget that one. :-)

2022-10-19 07:46 UTC, AaronH88 commented on config/config.go
> +		value := reflect.ValueOf(v)
Seems like a good idea

2022-10-19 07:47 UTC, AaronH88 approved these changes
/lgtm

2022-10-19 21:26 UTC, merged

2022-10-19 22:04 UTC, thom-at-redhat commented
After the fact /lgtm