fix validation against commit and images, add scenario to prevent rol…
RedHatInsights/edge-api pull request #1606
Opened 2022-10-25 22:33 UTC by acosferreira

# Description

Fix the validation under commitId and images
Prevent rollback on update when pass commitId
Add tests 

Fixes # (THEEDGE-2654)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-10-25 23:44 UTC, omaciel requested changes
Add unittest for conditional statement please

2022-10-25 23:44 UTC, omaciel commented on pkg/services/commits.go
> +	if imageSetDevices.Commit_Id > commitID {
Unittest please

2022-10-26 06:15 UTC, acosferreira commented on pkg/routes/updates_test.go
> +			It("should not allow to update", func() {
@omaciel follow the test for the scenario with minor commit, I should not be able to update

2022-10-26 07:57 UTC, AaronH88 commented on pkg/routes/updates_test.go
> +				// Expect(response.Message).To(Equal("There are no updates to perform"))
Is checking the response message needed?

2022-10-26 07:59 UTC, AaronH88 commented on pkg/services/commits.go
> +	if result := db.Org(orgID, "devices").Table("devices").Debug().
Is `Debug()` needed? Are we looking for this gorm log?

2022-10-26 08:07 UTC, AaronH88 commented on pkg/services/commits.go
> +		Joins("JOIN images ON devices.image_id = images.id join COMMITS on commits.ID = images.commit_id").
We seem to be mixing gorm syntax and SQL syntax here, It looks like the gorm way to do this is something like : 
`Joins("JOIN images ON devices.image_id = images.id).Joins(JOIN COMMITS on commits.ID = images.commit_id").`

I suggest keeping one syntax for readability :smile:

2022-10-26 08:09 UTC, AaronH88 commented on pkg/services/commits.go
>  		Find(&imageSetsDevices); result.Error != nil {
So in this query we have joined the `image set` , `images` and `devices` tables, this is a lot of data. Is all of this data needed?

If not everything is needed then please consider using the gorm `Scan()` function to only take needed data from a table.

2022-10-26 08:09 UTC, AaronH88 commented on pkg/services/commits.go
>  		Find(&imageSetsDevices); result.Error != nil {
https://gorm.io/docs/query.html#Scan

2022-10-26 12:19 UTC, ldjebran commented on pkg/routes/updates.go
> +			}).Error(err.Error())
we need to have a message what failed ValidateDevicesImageSetWithCommit failure  
or any phrase that indicate that, anyway the error message is already there.

2022-10-26 14:53 UTC, omaciel commented on pkg/routes/updates_test.go
> +			It("should not allow to update", func() {
@acosferreira even if we're indirectly testing the conditional statement for the `services/commits.go` package, I feel that having a `services/commits_test.go` test suite would be well worth the investment for us. So if not for this PR, then we should aim to add tests for `services/commits.go` or we run the risk of never handling our own technical debt AND decreasing our level of confidence for future pushes to PROD.

2022-10-26 20:15 UTC, omaciel commented on pkg/services/commits_test.go
> +	Context("ValidateDevicesImageSetWithCommit", func() {
Great! How about some positive tests too, please?

2022-10-26 20:25 UTC, omaciel approved these changes
My concern/request about adding unit tests have been addressed.

2022-10-27 15:15 UTC, de1987 commented on pkg/routes/updates.go
> +			}).Error(err.Error())
yeah, the `err.Error()` is attached as a field, so we should get the info about it
should we not?

2022-10-27 15:19 UTC, de1987 commented on pkg/routes/updates_test.go
> +			It("should update to version 3 and see 4,5 availble", func() {
```suggestion
			It("should update to version 3 and see 4,5 available", func() {
```
typo

2022-10-27 15:27 UTC, de1987 requested changes

2022-10-27 15:27 UTC, de1987 commented on pkg/routes/updates_test.go
> +				mockUpdateService.EXPECT().BuildUpdateTransactions(gomock.Any(), orgID, gomock.Any()).Return(&[]models.UpdateTransaction{}, nil)
instead of using `gomock.Any()`
I would suggest checking for the expected content which will increase our confidence in the code.

2022-10-27 15:27 UTC, de1987 commented on pkg/routes/updates_test.go
> +			It("should update to version 4 and see only 5 availble", func() {
```suggestion
			It("should update to version 4 and see only 5 available", func() {
```
typo

2022-10-27 22:39 UTC, de1987 commented on pkg/routes/updates_test.go
> +				var desiredCommit models.Commit
nice name, it will help the team understand more about mocks

2022-10-27 22:42 UTC, de1987 approved these changes

2022-10-27 23:02 UTC, omaciel approved these changes
/lgtm

2022-10-27 23:08 UTC, merged