Add Packages Metadata from imagebuilder
RedHatInsights/edge-api pull request #161
Opened 2021-08-04 16:21 UTC by Saurabh-Thakre

Signed-off-by: Saurabh Thakre sthakre@redhat.com

2021-08-04 17:13 UTC, biancarosa requested changes

2021-08-04 17:13 UTC, biancarosa commented on pkg/imagebuilder/client.go
> +	InstalledPackage []InstalledPackage `json:"packages"`
```suggestion
	InstalledPackages []InstalledPackage `json:"packages"`
```

Can we call this field InstalledPackages to make it clear that is it a list?

2021-08-04 17:13 UTC, biancarosa commented on pkg/imagebuilder/client.go
> +	installed_package := models.Commit{}
Do we really need this? installed packages are already on the OsTree struct itself, one unmarshall should do the trick.

2021-08-04 17:13 UTC, biancarosa commented on pkg/imagebuilder/client.go
> +	for n < countPackage {
Range (https://tour.golang.org/moretypes/16) is a nice way to loop without creating this variable.

2021-08-04 17:13 UTC, biancarosa commented on pkg/imagebuilder/client.go
>  	json.Unmarshal(data, &ostree_struct)
I think this Unmarshall needs to happen before this loop, otherwise ostree_struct won't be filled with the data.

2021-08-04 17:13 UTC, biancarosa commented on pkg/imagebuilder/client.go
> +		installed_package.InstalledPackage = installed_pkgs
I think we might need append here: https://tour.golang.org/moretypes/15

2021-08-04 17:20 UTC, Saurabh-Thakre commented on pkg/imagebuilder/client.go
> +	InstalledPackage []InstalledPackage `json:"packages"`
sure, makes sense

2021-08-04 17:52 UTC, Saurabh-Thakre commented on pkg/imagebuilder/client.go
> +	installed_package := models.Commit{}
Yeah we would need **installed_package**, as we can not put **installed_pkg** in **ostree_struct.InstalledPackages** as it'd be of a different type.

2021-08-05 15:04 UTC, biancarosa commented on pkg/imagebuilder/client.go
> +	installed_package := models.Commit{}
But I think this should be created inside of the loop, right? Otherwise you're creating an empty object here and adding it to the list over an over.

2021-08-09 16:26 UTC, biancarosa approved these changes
Looks really good!

2021-08-09 16:59 UTC, merged