add total packages to be used on FE
RedHatInsights/edge-api pull request #1612
Opened 2022-10-28 06:38 UTC by acosferreira

# Description
Add field to be used on FE

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-10-28 11:47 UTC, omaciel requested changes
It looks great but it needs unittests

2022-11-01 15:44 UTC, de1987 approved these changes

2022-11-01 16:42 UTC, thom-at-redhat approved these changes

2022-11-01 16:46 UTC, thom-at-redhat commented
> It looks great but it needs unittests
Added in [47e5e9c]
Marking as done

2022-11-01 16:48 UTC, merged

2022-11-01 19:18 UTC, mgold1234 reviewed
/lgtm