Add Consumer interface to allow mocking.
RedHatInsights/edge-api pull request #1616
Opened 2022-10-31 14:06 UTC by mgold1234

realted to THEEDGE-2678

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-03 10:08 UTC, AaronH88 commented on pkg/services/consumers.go
> +type Consumer interface {
I think this interface should live in /pkg/comon/kafka

2022-11-03 10:19 UTC, AaronH88 commented
I am failing to see how mocks can be injected into this solution. Can you write some example tests please and show how your solution works

2022-11-04 10:41 UTC, AaronH88 commented
Looks like we are getting closer, but again, can you please use these mocks in tests and prove that your proposal works.

Here is a PR where I used the producer mocks: https://github.com/RedHatInsights/edge-api/pull/1582/files

2022-11-07 09:22 UTC, AaronH88 commented on pkg/services/image/event_image_iso_requested_test.go
> +					consumer := mockConsumerService.EXPECT().GetConsumer(groupIDConsumer).Return(mockConsumer, nil)
This is just being initialised, not being used. 
The syntax looks ok, you just need to test a consumer, 
In the file `event_image_iso_requested.go` we do not use a kafka consumer

2022-11-08 09:01 UTC, AaronH88 commented on pkg/common/kafka/consumer_test.go
> +package kafkacommon_test
Lets go ahead and write this test file

2022-11-08 09:04 UTC, AaronH88 commented on pkg/services/images_iso/main_test.go
> +					err := mockConsumer.EXPECT().Poll(timeout).Return(cloudEvent)
Great!

Now time for the rest of the tests, 
Returning an error, no consumer etc.

2022-11-08 15:59 UTC, mgold1234 commented
/retest

2022-11-08 17:09 UTC, AaronH88 commented on pkg/common/kafka/consumer_test.go
> +var _ = Describe("Image Iso Kafka Consumer Test", func() {
This is not an ISO test, this describe is misleading

2022-11-08 17:11 UTC, AaronH88 commented
Please dont upload the binary file [pkg/services/1667593625653020087-services.db-journal](https://github.com/RedHatInsights/edge-api/pull/1616/files#diff-2574cadc9233e01e4ad5c075d116233c0d806081e97b91d099bbc6e24beddde0)

2022-11-08 21:08 UTC, mgold1234 commented
/retest

2022-11-10 09:16 UTC, AaronH88 commented on pkg/services/image/event_image_iso_requested_test.go
> +					consumer := mockConsumerService.EXPECT().GetConsumer(groupIDConsumer).Return(mockConsumer, nil)
This code is still not being used. Im surprised this is not causing an error. Is this test correctly being run?

2022-11-10 09:20 UTC, AaronH88 commented on pkg/services/images_iso/main_test.go
> +					err := mockConsumer.EXPECT().Poll(timeout).Return(cloudEvent)
Why did you remove this?
This was correct and is the actual test of the consumer

2022-11-10 09:28 UTC, mgold1234 commented on pkg/services/image/event_image_iso_requested_test.go
> +					consumer := mockConsumerService.EXPECT().GetConsumer(groupIDConsumer).Return(mockConsumer, nil)
@AaronH88 it's look like it running
github.com/redhatinsights/edge-api/pkg/services/image   0.082s

I will remove it for now

2022-11-13 09:56 UTC, mgold1234 commented
/retest

2022-11-13 14:34 UTC, mgold1234 commented
/retest

2022-11-14 13:13 UTC, ldjebran commented on pkg/common/kafka/consumer.go
> +	c, err := kafka.NewConsumer(&kafkaConfigMap)
mabe instead of calling 

```go
kafkaConfigMap := NewKafkaConfigMapService().GetKafkaConsumerConfigMap(groupID)
	c, err := kafka.NewConsumer(&kafkaConfigMap)
```
we should call 

```go 
c, err := GetConsumer(groupID)
```
what do you think ?

2022-11-14 13:16 UTC, ldjebran commented on pkg/common/kafka/consumer_test.go
> +			})
we can test GetInstanceConsumer and verify that GetConsumer get called

2022-11-14 13:26 UTC, ldjebran commented on pkg/common/kafka/consumer.go
> +func (s *ConsumerService) GetInstanceConsumer(topics []string, groupID string) (Consumer, error) {
as this function is not used (maybe this is for future refactoring) mabe should be removed.
what do you think ?

2022-11-14 13:36 UTC, ldjebran reviewed
Looks good left some comments

2022-11-14 14:07 UTC, mgold1234 commented on pkg/common/kafka/consumer.go
> +func (s *ConsumerService) GetInstanceConsumer(topics []string, groupID string) (Consumer, error) {
I will delete this function

2022-11-14 14:08 UTC, mgold1234 commented on pkg/common/kafka/consumer_test.go
> +			})
I will delete this function

2022-11-14 14:09 UTC, mgold1234 commented on pkg/common/kafka/consumer.go
> +	c, err := kafka.NewConsumer(&kafkaConfigMap)
delete this function

2022-11-14 14:15 UTC, mgold1234 commented
/retest

2022-11-14 17:35 UTC, mgold1234 commented
/retest

2022-11-15 11:40 UTC, AaronH88 commented on pkg/common/kafka/consumer.go
> +func (s *ConsumerService) GetConsumer(groupID string) (Consumer, error) {
This exposed function needs a comment in the format `// GetConsumer ...`

2022-11-15 11:43 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> -			if e.Code() == kafka.ErrAllBrokersDown {
Lets go back to using this if statement

2022-11-15 11:43 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> +	// create a base logger with fields to pass through the entire flow
remove this comment please

2022-11-15 12:25 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
I think we have a problem with this context in the current implementation of the consumer, this is not the problem with PR.
so we are passing the context that we globally create and then pass it the Consume function 
think we should create a new context for each event , and after that pass it to Consume function that can add identity to it (new context).

@AaronH88 @loadtheaccumulator what do you think ?
Note This problem exist in images_build also and other microservice

2022-11-15 14:57 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
Where do you suggest this context gets created?

2022-11-15 16:17 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
is this pr can stay as  is, and if we want to refactor it will be in other pr?

2022-11-15 16:25 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
yes , the current can stay as is, as the problem is affecting all the consumers .

I will resolve this comment, waiting for a resolution in an other PR for all the consumers services.

2022-11-15 16:26 UTC, ldjebran submitted a review, later dismissed
LGTM

2022-11-15 16:50 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
when investigating offline we came to the conclusion that line with code 
ctx = image.ContextWithLogger(ctx, mslog)

is creating a copy of our context that is then passed to Consume function

2022-11-15 20:44 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +	edgeAPIServices := dependencies.ServicesFromContext(ctx)
@ldjebran change it as you suggest, thank you for that

2022-11-16 09:22 UTC, mgold1234 commented
/retest

2022-11-16 09:47 UTC, ldjebran commented
/retest

2022-11-16 10:49 UTC, ldjebran commented
/retest

2022-11-16 11:16 UTC, ldjebran submitted a review, later dismissed
LGTM

2022-11-16 11:16 UTC, ldjebran commented
/retest

2022-11-16 15:25 UTC, mgold1234 commented
/retest

2022-11-16 20:24 UTC, mgold1234 commented
/restest

2022-11-16 22:04 UTC, loadtheaccumulator requested changes
requesting some changes and info

2022-11-16 22:04 UTC, loadtheaccumulator commented on pkg/common/kafka/consumer.go
> +type Consumer interface {
Should this only be the methods we use?
What is the process to maintain this if the definitions change upstream?

2022-11-17 08:45 UTC, mgold1234 commented
/retest

2022-11-17 16:22 UTC, mgold1234 commented
/retest

2022-11-17 16:47 UTC, mgold1234 commented on pkg/dependencies/main.go
> +	ConsumerService         kafkacommon.ConsumerServiceInterface
we cannot just call it, because in tests we may need to use the mock service, to use the mock we have to pass the service via context 
in the code we pass the real service, in the tests we pass the mock service

2022-11-18 16:14 UTC, loadtheaccumulator approved these changes

2022-11-18 16:15 UTC, AaronH88 approved these changes
/lgtm

2022-11-18 16:29 UTC, merged