Add pagination to update available
RedHatInsights/edge-api pull request #1622
Opened 2022-11-02 18:00 UTC by acosferreira

# Description

Add pagination to the list of update available for device

Fixes # (THEEDGE-2821)

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-03 10:24 UTC, thom-at-redhat commented on pkg/services/mock_services/devices.go
> +func (mr *MockDeviceServiceInterfaceMockRecorder) GetDevicesView(limit, offset, tx interface{}) *gomock.Call {
Should this be "GetDevicesView(limit, offset int, tx" to match line 69?

2022-11-03 10:31 UTC, thom-at-redhat requested changes

2022-11-03 10:31 UTC, thom-at-redhat commented on pkg/services/mock_services/devices.go
> +func (mr *MockDeviceServiceInterfaceMockRecorder) GetDevicesView(limit, offset, tx interface{}) *gomock.Call {
Should all limits/offsets be the same (i.e. should this line be "GetDevicesView(limit, offset int, tx" to match line 69)?

2022-11-03 13:33 UTC, omaciel requested changes
I don't see unittests for the actual changes that would prove that pagination is actually working. As most of the updates to existing tests are mocking the response, I feel that we're not actually testing the functionality of the modified functions. A unittest for `GetDeviceImageInfoByUUID` for example that returns the expected number of items is exactly what I'm looking for. The same goes for every function that has been modified to include pagination arguments.

2022-11-03 20:06 UTC, omaciel submitted a review, later dismissed
/lgtm

2022-11-03 20:41 UTC, thom-at-redhat approved these changes

2022-11-03 20:53 UTC, omaciel commented
/retest

2022-11-03 22:26 UTC, acosferreira commented
/retest

2022-11-03 23:42 UTC, omaciel commented
@mergify queue edge-api

2022-11-03 23:44 UTC, omaciel commented
/retest

2022-11-03 23:58 UTC, omaciel commented
@mergifyio refresh

2022-11-04 00:01 UTC, omaciel commented
@mergifyio queue

2022-11-04 00:03 UTC, omaciel commented
@mergifyio refresh edge-api

2022-11-04 00:03 UTC, omaciel commented
@mergifyio queue edge-api

2022-11-04 00:08 UTC, omaciel commented
@mergifyio refresh

2022-11-04 00:13 UTC, acosferreira commented
/retest

2022-11-04 00:22 UTC, omaciel commented
/lgtm

2022-11-04 00:49 UTC, matoval approved these changes

2022-11-04 00:56 UTC, matoval commented
@mergifyio refresh

2022-11-04 09:06 UTC, ldjebran commented
/retest

2022-11-04 09:28 UTC, ldjebran commented
@Mergifyio requeue

2022-11-04 10:28 UTC, thom-at-redhat commented
@mergifyio rebase

2022-11-04 10:29 UTC, thom-at-redhat commented
@mergifyio requeue

2022-11-04 16:29 UTC, matoval approved these changes

2022-11-04 17:00 UTC, thom-at-redhat approved these changes

2022-11-04 17:00 UTC, merged