add support to rhel-87
RedHatInsights/edge-api pull request #1635
Opened 2022-11-08 18:55 UTC by acosferreira

# Description

add support to rhel-87

Fixes # (THEEDGE-2807)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-08 18:58 UTC, omaciel requested changes
/lgtm

2022-11-08 18:58 UTC, omaciel commented on config/repo_config.go
> +	"rhel-87": RHEL86,
-"rhel-87": RHEL86,
+"rhel-87": RHEL87,

2022-11-08 20:34 UTC, omaciel commented on config/repo_config.go
> +	"rhel-87": RHEL86,
Anything that can make the code easier to maintain gets a 👍🏻  from me

2022-11-09 13:00 UTC, omaciel commented on config/repo_config.go
>  // DistributionsPackages add packages byi mage
Minor typo: s/byi/by

2022-11-09 15:08 UTC, ldjebran commented on config/repo_config_test.go
> +				Expect(config.DistributionsRefs[d]).To(ContainSubstring("8"))
I would prefer to be more explicit eg:

rhel-84", "rhel-85, "rhel-86", "rhel-87"  all have same ref , so one test is sufficient 

```go
Expect(config.DistributionsRefs[d]).To(Equal("rhel/8/x86_64/edge"))
```

what do you think ?

2022-11-09 15:55 UTC, loadtheaccumulator requested changes
just a couple of minor things

2022-11-09 15:55 UTC, loadtheaccumulator commented on config/repo_config.go
> +// RHEL8X contains additional list of packages to build an image to = RHEL86
Named RHEL8X but the comment refers to RHEL86.

2022-11-09 15:55 UTC, loadtheaccumulator commented on config/repo_config.go
> +// DistributionsPackages add packages by mage
mage typo

2022-11-09 17:25 UTC, acosferreira commented on config/repo_config_test.go
> +				Expect(config.DistributionsRefs[d]).To(ContainSubstring("8"))
make sense ;) 
thanks

2022-11-10 00:28 UTC, omaciel requested changes
How about a test for each distribution's ref?

2022-11-10 00:28 UTC, omaciel commented on config/repo_config_test.go
> +	supportedDistributions := []string{"rhel-84", "rhel-85", "rhel-86", "rhel-87", "rhel-90"}
Use the values from `DistributionsPackages` instead

2022-11-10 00:28 UTC, omaciel commented on config/repo_config_test.go
> +	supportedDistributions := []string{"rhel-84", "rhel-85", "rhel-86", "rhel-87", "rhel-90"}
Use the values from `DistributionsPackages` instead

2022-11-10 00:28 UTC, omaciel commented on config/repo_config_test.go
> +	supportedDistributions := []string{"rhel-84", "rhel-85", "rhel-86", "rhel-87", "rhel-90"}
Use the values from `DistributionsPackages` instead

2022-11-10 00:54 UTC, omaciel submitted a review, later dismissed
/lgtm

2022-11-10 01:09 UTC, loadtheaccumulator requested changes

2022-11-10 01:09 UTC, loadtheaccumulator commented on config/repo_config_test.go
> +func TestInvaliddistribution(t *testing.T) {
This should probably be TestInvalidDistribution.

2022-11-10 01:09 UTC, loadtheaccumulator commented on config/repo_config_test.go
> +package config_test
config_test instead of config?

2022-11-10 01:09 UTC, loadtheaccumulator commented on config/config_suite_test.go
> +package config_test
config_test instead of config package?

2022-11-10 01:28 UTC, omaciel approved these changes
/lgtm

2022-11-10 03:44 UTC, thom-at-redhat approved these changes

2022-11-10 09:26 UTC, AaronH88 approved these changes
/lgtm

2022-11-10 14:05 UTC, de1987 approved these changes

2022-11-10 14:18 UTC, merged