Filter by id on image-sets view route
RedHatInsights/edge-api pull request #1643
Opened 2022-11-10 17:48 UTC by de1987

# Description
Add filter by id on image-sets view route

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-10 18:15 UTC, omaciel approved these changes
/lgtm

2022-11-10 18:34 UTC, acosferreira requested changes

2022-11-10 18:34 UTC, acosferreira commented on pkg/routes/imagesets_test.go
> +		It("The image-sets view route should filter by id", func() {
what should happens when a invalid id was passed? Can you include this test scenario?

2022-11-10 21:10 UTC, de1987 commented on pkg/routes/imagesets_test.go
> +		It("The image-sets view route should filter by id", func() {
done

2022-11-10 21:55 UTC, acosferreira submitted a review, later dismissed
lgtm

2022-11-13 13:11 UTC, tomershinhar commented on pkg/routes/imagesets.go
> +				errs = append(errs, common.ValidationError{Key: "id", Reason: fmt.Sprintf("%s is not a valid id type, id must be number", val)})
maybe it is better to say that id must be an integer?

2022-11-14 13:38 UTC, de1987 commented on pkg/routes/imagesets.go
> +				errs = append(errs, common.ValidationError{Key: "id", Reason: fmt.Sprintf("%s is not a valid id type, id must be number", val)})
@tomershinhar I see your point, here I'm following the pattern of the message from another validation in this function.
I noticed other pieces of the code use the word `integer` as you suggested.
Should we propose to refactor this in all edge-api code?

2022-11-14 13:40 UTC, ldjebran approved these changes
LGTM

2022-11-14 14:46 UTC, de1987 commented on pkg/routes/imagesets.go
> +				errs = append(errs, common.ValidationError{Key: "id", Reason: fmt.Sprintf("%s is not a valid id type, id must be number", val)})
@tomershinhar done

2022-11-14 14:51 UTC, tomershinhar approved these changes
LGTM

2022-11-14 15:08 UTC, ldjebran approved these changes

2022-11-14 15:57 UTC, de1987 commented
/retest

2022-11-14 18:36 UTC, thom-at-redhat commented
@mergifyio rebase

2022-11-14 19:12 UTC, merged