add image completion producers
RedHatInsights/edge-api pull request #1650
Opened 2022-11-14 01:03 UTC by loadtheaccumulator

Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

# Description

Add image step completion producers for commit, repo, and installer

Fixes # (issue)  THEEDGE-2261

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-14 11:39 UTC, ldjebran commented on pkg/routes/common/identity.go
> +func GetIdentityInstanceFromContext(ctx context.Context) (identity.XRHID, error) {
in the same module common we will have two functions that will seems to return the same things,
GetIdentityFromContext 
GetIdentityInstanceFromContext

may be we should rename the function to be more explicit eg:

**GetOriginalIdentityInstanceFromContext**

The name is long but looks obvious 

what do you think ?

2022-11-14 12:00 UTC, mgold1234 reviewed
the changes in go.mod am go.sum related to this pr?

2022-11-14 12:08 UTC, ldjebran commented on pkg/services/images.go
> +			}
we cannot continue here with unknown identity

2022-11-14 12:09 UTC, ldjebran commented on pkg/services/images.go
> +			s.log.WithField("error", err.Error()).Error("Error getting identity from context")
same here,  we cannot continue here with unknown identity.

2022-11-14 12:19 UTC, ldjebran commented on pkg/services/images.go
> +	go s.processImage(context.Background(), image.ID)
this context will have no identity , no requestID 
may be we should use the the service context somehow

2022-11-14 12:27 UTC, ldjebran reviewed
looks good, pending some comments.

2022-11-14 12:34 UTC, mgold1234 commented on pkg/services/images.go
> +func (s *ImageService) ProcessImage(ctx context.Context, img *models.Image) error {
better image instead of IMO,
all other function is with 'image' name and not img

2022-11-14 12:34 UTC, mgold1234 commented on pkg/services/images.go
> +func (s *ImageService) CreateRepoForImage(ctx context.Context, img *models.Image) (*models.Repo, error) {
'image' unstead of img

2022-11-14 13:45 UTC, loadtheaccumulator commented on pkg/routes/common/identity.go
> +func GetIdentityInstanceFromContext(ctx context.Context) (identity.XRHID, error) {
One returns the string and one returns an instance of the struct. I'm not sure what Original adds to it.

2022-11-14 15:17 UTC, loadtheaccumulator commented on pkg/services/images.go
> +	go s.processImage(context.Background(), image.ID)
Actually... looking into why that's still context.Background()... hold please...

2022-11-14 15:19 UTC, loadtheaccumulator commented on pkg/services/images.go
> +	go s.processImage(context.Background(), image.ID)
Ah retry create image. Nice catch! I have to go back and pass that context in from route.

2022-11-14 15:23 UTC, loadtheaccumulator commented on pkg/services/images.go
> +func (s *ImageService) CreateRepoForImage(ctx context.Context, img *models.Image) (*models.Repo, error) {
'image' is a package, and I changed it from i for clarity.

2022-11-14 15:24 UTC, loadtheaccumulator commented on pkg/services/images.go
> +func (s *ImageService) ProcessImage(ctx context.Context, img *models.Image) error {
All other function should change in future refactors as image-related code moves to an image package.

2022-11-14 15:25 UTC, loadtheaccumulator commented
Fixing the go.sum conflict. something might have gone in between my rebase and this PR.

2022-11-14 16:55 UTC, loadtheaccumulator commented on pkg/services/images.go
> +			}
Done

2022-11-14 16:55 UTC, loadtheaccumulator commented on pkg/services/images.go
> +	go s.processImage(context.Background(), image.ID)
Done.

2022-11-14 16:55 UTC, loadtheaccumulator commented on pkg/services/images.go
> +			s.log.WithField("error", err.Error()).Error("Error getting identity from context")
Done.

2022-11-14 21:15 UTC, loadtheaccumulator commented
Not sure why go.mod and go.sum are showing differences. They are matched with main.

2022-11-14 21:29 UTC, loadtheaccumulator commented on pkg/routes/common/identity.go
> +func GetIdentityInstanceFromContext(ctx context.Context) (identity.XRHID, error) {
Ah. @ldjebran . I see what you are saying. For this purpose, there's no guarantee it's the original identity and the function in identityheaders works for pulling from the r.Context(), but not for this purpose. I propose renaming GetIdentityFromContext() in identityheaders.go to GetIdentityFromRequestContext(), and dropping the word original since the only one that has an original identity (currently) is the one pulling from r.Context(). Thoughts?

2022-11-15 11:36 UTC, ldjebran commented on pkg/routes/common/identity.go
> +func GetIdentityInstanceFromContext(ctx context.Context) (identity.XRHID, error) {
Think you are right, but not in the context of this PR (it's too much for this PR), let's do it in another PR,
   in recap propose to let the name **GetIdentityInstanceFromContext** for the moment as is in this PR,
   and then we can open a new PR for the refactoring so that:
   GetIdentityFromContext will became  GetIdentityFromRequestContext
and 
   GetIdentityInstanceFromContext with became GetIdentityFromContext
   what do you think ?

2022-11-15 17:52 UTC, ldjebran commented on pkg/routes/common/identity.go
> +func GetIdentityInstanceFromContext(ctx context.Context) (identity.XRHID, error) {
@loadtheaccumulator resolve this for now, and let's refactor the naming after merge

2022-11-15 17:54 UTC, ldjebran commented
@loadtheaccumulator remove your changes from go.mod and go.sum and rebase

2022-11-16 09:38 UTC, ldjebran approved these changes
LGTM

2022-11-16 09:48 UTC, AaronH88 commented on pkg/services/image/event_image_requested.go
> +	imageService := services.NewImageService(ctx, log)
This makes injecting mocks impossible. 

Before we where attaching the services to the context, this way we could pass in mock services. 
By creating a new image service withing the scope of the event, mocks can no longer be passed in and this becomes untestable

2022-11-16 09:51 UTC, AaronH88 requested changes
event_image_requested is currently untestable

2022-11-16 13:50 UTC, loadtheaccumulator commented on pkg/services/image/event_image_requested.go
> +	imageService := services.NewImageService(ctx, log)
THAT! So back to the hoop jumping.

2022-11-16 15:41 UTC, ldjebran commented on pkg/services/updates.go
> +var WaitGroup sync.WaitGroup
I think this was moved from images file to updates as used only here

2022-11-16 17:34 UTC, loadtheaccumulator commented on pkg/services/updates.go
> +var WaitGroup sync.WaitGroup
Yeah. I  abandoned wait group in images because it was not doing anything for us and left this declaration behind because of a dependency over here. I yanked it in this PR and moved it where it needed to be.

2022-11-16 17:35 UTC, loadtheaccumulator commented on pkg/services/updates.go
> +var WaitGroup sync.WaitGroup
It is used here... 
https://github.com/RedHatInsights/edge-api/blob/c3d5bd0cf19f5e61397f206d174f77fe53d36ea8/pkg/services/updates.go#L137-L144

2022-11-17 01:11 UTC, loadtheaccumulator commented
/retest

2022-11-17 05:30 UTC, loadtheaccumulator commented on pkg/services/image/event_image_requested.go
> +	imageService := services.NewImageService(ctx, log)
Well, not impossible.

2022-11-17 13:37 UTC, loadtheaccumulator commented on pkg/services/image/event_image_requested.go
> +	err = imgService.ProcessImage(ctx, image)
update the logger attached to service so requestid and orgid will pass thru to service methods (the point of plugging in via NewImageService)

2022-11-17 17:28 UTC, closed without merging

2022-11-17 17:28 UTC, loadtheaccumulator commented
Closing this one do to the go.sum go.mod weirdness. See PR #1664