add total packages and system running to image end point
RedHatInsights/edge-api pull request #1660
Opened 2022-11-16 11:24 UTC by mgold1234

realted to issue -THEEDGE-2835

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-16 22:53 UTC, omaciel requested changes
Please add unittests to cover your recent additions and changes.

2022-11-16 22:53 UTC, omaciel commented on pkg/services/images.go
> +		if err != nil {
Can you write a unitest for this specific case, please?

2022-11-16 22:53 UTC, omaciel commented on pkg/services/images.go
> +func (s *ImageService) GetDevicesCountByImage(imageId uint) (int64, error) {
Can you write a unitest for this specific `function`, please?

2022-11-17 10:19 UTC, ldjebran reviewed
looks good, please rename the function and add unit-tests

2022-11-17 12:06 UTC, ldjebran requested changes
it should one place from where get image TotalPackages and TotalDevicesWithImage
and it should be in ImageService as we are filling the model and consider this as a business logic.

2022-11-17 12:07 UTC, ldjebran commented on pkg/services/images.go
> +func (s *ImageService) GetDevicesCountByImage(imageId uint) (int64, error) {
this function has been removed from current PR version

2022-11-19 01:23 UTC, acosferreira commented on pkg/routes/imagesets_test.go
> +			FIt("The app internal iso urls are used when getting imageSet details", func() {
This should be IT, not Fit.

2022-11-21 09:29 UTC, ldjebran commented on pkg/services/images.go
> +		return 0, err
make sense to log this error 
```go
s.log.WithField("error", err.Error()).Error("Error getting orgID from context")
```

2022-11-21 09:32 UTC, ldjebran commented on pkg/services/images.go
> +			s.log.WithField("error", err.Error()).Error("Could not find device image info")
This error message and the error returned does not reflect the true nature of the error,
if we add the first error log in that function, we can remove this log and return the true error
as GetImageDevicesCount will log all the errors

2022-11-21 09:32 UTC, ldjebran commented on pkg/services/images.go
> +			return nil, new(ImageNotFoundError)
```go 
return nil, err
```

2022-11-21 09:47 UTC, ldjebran commented on pkg/services/images_test.go
> +					{OrgID: "00000000", UUID: faker.UUIDHyphenated(), ImageID: image1.ID},
to be more explicit use the same org for clarity 
eg: 
```go 
{OrgID: common.DefaultOrgID, UUID: faker.UUIDHyphenated(), ImageID: image1.ID}, 
 ```
 or use an  initiated org variable and use it everywhere, this will isolate your  tests records from the others.
 
 ```go 
 orgID := faker.UUIDHyphenated()
 ```

2022-11-21 09:47 UTC, ldjebran reviewed
LGTM, left some comments

2022-11-21 15:07 UTC, ldjebran commented on pkg/services/images_test.go
> +				It("should error in case there could not find device info", func() {
```suggestion
				It("GetUpdateInfo should return error when GetImageDevicesCount return error", func() {
```

2022-11-21 15:08 UTC, ldjebran commented on pkg/services/images_test.go
> +				It("should error in case there could not find device info", func() {
```suggestion
				It("GetImageDevicesCount should error when orgID is not defined", func() {
```

2022-11-21 15:10 UTC, ldjebran reviewed
LGTM, minor changes in comments  (about test names)

2022-11-22 08:45 UTC, ldjebran approved these changes
LGTM

2022-11-22 11:28 UTC, tomershinhar commented on pkg/services/images_test.go
> +	AfterEach(func() {
why do we have `AfterEach` ?
it seems to not be doing anything unless i am missing something

2022-11-22 12:43 UTC, tomershinhar approved these changes
LGTM

2022-11-22 13:14 UTC, ldjebran approved these changes

2022-11-22 17:20 UTC, omaciel approved these changes
/lgtm

2022-11-22 17:32 UTC, merged