add negative unit test to _image_iso
RedHatInsights/edge-api pull request #1672
Opened 2022-11-21 10:24 UTC by mgold1234

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-21 17:02 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +				return errors.New("error storing offset after ISO message")
not sure if we should return here

2022-11-21 17:05 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +				return errors.New("headers received with the event")
not sure we should return here

2022-11-22 10:06 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +				return errors.New("error storing offset after ISO message")
remove it

2022-11-22 11:04 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +				return errors.New("headers received with the event")
@ldjebran can you please look on that

2022-11-23 14:20 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +					return errors.New("failed to unmarshal CRC ISO event")
I already remove it, @ldjebran can you please look ?

2022-11-23 14:43 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> -		os.Exit(1)
This is a microservice, not a function. The os exit was correct, Please revert this.

2022-11-23 14:44 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> +				return errors.New("headers received with the event")
This is a microservice, not a function. Returning breaks the event loop, please do not return

2022-11-23 14:44 UTC, AaronH88 commented on pkg/services/images_iso/main.go
> +					return errors.New("failed to unmarshal CRC ISO event")
The return is still here

2022-11-23 14:57 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +					return errors.New("failed to unmarshal CRC ISO event")
move it

2022-11-23 20:56 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> -		os.Exit(1)
if I revert it, when we will run all tests I will get an error because we exit the application in case of a negative scenario.
@AaronH88 do you have a suggestion how to test negative cases

2022-11-24 15:09 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +		logger.FlushLogger()
let's flush the logger for any case when exiting the app eg:

```go
err := initConsumer(ctx)
logger.FlushLogger()
if err != nil {
    mslog.WithField("error", err).Error("Error when initialize consumer")
    os.Exit(1)
}
```

2022-11-24 15:10 UTC, ldjebran reviewed
LGTM, left one comment

2022-11-24 20:05 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +		logger.FlushLogger()
@ldjebran but I put the exit only in the main, I don't understand how it's possible to have another case existing except that.

2022-11-28 14:26 UTC, tomershinhar approved these changes
LGTM

2022-11-29 20:30 UTC, loadtheaccumulator requested changes

2022-11-29 20:30 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		return errors.New("subscribing to topics faile")
typo /faile/failed/

2022-11-29 20:30 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		mslog.WithField("error", err).Error("Error when initialize consumer")
replace /initialize/initializing/

2022-11-29 20:30 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		logger.FlushLogger()
He's suggesting adding a flush so the exit blocks until the log is written, otherwise we risk losing the log entry.

2022-11-29 20:30 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
>  		mslog.WithField("error", "No kafka configuration found")
This should be... 

mslog.Error("No kafka brokers configuration found")
or
mslog.WithField("error", "No kafka brokers configuration found").Error("Error reading Kafka brokers")

2022-11-29 21:06 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +		logger.FlushLogger()
@loadtheaccumulator thank you

2022-11-29 21:07 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +		return errors.New("subscribing to topics faile")
ty

2022-11-29 21:08 UTC, mgold1234 commented on pkg/services/images_iso/main.go
>  		mslog.WithField("error", "No kafka configuration found")
done

2022-11-30 02:32 UTC, loadtheaccumulator requested changes

2022-11-30 02:32 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		mslog.WithField("error", err).Error("Error when initializing consumer")
This gets logged after the flush and could be dropped. @ldjebran any thoughts on moving the flush on line 127 to the last line of the app and adding an explicit flush here?

2022-11-30 08:57 UTC, ldjebran commented on pkg/services/images_iso/main.go
> +		mslog.WithField("error", err).Error("Error when initializing consumer")
the original idea is to make a flush on any case error or not, so that we can be able to see the latests logs even if the initConsumer does not return error, but I understand your concern that we may  lose the last log then, maybe we should add a second one just after the last log and before os.exist(1), what do you think ?

2022-11-30 14:24 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +		mslog.WithField("error", err).Error("Error when initializing consumer")
@ldjebran this is good idea imoo

2022-11-30 15:23 UTC, mgold1234 commented
/retest

2022-12-01 12:54 UTC, ldjebran commented on pkg/services/images_iso/main.go
> -		os.Exit(1)
This has been fixed , resolving as Aaron in PTO

2022-12-01 13:38 UTC, ldjebran commented on pkg/services/images_iso/main_test.go
> +					Expect(errResult).ToNot(BeNil())
Let's make sure that  the error returned by GetConsumer is the one returned by initConsumer

2022-12-01 13:38 UTC, ldjebran reviewed
overall looks good, left one comment about the test it self.

2022-12-01 19:58 UTC, loadtheaccumulator requested changes

2022-12-01 19:58 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		mslog.WithField("error", err).Error("Error when initializing consumer")
Does this need to be mslog.WithField("error", err.Error()).Error("Error when initializing consumer")

2022-12-02 13:20 UTC, mgold1234 commented on pkg/services/images_iso/main_test.go
> +					Expect(errResult).ToNot(BeNil())
@ldjebran done,thank you

2022-12-02 14:06 UTC, ldjebran commented on pkg/services/images_iso/main_test.go
> +					mockConsumerService.EXPECT().GetConsumer(consumerGroupID).Return(nil, errors.New("failed to get ISO consumer"))
```suggestion
					mockConsumerService.EXPECT().GetConsumer(consumerGroupID).Return(nil, errorMessage)
```

2022-12-02 14:09 UTC, ldjebran commented on pkg/services/images_iso/main_test.go
> +					Expect(errResult).To(Equal(errors.New(errorMessage)))
I see it like this 

```go
expectedError := errors.New("failed to get ISO consumer")
mockConsumerService.EXPECT().GetConsumer(consumerGroupID).Return(nil, expectedError)
errResult := initConsumer(ctx)
Expect(errResult.Error()).To(Equal(expectedError.Error()))

```

2022-12-03 19:22 UTC, mgold1234 commented on pkg/services/images_iso/main_test.go
> +					Expect(errResult).To(Equal(errors.New(errorMessage)))
@ldjebran add it

2022-12-05 09:29 UTC, ldjebran approved these changes
LGTM

2022-12-09 15:34 UTC, ldjebran commented
/retest

2022-12-11 11:02 UTC, tomershinhar requested changes

2022-12-11 11:02 UTC, tomershinhar commented on pkg/services/images_iso/main_test.go
> +	Describe("Should not get Consumer", func() {
lines 143-145 are duplicates, we do not need new `Describe` `when` and `context`
this test can be added to the already existing one

2022-12-12 09:02 UTC, mgold1234 commented on pkg/services/images_iso/main_test.go
> +	Describe("Should not get Consumer", func() {
@tomer, I change it, thank you

2022-12-12 09:24 UTC, tomershinhar approved these changes
LGTM

2022-12-12 11:50 UTC, ldjebran approved these changes
lgtm

2022-12-12 11:51 UTC, ldjebran commented
@loadtheaccumulator please revisit

2022-12-12 15:23 UTC, loadtheaccumulator requested changes

2022-12-12 15:23 UTC, loadtheaccumulator commented on pkg/services/images_iso/main.go
> +		return errors.New("no kafka configuration found")
add brokers on 38 to match 37.

2022-12-12 15:40 UTC, mgold1234 commented on pkg/services/images_iso/main.go
> +		return errors.New("no kafka configuration found")
@loadtheaccumulator added, thank you

2022-12-13 09:33 UTC, ldjebran approved these changes

2022-12-13 09:55 UTC, tomershinhar approved these changes
LGTM

2022-12-13 13:01 UTC, loadtheaccumulator approved these changes

2022-12-13 13:02 UTC, loadtheaccumulator requested changes

2022-12-13 13:02 UTC, loadtheaccumulator commented on pkg/services/images_iso/main_test.go
> +				It("should get error be when there is no Consumer", func() {
one last typo...
/should get error be when there is no Consumer/should get error when there is no Consumer/

2022-12-13 13:04 UTC, mgold1234 commented on pkg/services/images_iso/main_test.go
> +				It("should get error be when there is no Consumer", func() {
@loadtheaccumulator done

2022-12-13 13:31 UTC, tomershinhar approved these changes
LGTM

2022-12-13 14:15 UTC, ldjebran approved these changes
lgtm

2022-12-13 15:33 UTC, loadtheaccumulator approved these changes

2022-12-13 15:55 UTC, mgold1234 commented
/retest

2022-12-14 09:30 UTC, ldjebran commented
@Mergifyio refresh

2022-12-14 09:30 UTC, ldjebran commented
@Mergifyio requeue

2022-12-14 09:49 UTC, merged