change the main of image_build and write unit test for that
RedHatInsights/edge-api pull request #1677
Opened 2022-11-22 13:09 UTC by mgold1234

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-22 16:35 UTC, AaronH88 commented on pkg/services/images_build/main.go
> -			case sig := <-sigchan:
same here, why removed?

2022-11-22 16:44 UTC, loadtheaccumulator requested changes

2022-11-22 16:44 UTC, loadtheaccumulator commented on pkg/services/images_build/main.go
> +	for run {
We should discuss removing the signal channel on L49-50 and the switch that goes with it. It is used to gracefully exit and shutdown when OpenShift terminates a pod.

2022-11-23 10:24 UTC, mgold1234 commented on pkg/services/images_build/main.go
> -		sigchan := make(chan os.Signal, 1)
I thought it should be the same as in image_iso, there we don't have a signal,
can you explain to me what is the difference, please?

2022-11-23 10:25 UTC, mgold1234 commented on pkg/services/images_build/main.go
> -			case sig := <-sigchan:
add it back

2022-11-28 13:45 UTC, mgold1234 commented on pkg/services/images_build/main.go
> +	for run {
I added it back

2022-11-29 15:32 UTC, tomershinhar submitted a review, later dismissed
LGTM

2022-11-29 20:33 UTC, loadtheaccumulator submitted a review, later dismissed

2022-12-05 16:36 UTC, tomershinhar commented
/retest

2022-12-11 11:25 UTC, tomershinhar approved these changes
LGTM

2022-12-22 13:36 UTC, ldjebran commented
remove do not merge as automation is ok now

2022-12-22 13:46 UTC, ldjebran commented
remove do not merge as automation is ok now

2023-01-04 18:13 UTC, loadtheaccumulator approved these changes

2023-01-04 18:15 UTC, loadtheaccumulator requested changes
Does poll return *kafka.Error or kafka.Error?

2023-01-04 19:44 UTC, loadtheaccumulator requested changes

2023-01-04 19:44 UTC, loadtheaccumulator commented on pkg/services/images_build/main.go
> +func main() {
It needs an empty line to separate the functions.

2023-01-04 21:50 UTC, mgold1234 commented
@loadtheaccumulator  poll return *kafka.Error

2023-01-05 17:32 UTC, ldjebran commented on pkg/services/images_build/images_build_suite_test.go
> +	RunSpecs(t, "Clients Suite")
```go
RunSpecs(t, "Images Build Suite")
```

2023-01-05 17:35 UTC, ldjebran commented on pkg/services/images_build/main_test.go
> +						Name:       gomock.Any().String(),
may be this should be the same name as the image set one

2023-01-05 17:43 UTC, ldjebran commented on pkg/services/images_build/main_test.go
> +					mockConsumer.EXPECT().Commit().AnyTimes()
why .AnyTimes() should't be one time, or I am missing something ? 
```go
mockConsumer.EXPECT().Commit().Times(1)
```

2023-01-05 17:43 UTC, ldjebran commented on pkg/services/images_build/main_test.go
> +					mockConsumer.EXPECT().Commit().AnyTimes()
as we have one message

2023-01-05 17:44 UTC, ldjebran commented on pkg/services/images_build/main_test.go
> +					mockConsumer.EXPECT().Poll(timeout).Return(&kafkaError).AnyTimes()
same here about AnyTime(), may be I am missing something ?

2023-01-05 17:53 UTC, ldjebran reviewed
looks good, left some comments.

2023-01-06 16:43 UTC, loadtheaccumulator commented
> @loadtheaccumulator poll return *kafka.Error

@mgold1234 Referencing confluent's .poll test, it appears to return kafka.Error.

https://github.com/confluentinc/confluent-kafka-go/blob/8f59eb87ad41e55c87ca80c40ac984eef7126f42/kafka/consumer_test.go#L491-L526

2023-01-06 20:06 UTC, mgold1234 commented
@loadtheaccumulator when I run it, It's look like it is *kafka.Error.
and it is the same as we have in image_iso/main.go no?
![image](https://user-images.githubusercontent.com/73419853/211090927-51284d76-d34a-421c-ad0f-8285270dd092.png)

2023-01-06 20:11 UTC, mgold1234 commented
@loadtheaccumulator should I change it in image_iso as well?
thank you

2023-01-09 14:59 UTC, loadtheaccumulator commented
> when I run it, It's look like it is *kafka.Error.

@mgold1234 When you run it, I'm assuming it is following the return defined in the mock or the actual method. If the actual method is looking for non-pointer, and because type pointer to type is different than the type itself, the failure will never get caught by the switch in production and only in the unit test. The lines of code I pasted above are from the confluent test for the same library.

2023-01-09 15:09 UTC, ldjebran reviewed
lgtm, except the problem with kafka.Error, I agree with @loadtheaccumulator,
, when you supply &kafka.Error from the mock of course you will will get *kafka.Error, 
you have to return back to kafka code and check the error returned, for me when investigating I found the returned is kafka.Error
The basic one in kaka code 
```go

// NewError creates a new Error.
func NewError(code ErrorCode, str string, fatal bool) (err Error) {
	return Error{code: code, str: str, fatal: fatal}
}
```

2023-01-09 15:29 UTC, mgold1234 commented
@loadtheaccumulator I already change the code to kafka.error can you please look?

2023-01-09 15:59 UTC, ldjebran submitted a review, later dismissed
lgtm

2023-01-09 20:40 UTC, loadtheaccumulator requested changes

2023-01-09 20:40 UTC, loadtheaccumulator commented on pkg/services/images_build/main.go
> +	log.Info("Closing consumer")
Is the consumer explicitly closed somewhere?

2023-01-12 15:21 UTC, loadtheaccumulator commented on pkg/services/images_build/main.go
> +	log.Info("Closing consumer")
@mgold1234 You should be able to cover that with a mockConsumer.EXPECT() line for .Close in the test.

2023-01-13 09:23 UTC, ldjebran commented
/retest

2023-01-13 10:21 UTC, ldjebran approved these changes

2023-01-13 14:19 UTC, loadtheaccumulator approved these changes

2023-01-13 15:39 UTC, merged