apiResponse: FIXES routes update api responses.
RedHatInsights/edge-api pull request #1683
Opened 2022-11-23 12:04 UTC by ldjebran

FIXES routes update api responses, using appropriate functions RespondWithAPIError and respondWithJSONBody.

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-23 14:16 UTC, omaciel requested changes
Would love for existing tests to also check for the type of response: `respondWithAPIError` and `respondWithJSONBody`.

2022-11-23 14:21 UTC, ldjebran commented
@omaciel we did not change the type of response , but used the compact version of it via functions respondWithAPIError and respondWithJSONBody  the code became more readable, and we removed repetitive code .

2022-11-23 14:25 UTC, omaciel commented
> @omaciel we did not change the type of response , but used the compact version of it via functions respondWithAPIError and respondWithJSONBody the code became more readable, and we removed repetitive code .

I understood that bit :) I'm proposing that we also test the response type so that if anyone ever decides or changes it by mistake in the future, our tests will alert us.

2022-11-23 15:19 UTC, omaciel commented
@ldjebran and I discussed over Slack and agreed that what I suggested requires a much more involved code refactoring, so I'll mark this as resolved.

2022-11-23 15:32 UTC, omaciel requested changes
Please consider adding at least one single and comprehensive test for the functions I highlighted. I see these as serious technical debts for us.

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/devices.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
Please consider adding at least one single unittest for this function? We currently have zero coverage:
<img width="1104" alt="Screenshot 2022-11-23 at 10 23 01" src="https://user-images.githubusercontent.com/53362/203583957-f58f55ee-39e9-47a9-a903-231d78594f21.png">

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewNotFound("file was not found on the S3 bucket"))
Please consider adding at least one unittest for this function as we currently have zero coverage:


<img width="1091" alt="Screenshot 2022-11-23 at 10 26 20" src="https://user-images.githubusercontent.com/53362/203584705-2e4df476-b775-4449-9d46-77065669e981.png">

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewInternalServerError())
We currently have zero coverage for this function:

<img width="1495" alt="Screenshot 2022-11-23 at 10 27 52" src="https://user-images.githubusercontent.com/53362/203585024-c82011c8-beb7-4a4f-be21-98c0eed33f97.png">

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/updates.go
> +	ctxServices := dependencies.ServicesFromContext(r.Context())
Zero coverage:

<img width="626" alt="Screenshot 2022-11-23 at 10 29 06" src="https://user-images.githubusercontent.com/53362/203585342-1ebc991f-cfa0-461b-b1b1-ceffb6149615.png">

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
Zero coverage:

<img width="1161" alt="Screenshot 2022-11-23 at 10 30 12" src="https://user-images.githubusercontent.com/53362/203585616-10611f7f-a576-4d2d-a68c-6e05e31172d8.png">

2022-11-23 15:32 UTC, omaciel commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
Zero coverage:

<img width="1461" alt="Screenshot 2022-11-23 at 10 31 26" src="https://user-images.githubusercontent.com/53362/203585873-a9abe11c-d502-443e-b5d4-29c17b46db63.png">

2022-11-26 11:02 UTC, ldjebran commented on pkg/routes/devices.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
![image](https://user-images.githubusercontent.com/131553/204085472-9342e2ae-dbc8-49b5-993c-b434d10b11f1.png)

2022-11-26 11:03 UTC, ldjebran commented on pkg/routes/devices.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
done

2022-11-26 11:05 UTC, ldjebran commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewNotFound("file was not found on the S3 bucket"))
![image](https://user-images.githubusercontent.com/131553/204085498-7ea566da-d770-44bd-be98-fbd2f1e16362.png)
The io.Copy error needs too much code refactoring, will do it in a separate PR asn io copy needs to be transfred via  context ir try to use file service

2022-11-26 11:05 UTC, ldjebran commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewNotFound("file was not found on the S3 bucket"))
done

2022-11-26 11:07 UTC, ldjebran commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewInternalServerError())
![image](https://user-images.githubusercontent.com/131553/204085568-aca74b8d-c7f0-4914-bac1-5906fa3abe1f.png)
the db error need to be investigated as we need to mock db will work with @AaronH88 to find a solution for this.

2022-11-26 11:07 UTC, ldjebran commented on pkg/routes/updates.go
> +		respondWithAPIError(w, services.Log, errors.NewInternalServerError())
done

2022-11-26 11:07 UTC, ldjebran commented on pkg/routes/updates.go
> +	ctxServices := dependencies.ServicesFromContext(r.Context())
![image](https://user-images.githubusercontent.com/131553/204085623-8d2042af-8551-48b4-8f30-f42d7552f163.png)

2022-11-26 11:07 UTC, ldjebran commented on pkg/routes/updates.go
> +	ctxServices := dependencies.ServicesFromContext(r.Context())
done

2022-11-26 11:08 UTC, ldjebran commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
![image](https://user-images.githubusercontent.com/131553/204085640-714953e8-a60b-4fb8-9ab0-fd9dec8e43f6.png)

2022-11-26 11:08 UTC, ldjebran commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
done

2022-11-26 11:08 UTC, ldjebran commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
![image](https://user-images.githubusercontent.com/131553/204085672-88c06db4-fa9c-464c-a384-06827a15d9d4.png)

2022-11-26 11:08 UTC, ldjebran commented on pkg/routes/updates.go
> +		ctxServices := dependencies.ServicesFromContext(r.Context())
done

2022-11-26 11:11 UTC, ldjebran commented
@omaciel please revisit 
increased coverage:
 for devices from 41.1% upto  50.3
 for updates from 43.9 upto 78%

2022-11-26 16:34 UTC, omaciel approved these changes
/lgtm

2022-11-26 16:37 UTC, omaciel commented
From https://app.codecov.io/gh/RedHatInsights/edge-api/pull/1683:

<img width="998" alt="Screenshot 2022-11-26 at 11 35 44" src="https://user-images.githubusercontent.com/53362/204099229-6c77a0ab-d989-473d-94ff-644a17230e9b.png">

2022-11-26 17:17 UTC, ldjebran commented
strange that the numbers are different from the local dev one 
![image](https://user-images.githubusercontent.com/131553/204100941-3be89382-b225-4516-85e5-ec99d07beedc.png)

![image](https://user-images.githubusercontent.com/131553/204100959-218bd246-fb3b-4a6c-a985-98601728434c.png)

2022-11-28 12:54 UTC, mgold1234 approved these changes
/lgtm

2022-11-28 12:55 UTC, merged