add more unit test to check the getDeviceforImage function
RedHatInsights/edge-api pull request #1688
Opened 2022-11-24 13:24 UTC by mgold1234

Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-11-24 14:41 UTC, tomershinhar commented on pkg/services/images_test.go
>  				It("should return device count of image1", func() {
the name suggests that you would call image1 but image2 is used instead

2022-11-24 14:41 UTC, tomershinhar commented on pkg/services/images_test.go
>  				It("should return 0 device of image2", func() {
image2 is the one running on the devices, and the test itself correctly calls image1
the name needs to be updated too

2022-11-24 14:41 UTC, tomershinhar commented on pkg/services/images_test.go
> +				It("should return 0 device of image2", func() {
this name of the test is not matching what it is actually doing

2022-11-24 14:41 UTC, tomershinhar commented on pkg/routes/images.go
> +			imgDetail.Image.TotalDevicesWithImage = upd[len(upd)-1].Image.TotalDevicesWithImage
we might want to add validation for those added attributes in the route test too, just to make sure they are returned correctly

2022-11-24 18:58 UTC, mgold1234 commented on pkg/services/images_test.go
>  				It("should return device count of image1", func() {
good catch!!

2022-11-24 18:58 UTC, mgold1234 commented on pkg/services/images_test.go
>  				It("should return 0 device of image2", func() {
thank you for that

2022-11-24 18:58 UTC, mgold1234 commented on pkg/services/images_test.go
> +				It("should return 0 device of image2", func() {
thank you

2022-11-24 18:59 UTC, mgold1234 commented on pkg/routes/images.go
> +			imgDetail.Image.TotalDevicesWithImage = upd[len(upd)-1].Image.TotalDevicesWithImage
I will try

2022-11-28 11:24 UTC, tomershinhar submitted a review, later dismissed
LGTM

2022-11-28 12:51 UTC, lahavyuv86 commented on pkg/services/images_test.go
>  				device = []models.Device{
@mgold1234 ^^

2022-11-28 13:11 UTC, mgold1234 commented on pkg/services/images_test.go
>  				device = []models.Device{
good idea

2022-11-28 13:48 UTC, mgold1234 commented
/retest

2022-11-28 13:53 UTC, omaciel requested changes
Please a single unittest to cover `func GetImageDetailsByID`

2022-11-28 13:53 UTC, omaciel commented on pkg/routes/images.go
> +			imgDetail.Image.TotalPackages = upd[len(upd)-1].Image.TotalPackages
Zero coverage:

![Screenshot 2022-11-28 at 08 50 54](https://user-images.githubusercontent.com/53362/204294278-61556d93-e9f4-4015-bbb2-dc397e9dea3c.png)

2022-11-29 12:47 UTC, tomershinhar approved these changes
LGTM

2022-11-29 15:03 UTC, mgold1234 commented on pkg/routes/images.go
> +			imgDetail.Image.TotalPackages = upd[len(upd)-1].Image.TotalPackages
@omaciel I added more unit test, can you please look?

2022-11-29 15:30 UTC, omaciel approved these changes
/lgtm

2022-11-29 15:45 UTC, merged