Adding route for liveness and readiness probes.
RedHatInsights/edge-api pull request #1705
Opened 2022-12-01 18:55 UTC by omaciel

# Description

This is required for AppSRE.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-12-01 19:30 UTC, acosferreira submitted a review, later dismissed
lgtm

2022-12-01 20:08 UTC, omaciel commented
/retest

2022-12-01 20:23 UTC, loadtheaccumulator submitted a review, later dismissed

2022-12-02 09:20 UTC, psav requested changes

2022-12-02 09:20 UTC, psav commented on deploy/clowdapp.yaml
> +            port: 8080
I'd set the port to `web`, 8080 is not right for clowder, and `web` will use whatever clowder picked

2022-12-02 13:55 UTC, ldjebran approved these changes
/LGTM

2022-12-02 14:10 UTC, ldjebran commented
/retest

2022-12-02 15:32 UTC, ldjebran submitted a review, later dismissed

2022-12-05 09:27 UTC, ldjebran commented
/retest

2022-12-05 14:28 UTC, omaciel commented
/retest

2022-12-05 20:10 UTC, closed without merging