update: implement UpdateRepoRequested event.
RedHatInsights/edge-api pull request #1721
Opened 2022-12-08 11:36 UTC by ldjebran

FIXES: THEEDGE-2754

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-12-08 11:40 UTC, ldjebran commented
increased coverage to 75.6 of services/updates.go
![image](https://user-images.githubusercontent.com/131553/206437333-f7159420-54a0-4bc4-a929-0e9ab08643bf.png)

update_repo_requested consume coverage 91.9
![image](https://user-images.githubusercontent.com/131553/206437627-06cdee17-5f29-4310-85bb-ade09b715a8c.png)

2022-12-08 17:22 UTC, loadtheaccumulator requested changes
Just some minor things and question.

2022-12-08 17:22 UTC, loadtheaccumulator commented on pkg/services/update/event_update_repo_requested.go
> +	if ev.RedHatOrgID == "" || ev.Data.RequestID == "" {
Can these validation checks be moved to one or more functions?

2022-12-08 17:22 UTC, loadtheaccumulator commented on pkg/services/updates.go
> +	// bellow code wil be refactored in its own function when WriteTemplateRequested event will be implemented
typo /bellow code wil/below code will/

2022-12-08 17:22 UTC, loadtheaccumulator commented on unleash/features/feature.go
> +var UpdateRepoRequested = &Flag{Name: "edge-management.update_repo_requested", EnvVar: "UPDATE_REPO_REQUESTED"}
Prefixing UPDATE_REPO_REQUESTED with FEATURE_ (FEATURE_UPDATE_REPO_REQUESTED) will help avoid conflicts and search for env vars related to feature flags.

2022-12-08 17:22 UTC, loadtheaccumulator commented on pkg/services/updates.go
> +func (s *UpdateService) ProduceEvent(requestedTopic, recordKey string, event models.CRCCloudEvent) error {
Why does this need to be a new method in the UpdateService versus just calling the ProducerService directly?

2022-12-09 13:35 UTC, ldjebran commented on pkg/services/update/event_update_repo_requested.go
> +	if ev.RedHatOrgID == "" || ev.Data.RequestID == "" {
Thanks Jhonathan, created a Validate function

2022-12-09 13:35 UTC, ldjebran commented on pkg/services/update/event_update_repo_requested.go
> +	if ev.RedHatOrgID == "" || ev.Data.RequestID == "" {
it's more compact now

2022-12-09 13:35 UTC, ldjebran commented on pkg/services/updates.go
> +	// bellow code wil be refactored in its own function when WriteTemplateRequested event will be implemented
done

2022-12-09 13:35 UTC, ldjebran commented on unleash/features/feature.go
> +var UpdateRepoRequested = &Flag{Name: "edge-management.update_repo_requested", EnvVar: "UPDATE_REPO_REQUESTED"}
done

2022-12-09 13:37 UTC, ldjebran commented on pkg/services/updates.go
> +func (s *UpdateService) ProduceEvent(requestedTopic, recordKey string, event models.CRCCloudEvent) error {
Thanks to notice this, I implemented this , in an earlier stage , because I had a circular import problem, but as the implementation became cleaner, returned back to the initial implementation.

2022-12-09 13:37 UTC, ldjebran commented on pkg/services/updates.go
> +func (s *UpdateService) ProduceEvent(requestedTopic, recordKey string, event models.CRCCloudEvent) error {
done

2022-12-09 13:38 UTC, ldjebran commented
@loadtheaccumulator all comments addressed , please revisit.

2022-12-09 14:58 UTC, loadtheaccumulator approved these changes

2022-12-09 15:38 UTC, elyezer approved these changes

2022-12-09 15:53 UTC, merged