remove min replicas to ibievents and isobuild
RedHatInsights/edge-api pull request #1760
Opened 2022-12-19 18:58 UTC by acosferreira

# Description

remove readiness for ibievents and isobuilds

Fixes # ( THEEDGE-2216  THEEDGE-2217)

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-12-22 13:35 UTC, ldjebran commented
remove do not merge as automation is ok now

2022-12-22 18:54 UTC, de1987 approved these changes
LGTM

2022-12-23 18:31 UTC, loadtheaccumulator requested changes

2022-12-23 18:31 UTC, loadtheaccumulator commented on deploy/clowdapp.yaml
> +      minReplicas: 0
This has to be 1. ibvents is production and responsible for resuming interrupted builds and marking stale builds as ERROR.

2022-12-28 20:59 UTC, omaciel commented
/rebase

2023-01-03 21:04 UTC, loadtheaccumulator approved these changes

2023-01-03 21:32 UTC, omaciel commented
This PR is still labeled as DRAFT. BTW the description says ibevents and isobuilds will be updated but only one has been updated

2023-01-03 22:45 UTC, merged