move external url controller to commit object
RedHatInsights/edge-api pull request #1761
Opened 2022-12-19 20:32 UTC by acosferreira

# Description

move the external url controller to commit object to avoid errors on resume images

Fixes # ([THEEDGE-2917](https://issues.redhat.com/browse/THEEDGE-2917))

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2022-12-20 12:31 UTC, ldjebran commented on pkg/services/repobuilder.go
> +	c.ExternalURL = true
we should set this value as true the first time when we get the url from image builder eg in the client after line 
https://github.com/RedHatInsights/edge-api/blob/main/pkg/clients/imagebuilder/client.go#L392 

```go
                image.Commit.Status = models.ImageStatusSuccess
		image.Commit.ImageBuildTarURL = cs.ImageStatus.UploadStatus.Options.URL
		image.Commit.ExternalURL = true
```

2022-12-20 12:36 UTC, ldjebran commented on pkg/services/repobuilder.go
> +	update.Commit.ExternalURL = false
we should set this value to false at the place where we set the internal url  eg after line 
https://github.com/RedHatInsights/edge-api/blob/main/pkg/services/repobuilder.go#L320

```go
        c.ImageBuildTarURL = repoTarURL   // line 320
        c.ExternalURL = false
	result := db.DB.Save(c)
```

2022-12-20 18:41 UTC, ldjebran approved these changes
/lgtm

2022-12-20 18:53 UTC, omaciel requested changes
We don't have any tests to check your changes? I think we need one for the conditional statement I mentioned in `/pkg/clients/imagebuilder/client.go`.

2022-12-20 18:53 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +		image.Commit.ExternalURL = false
This line is repeated twice inside this conditional statement. Is this intentional?

2022-12-20 19:20 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +		image.Commit.ExternalURL = false
yeah, we check the status of commit while is building I want to keep as false, if an error occurs is also false.
 maybe i can move it for outside of validation and keep in one line ;)

2022-12-20 20:30 UTC, omaciel submitted a review, later dismissed
/lgtm

2022-12-20 20:53 UTC, thom-at-redhat submitted a review, later dismissed

2022-12-21 08:52 UTC, mgold1234 commented
/retest

2022-12-21 18:11 UTC, de1987 commented on pkg/services/repobuilder_test.go
> +				// mockDownloaderService.EXPECT().DownloadToPath(commit.ImageBuildTarURL, "repo.tar").Return(nil)
Could you remove those?

2022-12-22 13:07 UTC, de1987 commented on pkg/services/repobuilder.go
> +		if err := downloader.DownloadToPath(c.ImageBuildTarURL, tarFileName); err != nil {
@ldjebran we replaced the `FilesService` init with the one that exists inside of `RepoBuilderService`
Is there any concern about it?

2022-12-22 13:14 UTC, ldjebran commented on pkg/services/repobuilder.go
> +		if err := downloader.DownloadToPath(c.ImageBuildTarURL, tarFileName); err != nil {
@de1987 I found this implementation more logical , as Ana want to create a mock for testing, there is no functionality changes here , so it lgtm

2022-12-22 13:19 UTC, ldjebran commented on pkg/services/repobuilder_test.go
> +				fileDest := "/tmp/download/"
may be this should go to setup section lines After subscribe

2022-12-22 13:19 UTC, ldjebran commented on pkg/services/repobuilder_test.go
> +				os.RemoveAll(fileDest)
may be this should go the AfterEach section

2022-12-22 13:34 UTC, ldjebran commented
remove do not merge as automation is ok now

2022-12-22 17:00 UTC, ldjebran submitted a review, later dismissed
/lgtm

2022-12-22 17:02 UTC, de1987 submitted a review, later dismissed

2022-12-22 17:36 UTC, acosferreira commented
/retest

2022-12-22 18:36 UTC, de1987 approved these changes

2022-12-22 18:38 UTC, thom-at-redhat approved these changes

2022-12-22 18:39 UTC, merged