added endpoint /images/reserved-usernames
RedHatInsights/edge-api pull request #177
Opened 2021-08-06 18:38 UTC by resoluteCoder

Add functionality to get reserved usernames on system -> returns an array

2021-08-06 18:44 UTC, biancarosa requested changes

2021-08-06 18:44 UTC, biancarosa commented on pkg/images/images.go
> +	c1, _ := exec.Command("sed", "1d;/^#/d;s/\t.*//", "/usr/share/doc/setup/uidgid").Output()
I'm just missing an error check here to return an internal server error if this command fails 😬

2021-08-06 18:45 UTC, resoluteCoder commented on pkg/images/images.go
> +	c1, _ := exec.Command("sed", "1d;/^#/d;s/\t.*//", "/usr/share/doc/setup/uidgid").Output()
Error handling, wooooooops. I'll get on it :smile:

2021-08-06 20:29 UTC, maxamillion commented
LGTM :+1:

2021-08-09 12:39 UTC, biancarosa approved these changes
LGTM!

2021-08-09 16:59 UTC, merged