blocking out some ideas for repo hosting
RedHatInsights/edge-api pull request #18
Opened 2021-05-27 14:02 UTC by jhjaggars

2021-05-27 14:34 UTC, omaciel requested changes
I think you need to rebase but otherwise, let 'er rip :)

2021-05-27 14:34 UTC, omaciel commented on pkg/commits/commits.go
> +// This provides type safety in the context object for our "commit" key.  We
Looks like you may have to rebase? This was part of your previous PR

2021-05-27 14:34 UTC, omaciel commented on pkg/repo/repo.go
> +		cr.Name = "default" // should be randomized?
As part of the common module, someone could implement something like https://golangdocs.com/generate-random-string-in-golang:

```go
import (
    "fmt"
    "math/rand"
)
 
func RandomString(n int) string {
    var letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
 
    s := make([]rune, n)
    for i := range s {
        s[i] = letters[rand.Intn(len(letters))]
    }
    return string(s)
}
 
func main() {
    fmt.Println(RandomString(10))        // BpLnfgDsc2
}
```

2021-06-03 17:36 UTC, merged

2021-06-03 17:37 UTC, maxamillion commented
I'm merging because I'm going to base the next thing I do on the work in this PR and Jesse is going to be afk for a bit