Fix Inconsistent count returned from /image-sets, and image-sets/view
RedHatInsights/edge-api pull request #1857
Opened 2023-02-01 18:21 UTC by Saurabh-Thakre

# Description
Fixing  Inconsistent count returned from /image-sets and /image-sets/view

The GET /image-sets and GET /image-sets/view APIs return different count values. For example:
```
$ $EDGE/image-sets?status=error | jq '.Count'
6629

$ $EDGE/image-sets/view?status=error | jq '.count'
5857
```
FIXES: 

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-02-02 08:39 UTC, ldjebran commented on pkg/routes/imagesets.go
> +		Count(&count)
This count has to be the same as for the records count in query at line https://github.com/RedHatInsights/edge-api/pull/1857/files#diff-7d067fdfe152f3f147f9e7772b4eab0b02785685caf2348b0beef7fd46be1e25R222

so you have to fund a solution that satisfy the two.

2023-02-09 12:36 UTC, de1987 requested changes

2023-02-09 12:36 UTC, de1987 commented on pkg/routes/imagesets.go
> +		Find(&imageSet)
is there a test covering these changes?

2023-02-09 14:37 UTC, ldjebran commented on pkg/routes/imagesets.go
> +		Find(&imageSet)
@Saurabh-Thakre you should write a unittest that should demonstrate that your fix is working (of course it will fail without your changes) 

The test for example can have this scenario

Create 3 ImageSets 
1 imageSet has one image with Error status
2 imageset has one image without success status
3 imageset has 2 images  the latest one has success status , the first one has error status

filter by status=error => result should be only one imageset `the first one`

This scenario will fail for the current implementation , and should pass with your fix.


you can create a second test that filter by status=success that should return 2 image-sets (number 2 and number 3).

2023-02-09 15:36 UTC, Saurabh-Thakre commented on pkg/routes/imagesets.go
> +		Find(&imageSet)
gotcha, I wrote it but then I saw we already have some tests around filter by status so I removed. I will put it back

2023-02-09 18:35 UTC, ldjebran commented
/retest

2023-02-15 10:39 UTC, Saurabh-Thakre commented
/retest

2023-02-15 12:12 UTC, ldjebran commented
/retest

2023-02-16 10:18 UTC, adeliaferreira commented
/lgtm

2023-02-16 11:15 UTC, Saurabh-Thakre commented
/retest

2023-02-16 14:18 UTC, ldjebran commented on pkg/routes/imagesets_test.go
> +				Expect(string(respBody)).To(ContainSubstring("image-set-1"))
I think we need to unmarshal this respBody and analyse how much image-sets we received and go through all image-sets returned to find image-set-1 and image-set-2 , in error messages we can do this , but here I think we need to be more explicit, as we are building a functionality contract .

2023-02-16 14:19 UTC, ldjebran reviewed
loog good, left one comment about the unittest.

2023-02-16 14:26 UTC, ldjebran commented on pkg/routes/imagesets_test.go
> +				Expect(string(respBody)).To(ContainSubstring("image-set-1"))
hint:
 you can create the image names having all the same prefix , so that you can find them
```go
prefix := faker.UUIDHyphenated() 
image1 := models.Image{
    ...
    Name: prefix + "image-set-1" 
    ...
}

// and then filter by name and status 
req, err := http.NewRequest("GET", fmt.Sprintf("/image-sets?"?name=?&status=?",prefix, status), nil)
// this should return all imagesets that name contain prefix value and the status 
```

2023-02-22 09:15 UTC, ldjebran commented on pkg/routes/imagesets_test.go
> +				Name:  "imageSet-1",
think a more random prefix must be used here (as if any one will use this name in tests , this test will fail):
```go
var namePrefix string 

BeforeEach(func() {
     namePrefix := faker.UUIDHyphenated()
     imageSet1 := &models.ImageSet{
				Name:  namePrefix + "imageSet-1",
				....
// in request filter by prefix
req, err := http.NewRequest("GET", fmt.Sprintf("/image-sets?status=%s&name=namePrefixt", status), nil)

```

2023-02-22 09:17 UTC, ldjebran commented on pkg/routes/imagesets_test.go
> +			imageSet3 := &models.ImageSet{
maybe these data should be removed ?

2023-02-28 08:08 UTC, adeliaferreira approved these changes
LGTM

2023-02-28 08:36 UTC, mgold1234 commented
/retest

2023-02-28 08:47 UTC, merged