kafka: Fixes SecurityProtocol to update package update-app-common-go to latest 1.6.5.
RedHatInsights/edge-api pull request #1870
Opened 2023-02-07 12:04 UTC by ldjebran

# Description
update-app-common-go  have deprecated SecurityProtocol on sasl struct and add it to broker struct. https://github.com/RedHatInsights/app-common-go/commit/195d14d0d2eb6ca7490f087517ae04092f54fe7c

This is related to this PR failure https://github.com/RedHatInsights/edge-api/pull/1864

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor
- [X] Dependency Update

2023-02-07 12:45 UTC, ldjebran commented
/retest

2023-02-07 13:41 UTC, ldjebran commented
/retest

2023-02-07 14:42 UTC, ldjebran commented
/retest

2023-02-07 14:50 UTC, omaciel submitted a review, later dismissed
/lgtm

2023-02-07 16:31 UTC, ldjebran commented
/retest

2023-02-07 17:07 UTC, ldjebran commented
/retest

2023-02-07 17:40 UTC, ldjebran commented
/retest

2023-02-07 18:00 UTC, ldjebran commented
/retest

2023-02-08 06:51 UTC, ldjebran commented
/retest

2023-02-08 08:25 UTC, ldjebran commented
/retest

2023-02-08 08:42 UTC, ldjebran commented
@Mergifyio rebase

2023-02-08 11:09 UTC, AaronH88 approved these changes
lgtm

2023-02-08 11:43 UTC, omaciel requested changes
Can we add tests? Seems like such an important area for us

2023-02-08 11:43 UTC, omaciel commented on pkg/common/kafka/kafkaconfigmap.go
> +		if cfg.KafkaBrokers[0].SecurityProtocol != nil {
I'd feel much confident if we had tests to go along with these conditional statements (the logic is fairly complicated as currently written with multiple checks in one line)

2023-02-08 13:06 UTC, ldjebran commented on pkg/common/kafka/kafkaconfigmap.go
> +		if cfg.KafkaBrokers[0].SecurityProtocol != nil {
add unit-tests

2023-02-08 13:37 UTC, AaronH88 approved these changes
lgtm

2023-02-08 14:06 UTC, omaciel approved these changes
/lgtm

2023-02-08 14:26 UTC, AaronH88 approved these changes
/lgtm

2023-02-08 14:26 UTC, merged