add unit test to repo.
RedHatInsights/edge-api pull request #1877
Opened 2023-02-09 11:30 UTC by mgold1234

repo has 11% of covarage, so this pr will increase the covarage
Signed-off-by: mgold1234 <mgold@redhat.com>

# Description

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-02-09 12:12 UTC, ldjebran commented on pkg/services/repo_test.go
> +				image := &models.Image{
why we need image to retieve a repo ?

2023-02-09 18:24 UTC, ldjebran commented
/retest

2023-02-09 18:30 UTC, ldjebran commented on pkg/services/repo_test.go
> +				id, _ := faker.RandomInt(1)
as understand this, pick a random number , and that id may exist in database.
for testing and for happy , we should be sure that  the record exists.
Imagine the database is empty, so this test should fail,  so it can an repo id that have status  Error

2023-02-09 18:31 UTC, ldjebran requested changes
1. Need to create a real repo. 
2. Check the error first before any other check.

2023-02-13 08:32 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(err).To(BeNil())
the error assert must just after the the function call
```go
repo, err := repoService.GetRepoByID(&testRepo.ID)
Expect(err).To(BeNil())
```

2023-02-13 08:33 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(err).ToNot(BeNil())
the error assert must just after the the function call
```go
repo, err := repoService.GetRepoByID(id1)
Expect(err).To(BeNil())
```

2023-02-13 08:36 UTC, ldjebran commented on pkg/services/repo_test.go
> +			It("repo id doesnt create", func() {
what is the test is testing, when passing a nil id?

2023-02-13 09:37 UTC, mgold1234 commented on pkg/services/repo_test.go
> +			It("repo id doesnt create", func() {
repo id doesnt create and verify that repo id doesnt exist in case of sending empty id, WDYT?

2023-02-14 09:01 UTC, ldjebran commented on pkg/services/repo_test.go
> +			It("repo id doesnt create", func() {
I think that , this a case of two negative unitests, one with id nil , and one with id not nil but does not exist, as they return different errors. 

I think also that function GetRepoByID should validate id to be not nil before passing it to gorm select function.
eg:

```go

// GetRepoByID receives RepoID uint and get a *models.Repo back
func (s *RepoService) GetRepoByID(repoID *uint) (*models.Repo, error) {
	if repoID == nil {
		return nil, new(ImageRepositoryIsUndefined)
	}
	s.log.Debug("Retrieving repo by ID")
        ...
}
```

2023-02-15 09:24 UTC, ldjebran commented on pkg/services/repo_test.go
> +			It("repo id doesnt create", func() {
what dou think ?

2023-02-15 17:11 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(err.Error()).To(Equal("unsupported data"))
```suggestion
				Expect(result.Error).To(HaveOccurred())
				Expect(err.Error()).To(Equal("unsupported data"))
```

2023-02-15 17:12 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(err.Error()).To(Equal("record not found"))
```suggestion
				Expect(err).To(HaveOccurred())
				Expect(err.Error()).To(Equal("record not found"))
```

2023-02-17 09:59 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(repo).To(BeNil())
remove this line

2023-02-17 09:59 UTC, ldjebran commented on pkg/services/repo_test.go
> +				Expect(repo).To(BeNil())
remove this line

2023-02-17 10:01 UTC, ldjebran commented
/retest

2023-02-17 10:53 UTC, ldjebran commented
/retest

2023-02-17 20:06 UTC, mgold1234 commented
@djebran for some reason the test with non existed id always fail when I run it in githlab, because somehow this id is found in the db.
so I remove this test, or maybe you have any idea for an id that does not exist?

2023-02-21 11:46 UTC, ldjebran requested changes
add Expect(err).To(HaveOccurred())
as per comments

2023-02-21 12:21 UTC, mgold1234 commented on pkg/services/repo_test.go
> +			It("repo id doesnt create", func() {
do you think its ok to change the existing code now? or its ok to refactor some places?

2023-02-21 15:09 UTC, ldjebran approved these changes
lgtm

2023-02-21 20:17 UTC, acosferreira approved these changes
lgtm

2023-02-21 20:28 UTC, merged