Test scan
RedHatInsights/edge-api pull request #1885
Opened 2023-02-14 01:34 UTC by acosferreira

# Description
Add feature flag to validate package creation and avoid installedPackage growht.
Add omit to avoid dup 
Create commit_installed_package to be able to reuse installed_package_id from previous package created
Added test scenario
The goal is reduce the exponential data creation, we should do one more refactor to fix m2m relationship and clean up the 26gb of data

FIXES: THEEDGE-2648/2469

## Type of change

What is it?

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-02-14 09:45 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> -// MetaCount contains Count of a SearchPackageResult
why we need to move this structs from this module , their declaration in this module is very natural
as they are created in this module, and their existence is related to this module  ?

2023-02-14 17:42 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	db.DB.Table("Installed_Packages").Select("ID, name,release, arch, version, epoch").
missing error handling

2023-02-14 17:51 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +			pkg := validatePackages(metadata.InstalledPackages[n])
this may be very inefficient, as if we have 1000 packages , we will do 1000 sql queries. 
I think about a function that we pass all the packages and return a map[int64]*models.InstalledPackage
where the key is the index in metadata.InstalledPackages

what do you think ?

2023-02-14 19:43 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +			pkg := validatePackages(metadata.InstalledPackages[n])
yeah, i left a comment on validatePackage function about it
I'll see if I can make it using in condition like (name, release) in ('a', 'b')

2023-02-15 08:30 UTC, mgold1234 commented
/retest

2023-02-15 12:13 UTC, ldjebran commented
/retest

2023-02-15 12:16 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +			pkg := validatePackages(metadata.InstalledPackages[n])
I think we go with something like this: 

```go
func GetInstalledPackagesMap(installedPackages []models.InstalledPackage) (map[int64]models.InstalledPackage, error) {
	installedPackagesMap := make(map[int64]models.InstalledPackage, len(installedPackages))
	if len(installedPackages) == 0 {
		return installedPackagesMap, nil
	}
	// build md5 slice
	packagesMD5 := make([]string, 0, len(installedPackages))
	for _, installPackage := range installedPackages {
		packagesMD5 = append(packagesMD5, installPackage.Sigmd5)
	}
	// prepare 
	var md5Packages models.InstalledPackage
	if err := db.DB.Where("sigmd5", packagesMD5).Find(&md5Packages).Error; err != nil {
		return installedPackagesMap, err
	}

	... 
	
	return installedPackagesMap, nil
}

```

we may need two maps to resolve this

2023-02-15 13:39 UTC, omaciel requested changes
Left you some comments and suggestions

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +	fmt.Printf("\n body %v", respBody)
Do you want this printed or logged?

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +				db.DB.Debug().Omit("Image.InstalledPackages.*").Save(image.Commit)
Do we need `Debug()` here? It'll probably speed things up without it.

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +		if len(cip) > 0 {
Since you checked `len(dupPackages) > 0` above, is it necessary to check that `len(cip) > 0`?

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +	err := db.DB.Debug().Table("Installed_Packages").Select("ID, name,release, arch, version, epoch").
Remove `Debug()`?

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client_test.go
> +	// "github.com/redhatinsights/edge-api/pkg/clients/imagebuilder/mock_imagebuilder"
Remove comment?

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client_test.go
> +				db.DB.Model(models.CommitInstalledPackages{}).Where("Commit_Id=?", img.Commit.ID).Debug().Count(&s)
Debug?

2023-02-15 13:39 UTC, omaciel commented on pkg/models/commits.go
> +	InstalledPackages    []InstalledPackage `faker:"-" json:"InstalledPackages,omitempty" gorm:"many2many:commit_installed_packages;"`
What does `faker:"-"` do here?

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +func (c *Client) ValidatePackages(pkgs []string) (map[uint]*models.InstalledPackage, error) {
Needs unittest

2023-02-15 13:39 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
>  	if err != nil {
Now that you have mocked `http.Client.Do`, how about adding a test where `Do` returns an error?

2023-02-15 17:13 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +			pkg := validatePackages(metadata.InstalledPackages[n])
explaint in a call ;)

2023-02-16 11:17 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +				db.DB.Omit("Image.InstalledPackages.*").Save(image.Commit)
if we are saving image.commit n times ?

2023-02-16 11:20 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +				db.DB.Omit("Image.InstalledPackages.*").Save(image.Commit)
may be this should be like this:
```go
if feature.DedupPackage.IsEnabled()  && concatPkg[metadata.InstalledPackages[n].Name] != "" {
    continue
} else {
   ....
}
```

2023-02-16 11:35 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +	concatPkg := make(map[string]string)
we are using concatPkg as to check if package already in dataBase 
maybe  it should be 
```go
packagesAlreadyExistsMap :=   make(map[string]bool)
```
when setting 
```go
oncatPkg[pkg[key].Name] = true
```

and when checking 

```go
if packagesAlreadyExistsMap[metadata.InstalledPackages[n].Name] == true {
...

```
this is more readable , what do you think?

2023-02-16 11:40 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +		Find(&result)
maybe like this will more naturel 
```go
Find(&result).Error
if err != nil {
....

```

2023-02-16 13:50 UTC, omaciel requested changes

2023-02-16 23:35 UTC, acosferreira commented on pkg/clients/imagebuilder/client_test.go
> +		It("should return nil ", func() {
Added scenario

2023-02-17 13:45 UTC, omaciel requested changes
We can talk about it and go over together if you think it might make it easier?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +				packagesExistsMap[pkg[key].Name] = true
It looks to me that `packagesExistsMap` will always and only filled with `true` value, so why not consider the value returned from `c.ValidatePackages(metadataPackages)` as the source of truth?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +			if packagesExistsMap[metadata.InstalledPackages[n].Name] {
Instead of checking if the package exists, perhaps you could check the opposite?

```go
if found, ok := packagesExistsMap[metadata.InstalledPackages[n].Name]; !ok {
    pkg := models.InstalledPackage{...}
}
```

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +		if len(result) > 0 {
Is `result` always an iterable? If so, then it should be safe not to check its length and `for n:= range results` should either go through all items or just skip if results is empty (unless it's `nil`?)

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client_test.go
> +			db.DB.Exec("ALTER TABLE installed_packages DROP COLUMN name")
Won't this cause major headache if run in parallel or if the order ever changes or if another test needs to save to that table?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +	if feature.DedupPackage.IsEnabled() {
Unittest covers this branch?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +		if len(pkg) > 0 && err == nil {
Unittest covers this branch?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +			} else {
Unittest covers this branch?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +		} else {
Unittest covers this branch?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
> +	if feature.DedupPackage.IsEnabled() &&
Unittest covers this branch?

2023-02-17 13:45 UTC, omaciel commented on pkg/clients/imagebuilder/client.go
>  	if err != nil {
Unittest covers this branch?

2023-02-17 18:19 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +				packagesExistsMap[pkg[key].Name] = true
we need this map to check later if the name is already saved, because  the map returned with ValidatePackages have ID as keys, so we need to build a map of just the existing packages.
but Yes @omaciel ValidatePackages can return a map of packagename as keys and we will not need packagesExistsMap at all (and also dupPackages).

2023-02-17 21:10 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +	if feature.DedupPackage.IsEnabled() {
yes we have 5 diff scenarios created covering those pices

2023-02-17 21:10 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +		} else {
yes we have 5 diff scenarios created covering those pices

2023-02-17 21:10 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +	if feature.DedupPackage.IsEnabled() &&
yes we have 5 diff scenarios created covering those pices

2023-02-17 21:11 UTC, acosferreira commented on pkg/clients/imagebuilder/client_test.go
> +			db.DB.Exec("ALTER TABLE installed_packages DROP COLUMN name")
added the after each to make sure we are in same context

2023-02-20 13:18 UTC, adeliaferreira approved these changes
/lgtm

2023-03-01 21:22 UTC, loadtheaccumulator requested changes
Just some questions and minor changes

2023-03-01 21:22 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +	var packagesExistsMap map[string]*models.InstalledPackage
Should these lines be inside the feature flag?

2023-03-01 21:22 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +			fmt.Printf("\n passei aqui: %v\n", n)
Remove debug print statement.

2023-03-01 21:22 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +	db.DB.Omit("Image.InstalledPackages.*").Save(image.Commit)
Is there functionality that needs to exist outside of the feature flag? If yes, should there be two separate PRs?

2023-03-01 21:27 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +	db.DB.Omit("Image.InstalledPackages.*").Save(image.Commit)
no, this needs to happen regardless of feature flag.

2023-03-02 22:09 UTC, omaciel approved these changes
/lgtm

Looks like my concerns/suggestions have been addressed.

2023-03-06 19:09 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +	var packagesExistsMap map[string]*models.InstalledPackage
we need to declare to be able to use it

2023-03-06 20:00 UTC, de1987 approved these changes

2023-03-06 20:35 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +	db.DB.Omit("Image.InstalledPackages.*").Save(image.Commit)
I'm still iffy on introducing a feature in one PR and its flagged replacement in the same PR, but not a show stopper for me.

2023-03-06 20:36 UTC, loadtheaccumulator approved these changes
I'm still iffy on introducing a feature in a PR and its flagged replacement in the same PR, but not a show stopper for me.

2023-03-06 20:52 UTC, merged