THEEDGE-3037
RedHatInsights/edge-api pull request #1892
Opened 2023-02-15 18:01 UTC by de1987

# Description
The edge-api was returning the wrong HTTP status when trying to update an image that is not the latest.
These changes fix the issue.

FIXES: [THEEDGE-3037](https://issues.redhat.com/browse/THEEDGE-3037)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2023-02-15 18:31 UTC, de1987 commented
/retest

2023-02-15 19:50 UTC, mgold1234 commented on pkg/routes/images_test.go
> +			It("should create image update successfully", func() {
do you mean that the image update successfully?
I think maybe the 'create' is uncesussery here

2023-02-15 21:15 UTC, omaciel requested changes
Looking good and it'll look even better with more tests :)

2023-02-15 21:15 UTC, omaciel commented on pkg/services/images.go
> +	if image.Commit != nil && image.Commit.Status == models.ImageStatusSuccess {
I feel that we should add tests for this dual conditional statement. It doesn't look like we testing `processImage` directly (yes, I know it's a 'private' function :P

2023-02-15 21:15 UTC, omaciel commented on pkg/services/images.go
> +	if image.Commit != nil && image.Commit.Status == models.ImageStatusBuilding {
I feel that we should add tests for this dual conditional statement. It doesn't look like we testing `UpdateImageStatus` directly

2023-02-16 12:05 UTC, de1987 commented on pkg/routes/images_test.go
> +			It("should create image update successfully", func() {
it's not updating an image, it's in the step that creates the update itself
any suggestion to improve the description?

2023-02-16 13:15 UTC, de1987 commented on pkg/services/images.go
> +	if image.Commit != nil && image.Commit.Status == models.ImageStatusBuilding {
I agree with you, after carefully analyzing the tests I fixed the mocks and removed those changes

2023-02-16 14:40 UTC, ldjebran commented on pkg/routes/images_test.go
> +				mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).DoAndReturn(func(image *models.Image) (*models.Image, error) {
```suggestion
				mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).Return(image, nil)
```
we do not need the function here

2023-02-16 14:45 UTC, ldjebran reviewed
lgtm, left only one comment

2023-02-16 14:58 UTC, de1987 commented on pkg/routes/images_test.go
> +				mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).DoAndReturn(func(image *models.Image) (*models.Image, error) {
hey @ldjebran thank you for your suggestion
for this one, it's required because by using `Return` only the main code loses the pointer reference and causes panic
with `DoAndReturn` is able to get the pointer and just return it

I double-check with your suggestion and it's causing panic

2023-02-16 15:02 UTC, omaciel approved these changes
/lgtm

2023-02-16 15:11 UTC, ldjebran commented on pkg/routes/images_test.go
> +				mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).DoAndReturn(func(image *models.Image) (*models.Image, error) {
and with the pointer 

```go
mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).Return(&image, nil)
```

2023-02-16 16:09 UTC, ldjebran commented on pkg/routes/images_test.go
> +				mockImageBuilder.EXPECT().ComposeCommit(gomock.Eq(&composeImage)).DoAndReturn(func(image *models.Image) (*models.Image, error) {
after an offline  discussion and debugging session we came on that we need this function, and we need to return the image received by ComposeCommit that we cannot control from our test.
resolving question

2023-02-16 16:09 UTC, ldjebran approved these changes
lgtm, Thanks @de1987

2023-02-16 16:27 UTC, merged