content-sources: API return HMS repositories
RedHatInsights/edge-api pull request #1951
Opened 2023-03-13 13:39 UTC by ldjebran

# Description

- To preserve compatibility: Return HMS repositories as thirdparty repos models with arbitrary/virtual ids, except for the ones already selected we need to supply their real ids , this happens when we update an image, and we supply an imageID in url param. The resolution is to have virtual ids superior to any id known in the current context. 
- Introduced a function GetImageByIDExtended that allow to have the image only with the data that are needed, and to not overcomplicate/overload this function for simple usage, when gormDB is not supplied (is nil) the core image is returned without any data queried.
- All the code is 100 % covered.

FIXES: THEEDGE-3158

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2023-03-13 15:22 UTC, de1987 commented on pkg/routes/thirdpartyrepo.go
> +	}
is this error handled somewhere else?

2023-03-13 15:43 UTC, de1987 requested changes

2023-03-13 15:43 UTC, de1987 commented on pkg/routes/thirdpartyrepo_test.go
> +
could we have to check when the `imageID` is missing?
WDYT?

2023-03-13 15:51 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +	}
This is not an error, this mean we have no error , and no image

2023-03-13 16:03 UTC, de1987 approved these changes

2023-03-13 16:04 UTC, ldjebran commented on pkg/routes/thirdpartyrepo_test.go
> +
we have a test without image , listing with filtering by name

2023-03-14 17:02 UTC, mgold1234 commented on pkg/routes/thirdpartyrepo.go
> +		// calculate the id to set , to not have conflict with the saved one on db,
```suggestion
		// calculate the id to set , that will not have a conflict with the saved one on db,
```

2023-03-14 17:02 UTC, mgold1234 commented on pkg/services/images.go
> +// GetImageByIDExtended retrieves an image by its identifier and use the supplied gormDB instance
```suggestion
// GetImageByIDExtended retrieves an image by its identifier and uses the supplied gormDB instance
```

2023-03-14 17:02 UTC, mgold1234 commented on pkg/services/images.go
> +// This is more customisable function version, that will get only the needed data, if gormDB is nil, we get an image without
```suggestion
// This is more customizable function version, that will get only the needed data, if gormDB is nil, we get an image without
```

2023-03-14 17:02 UTC, acosferreira commented on pkg/routes/thirdpartyrepo.go
> +		edgeRepo := models.ThirdPartyRepo{
Should we include also the new fields?

2023-03-15 08:17 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +		edgeRepo := models.ThirdPartyRepo{
for the UI  it's not needed , but for the API generally, this may be needed.
Will add them.

2023-03-15 08:19 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +		// calculate the id to set , to not have conflict with the saved one on db,
ok , will rephrase it .

2023-03-15 08:23 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +	// create a map of the image (if defined) for repos uuid to repos id and define the maximum id value
here we mean if image was defined (in the past)  and not to define in the present or future.

2023-03-15 08:41 UTC, ldjebran commented on pkg/services/images.go
> +// GetImageByIDExtended retrieves an image by its identifier and use the supplied gormDB instance
done

2023-03-15 08:41 UTC, ldjebran commented on pkg/services/images.go
> +// This is more customisable function version, that will get only the needed data, if gormDB is nil, we get an image without
done

2023-03-15 08:41 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +		// calculate the id to set , to not have conflict with the saved one on db,
done

2023-03-15 08:41 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +	// create a map of the image (if defined) for repos uuid to repos id and define the maximum id value
done

2023-03-15 08:42 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +		// when imageID not Defined return a nil image
done

2023-03-15 08:42 UTC, ldjebran commented on pkg/routes/thirdpartyrepo.go
> +		edgeRepo := models.ThirdPartyRepo{
done

2023-03-15 08:44 UTC, ldjebran commented
@acosferreira @mgold1234 thanks you for your review, all comments has been applied, please revisit.
@de1987 thanks for your review, your approval has been dismissed because of new commits, please revisit.

2023-03-15 10:50 UTC, ldjebran commented
/retest

2023-03-15 12:13 UTC, adeliaferreira approved these changes
LGTM

2023-03-15 13:39 UTC, mgold1234 commented
/lgtm

2023-03-15 14:46 UTC, merged