content-sources: submit content-sources repositories to image builder.
RedHatInsights/edge-api pull request #1958
Opened 2023-03-16 16:58 UTC by ldjebran

# Description
- Fixes image ThirdParties repos when Creating/Updating Image before imagebuilder Compose, some repos exists and need updates, some needs to be created locally.
- Update Image Builder request repos with new repository fields, for now image builder support only GPGKey, CheckGPG

FIXES: THEEDGE-3083

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Tests update
- [ ] Refactor

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2023-03-16 17:16 UTC, acosferreira commented on pkg/services/images.go
> +			if existingEMRepo.Name != csRepo.Name {
what do you think to use the case instead the if?

2023-03-16 17:18 UTC, acosferreira commented on pkg/clients/imagebuilder/client.go
> +			enforceCheckGpg = true
what do you think to start the checkGpg as false and if thirdpartyrepos[i].GpgKey != "" set to true?
and we can remove the other if.

2023-03-16 17:52 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +			enforceCheckGpg = true
we have agreed with ana to add a comment, as we want to pass checkGpg only in case of enforce checkGpg is true.

2023-03-16 17:53 UTC, ldjebran commented on pkg/services/images.go
> +			if existingEMRepo.Name != csRepo.Name {
Offline with Ana we have updated this to a more compact version.

2023-03-16 17:55 UTC, acosferreira reviewed
lgtm

2023-03-16 19:13 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +		// assume that if repo has gpgKey, we should enforce CheckGPG
@mgold1234 what's the purpose of this change in the comment when the var is named gpgKey?

2023-03-16 19:22 UTC, loadtheaccumulator commented on pkg/clients/imagebuilder/client.go
> +		// we have no checkGpg field in custom repo or in remote content-sources repositories or in image model
@mgold1234 Line 541 in the suggestion above will not compile

2023-03-16 19:27 UTC, loadtheaccumulator requested changes

2023-03-16 19:27 UTC, loadtheaccumulator commented on pkg/services/images.go
> +		// need to save the repos to database
When you say "save the repos to the database" are we intentionally duplicating the data from the HMS API in the Edge DB with new code, or only as a byproduct of using the existing code that writes the relationship?

2023-03-17 09:59 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +		// we have no checkGpg field in custom repo or in remote content-sources repositories or in image model
rephrased in second commit as :
```go
// there is no CheckGpg field in:
//	models.ThirdPartyRepo, repositories.Repository, models.Image
// assume that if repo has a GpgKey, we should set enforceCheckGPG to true
```

2023-03-17 10:31 UTC, ldjebran commented on pkg/services/images.go
> +		// need to save the repos to database
Removed the comment as it make no sense, and we are not just saving the repos.
Facts about SetImageContentSourcesRepositories (we need to keep this function very simple):
- Is not doing any migration of the current local repos to content-sources (this is the job the migration script + when reading repos from the API)
- It create new records locally for those content-sources repos that do not exist locally of course checking by their UUID.
- The records that already exist locally(with UUID) are used and updated if any changes occurred 
So we are not duplicating Data in the context of content-sources repositories.


Any other job should be handled by the migration strategy that will have two phases 
1- Migration script to repair the current duplicated records, as many records may have  the same URL and already used with images, 
note: we cannot upload our data to remote content-sources  by a migration script as we cannot login with that organization.
2- When retrieving repos via API, as we are logged as the organization, we can upload our local repos to remote content-sources and set their UUID to the remote one.
we are going to discuss this offline in details.

2023-03-17 10:33 UTC, ldjebran commented
@mgold1234 @loadtheaccumulator thank you for your view, updated the comments, and responded to the questions.

2023-03-17 15:29 UTC, ldjebran commented on pkg/services/images.go
> +		// need to save the repos to database
The second one e.g. : we always reading from Content Sources via API call using the Content Sources UUID we store to keep that image<->repo relationship as reference

2023-03-19 11:25 UTC, mgold1234 approved these changes
/lgtm

2023-03-20 14:12 UTC, de1987 approved these changes

2023-03-20 14:24 UTC, de1987 commented on pkg/services/images.go
> +	}
based on clean code, it could be extracted into a small function
e.g: `createRepoMap`

2023-03-20 14:25 UTC, de1987 commented on pkg/services/images.go
> +				existingEMRepo.PackageCount != csRepo.PackageCount {
based on clean code, it could be var boolean inline
e.g: `isRepoChanged`

2023-03-20 16:06 UTC, de1987 approved these changes

2023-03-20 22:10 UTC, loadtheaccumulator approved these changes
lgtm. we can refactor if we need to revisit temporary DB caching of data when used in an image

2023-03-21 09:15 UTC, merged