Add description to ConfigureHttpClient fuction
RedHatInsights/edge-api pull request #1960
Opened 2023-03-16 18:44 UTC by mgold1234

# Description

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-03-16 18:50 UTC, loadtheaccumulator requested changes

2023-03-16 18:50 UTC, loadtheaccumulator commented on .gitignore
> +rebase.sh
Please remove this rebase.sh script.

2023-03-16 18:50 UTC, loadtheaccumulator commented on rebase.sh
> +
Please remove this file.

2023-03-16 18:50 UTC, loadtheaccumulator commented on pkg/clients/client.go
> +// ConfigureHttpClient return https client in case there is TLS CA path,
I would reword to say it adds a TLS config to an http client.
This function is called on the assumption there is a TLS CA Path
Line below looks awesome, but you could mention that if there is no TLS CA, it logs an error and returns the original unmodified client.

2023-03-17 10:38 UTC, ldjebran commented on rebase.sh
_New github feature , to comment on the whole file :smiley:_ 

Please remove this file.

2023-03-20 01:56 UTC, loadtheaccumulator commented
It looks like this grew in scope from just adding a description. Please separate them so that a problem with one does not interfere with the other.

2023-03-20 17:01 UTC, mgold1234 commented on pkg/clients/client.go
> +// ConfigureHttpClient return https client in case there is TLS CA path,
@loadtheaccumulator added the changes

2023-03-20 20:16 UTC, loadtheaccumulator approved these changes
lgtm

2023-03-21 09:14 UTC, ldjebran approved these changes

2023-03-21 09:15 UTC, ldjebran commented
/retest

2023-03-21 09:38 UTC, merged