add a fix to upgrade playbook in case of customer change the configuration
RedHatInsights/edge-api pull request #1976
Opened 2023-03-27 14:26 UTC by mgold1234

the configuration file.
related to https://issues.redhat.com/browse/THEEDGE-3223?focusedId=21963643&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21963643

# Description

FIXES: 

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-03-27 15:23 UTC, loadtheaccumulator commented
What happens if a line other than proxy is added?

2023-03-27 20:29 UTC, de1987 commented
> What happens if a line other than proxy is added?

agree with Jonathan
and if it's empty? or null?

Also, what is the security it could imply?

2023-03-27 20:30 UTC, acosferreira requested changes
validates if has all the required keys present 
and should just change the contenturl value to the updated value.
this will prevent to change the file in case the user add any other confi besides the proxy

2023-03-28 01:03 UTC, loadtheaccumulator commented
> ... should just change the contenturl value to the updated value. this will prevent to change the file in case the user add any other confi besides the proxy

+1 

@mgold1234 That is what I was recommending in our chat. Any values passed via the playbook should be added/modified instead of overwriting the entire file with customizations read from local and added back.

2023-03-29 11:35 UTC, ldjebran reviewed
awesome resolution, but we should be also able  to create the file if it's missing 
and of course with the config section.
```
[remote “rhel-edge”]


```

2023-03-29 11:35 UTC, ldjebran commented on templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
> -      [remote "{{ ostree_remote_name }}"]
I think we are missing the config section

2023-03-29 11:41 UTC, ldjebran commented on templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
> -      [remote "{{ ostree_remote_name }}"]
is "ostree_remote_name" var is a constant or may change over updates ?

2023-03-29 12:13 UTC, ldjebran commented on templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
> -      [remote "{{ ostree_remote_name }}"]
I think we should
 what  do you think @loadtheaccumulator @acosferreira

2023-03-29 14:18 UTC, loadtheaccumulator commented on templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
> -      [remote "{{ ostree_remote_name }}"]
@mgold1234 @ldjebran I think if file exists would be a good check. You would do it programmatically out of habit, so probably a good practice to continue here.

2023-03-29 14:18 UTC, loadtheaccumulator commented on templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
> -      [remote "{{ ostree_remote_name }}"]
Take a look at backup and create options.

2023-03-29 14:19 UTC, loadtheaccumulator requested changes

2023-03-29 14:19 UTC, loadtheaccumulator commented on templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
> +      ansible.builtin.lineinfile:
Yeah. Please backup the file before modifying, and take a look at the create option to create the file if it doesn't exist.

2023-04-12 17:42 UTC, closed without merging

2023-04-12 17:43 UTC, loadtheaccumulator commented
https://github.com/RedHatInsights/edge-api/pull/1994 replaces this PR.