add post migration flag to custom repositories
RedHatInsights/edge-api pull request #2022
Opened 2023-04-27 14:50 UTC by mgold1234

# Description
 

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-05-01 14:49 UTC, loadtheaccumulator requested changes
requesting change for discussion

2023-05-01 14:49 UTC, loadtheaccumulator commented on unleash/features/feature.go
> +var PostMigrateCustomRepositories = &Flag{Name: "edge-management.post_migrate_custom_repositories", EnvVar: "FEATURE_POST_MIGRATE_CUSTOM_REPOSITORIES"}
As named, it's unclear what is being turned on/off after migration.
Suggesting adding "delete" to the name..
e.g., post_migrate_delete_repos

2023-05-01 20:43 UTC, de1987 commented on unleash/features/feature.go
> +var PostMigrateCustomRepositories = &Flag{Name: "edge-management.post_migrate_custom_repositories", EnvVar: "FEATURE_POST_MIGRATE_CUSTOM_REPOSITORIES"}
+1 for @loadtheaccumulator suggestion

2023-05-02 10:18 UTC, mgold1234 commented on unleash/features/feature.go
> +var PostMigrateCustomRepositories = &Flag{Name: "edge-management.post_migrate_custom_repositories", EnvVar: "FEATURE_POST_MIGRATE_CUSTOM_REPOSITORIES"}
thank you for your advice

2023-05-02 12:08 UTC, de1987 approved these changes

2023-05-02 13:03 UTC, ldjebran commented on unleash/features/feature.go
> +var PostMigrateDeleteCustomRepositories = &Flag{Name: "edge-management.post_migrate_delete_repos", EnvVar: "FEATURE_POST_MIGRATE_CUSTOM_REPOSITORIES"}
```suggestion
var PostMigrateDeleteCustomRepositories = &Flag{Name: "edge-management.post_migrate_delete_repos", EnvVar: "FEATURE_POST_MIGRATE_DELETE_REPOSITORIES"}
```

2023-05-02 14:23 UTC, mgold1234 commented on unleash/features/feature.go
> +var PostMigrateDeleteCustomRepositories = &Flag{Name: "edge-management.post_migrate_delete_repos", EnvVar: "FEATURE_POST_MIGRATE_CUSTOM_REPOSITORIES"}
@ldjebran done

2023-05-02 14:57 UTC, loadtheaccumulator approved these changes
lgtm

2023-05-02 15:03 UTC, ldjebran approved these changes
lgtm

2023-05-02 15:04 UTC, merged