Post migrate delete custom repository
RedHatInsights/edge-api pull request #2026
Opened 2023-05-02 16:11 UTC by mgold1234

# Description

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-05-02 16:37 UTC, loadtheaccumulator commented
@mgold1234  Please fill in the description and add the Jira # to the FIXES: for the PR

2023-05-02 16:44 UTC, loadtheaccumulator requested changes

2023-05-02 16:44 UTC, loadtheaccumulator commented on cmd/migraterepos/main.go
> +	if feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
Why a feature flag for only logging?

2023-05-02 16:44 UTC, loadtheaccumulator commented on cmd/migraterepos/main.go
> +	if _, err := postmigraterepos.PostMigrateDeleteCustomRepo(); err != nil {
Is there a reason to run this if the feature flag is off?
If not, I recommend adding it to the above so it doesn't make the call.

2023-05-02 16:44 UTC, loadtheaccumulator commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if !feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
Should all of this function be feature flagged? I'm thinking remove this and just feature flag the caller.

2023-05-02 17:24 UTC, mgold1234 commented on cmd/migraterepos/main.go
> +	if feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
@loadtheaccumulator thanks, I put the second if in a wrong place

2023-05-02 17:24 UTC, mgold1234 commented on cmd/migraterepos/main.go
> +	if _, err := postmigraterepos.PostMigrateDeleteCustomRepo(); err != nil {
yes make sense

2023-05-02 17:25 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if !feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
what do you mean 'just feature flag the caller'? do you mean to leave it only on the main?

2023-05-02 18:24 UTC, loadtheaccumulator commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if !feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
yes. Don't bother with a feature flag in this function and just use the flag in main.go

2023-05-03 09:01 UTC, ldjebran commented on cmd/migraterepos/repairrepos/repairrepos.go
> +var ErrPostMigrationNotAvailable = errors.New("post migration  delete repository is not available")
move this error to postmigraterepos module

2023-05-03 09:08 UTC, ldjebran commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if err := db.DB.Debug().
may be this will be expensive for memory (without limits) and we should use count only, as this the purpose of this task.

2023-05-03 09:12 UTC, ldjebran commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if !feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
I used this in other modules , e.g. feature flag in public functions , to be sure that the function is not executed even if called directly , also to be able to unit-test the feature flag is working as expected.

@loadtheaccumulator what do you think ?

2023-05-03 12:04 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if !feature.PostMigrateDeleteCustomRepositories.IsEnabled() {
I agree with you Djebran, if I remove this there is no way to check it in case it is disable in unit tests

2023-05-03 13:13 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +		logger.WithField("error", result.Error).Error("Error when trying to delete ")
done

2023-05-03 13:13 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +		logger.WithField("error", err.Error()).Error("Error checking migrated custom repository existence")
done

2023-05-03 13:16 UTC, mgold1234 commented on cmd/migraterepos/repairrepos/repairrepos.go
> +var ErrPostMigrationNotAvailable = errors.New("post migration  delete repository is not available")
done

2023-05-04 07:23 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	if err := db.DB.Debug().
remove the debug

2023-05-04 12:49 UTC, loadtheaccumulator approved these changes
lgtm

2023-05-04 13:20 UTC, de1987 reviewed
I left a suggestion, could you take a look?

2023-05-04 13:20 UTC, de1987 commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	return result.RowsAffected, nil
since it's loading all the custom repos before deleting those, as a good practice I would suggest using this list to delete from the database

my suggestion is, instead of performing the same `WHERE` condition again in the `DELETE`, you could use `IN` against the list it's already loaded

WDYT?

2023-05-04 13:35 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
> +			repairrepos.DefaultDataLimit = 1
done

2023-05-04 13:35 UTC, ldjebran commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	return result.RowsAffected, nil
https://gorm.io/docs/delete.html  see db.Delete(&users)

2023-05-04 13:36 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
> +			initialConfAuth = config.Get().Auth
done

2023-05-04 13:40 UTC, ldjebran commented on cmd/migraterepos/postmigraterepos/postmigraterepos.go
> +	return result.RowsAffected, nil
but I am also OK with the current implementation, as they will be deleted forever.

2023-05-04 13:40 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
> +			Expect(err).ToNot(HaveOccurred())
done

2023-05-04 13:41 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
> +			Expect(err).ToNot(HaveOccurred())
done

2023-05-05 13:01 UTC, mgold1234 commented on cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
> +			Expect(err).To(HaveOccurred())
done

2023-05-05 14:15 UTC, ldjebran approved these changes
lgtm

2023-05-05 14:41 UTC, merged