create imageset_api
RedHatInsights/edge-api pull request #2113
Opened 2023-06-28 10:45 UTC by mgold1234

# Description
this commit create the imageset_api to generate the api documentation for imageset
related issue: https://issues.redhat.com/browse/THEEDGE-3344

FIXES: 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-06-28 18:25 UTC, loadtheaccumulator requested changes
Looking good, but some requested changes.

2023-06-28 18:25 UTC, loadtheaccumulator commented on pkg/models/imagesets_api.go
> +	Version int     `json:"version" example:"0"`
Can version be zero or need to start at 1?

2023-06-28 18:25 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.Image	true	"request body"
This will still display all of models.Image. Should this be the new struct you created?

2023-06-28 18:25 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.ImageSetAPI	true	"request body"
DELETE also has a different Param format from POST. So line 767 is the correct entry instead of the new 768.

2023-06-28 18:25 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.Image	true	"request body"
GET has a different Param format from POST. I'll dig up the example.

2023-06-28 18:30 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.Image	true	"request body"
GET follows this example:
// @Param  uuid  path  string    true  "Identifier of the Repository"

2023-06-28 18:32 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.Image	true	"request body"
If it's required, replace line 634 and remove 635.
If optional, replace 635 and remove 634.

2023-06-29 10:27 UTC, mgold1234 commented on pkg/routes/imagesets.go
> +// @Param        body	body	models.Image	true	"request body"
@loadtheaccumulator can you please explain from where you took this param uuid path string true "Identifier of the Repository"?

2023-06-29 14:42 UTC, loadtheaccumulator requested changes

2023-06-29 14:42 UTC, loadtheaccumulator commented on api/docs.go
Per previous review, please remove.

2023-06-29 14:42 UTC, loadtheaccumulator commented on api/swagger.json
Per previous review, please remove.

2023-06-29 14:42 UTC, loadtheaccumulator commented on api/swagger.yaml
Per previous review, please remove.

2023-06-29 20:03 UTC, loadtheaccumulator requested changes
Each Param needs to follow the syntax for its type. Background on HTTP params is in a link in the review comment. The docs for swaggo (and the Param format) are here: https://github.com/swaggo/swag/tree/master#api-operation

2023-07-05 17:32 UTC, loadtheaccumulator requested changes
Looks pretty close. Just a couple of requests and questions.

2023-07-05 17:32 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Tags         image-sets
I'm good with going with lowercase for the tags, but it needs to be consistent across all of them for image-sets, and the change needs to be communicated back to the team.

2023-07-05 17:32 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param		 image_set_id path int true "the image-set id"
Indent issue. This happened to me, but didn't show up locally. Extra tab, maybe? This applies to the same below as well.

2023-07-05 18:01 UTC, loadtheaccumulator commented on pkg/models/imagesets_api.go
> +	Name    string  `json:"name" example:"my-edge-image"`
Do you also want to add // descriptions for each field in this PR, or do that in another one?

2023-07-06 13:43 UTC, ldjebran commented on go.mod
> +	github.com/swaggo/swag v1.16.1
let's add this dependency in standalone PR.

what do you think ?

2023-07-07 15:36 UTC, loadtheaccumulator requested changes

2023-07-07 15:36 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Tags         image-sets
Looks nice. Works for me.

2023-07-07 15:36 UTC, loadtheaccumulator commented
Looking good. Just the remaining tweaks.

2023-07-09 08:05 UTC, mgold1234 commented on go.mod
> +	github.com/swaggo/swag v1.16.1
done

2023-07-09 08:05 UTC, mgold1234 commented on pkg/models/imagesets_api.go
> +	Name    string  `json:"name" example:"my-edge-image"`
different pr

2023-07-10 08:56 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      404 {object} errors.NotFound "The Image Set was not found."
I am not sure we return 404 http status here.

2023-07-10 09:04 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Param		 image_set_id path      int       true   "the image-set id"
indent by spaces

2023-07-10 09:05 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      404 {object} errors.NotFound "The Image-Set was not found."
not sure if we return 404 http status , please check

2023-07-10 09:45 UTC, ldjebran reviewed
looks good left some comments

2023-07-10 10:50 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Param		 image_set_id path integer true "the image-set id"
indent by space

2023-07-10 10:51 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Param		 image_id     path int true "the image id"
indent by space

2023-07-10 10:52 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
missing 404 http status

2023-07-10 10:53 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Param		 ImageSetId		path    int  true  "Identifier of the ImageSet"
indent by space

2023-07-10 10:54 UTC, ldjebran reviewed
overall looks good , left some comment

2023-07-10 11:58 UTC, mgold1234 commented on pkg/routes/imagesets.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
there is no 400 error in the original-
    get:
      operationId: GetImageSetsDevicesByID
      parameters:
        - name: ImageSetId
          in: path
          required: true
          description: ImageSetId
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.DevicesForImageSet"
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.

2023-07-10 15:07 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
what we are returning in case image-set with imageSetID as ID does not exist ?

2023-07-10 15:14 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
so we are missing 400 and 404

2023-07-10 15:35 UTC, mgold1234 commented on pkg/routes/imagesets.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
added

2023-07-10 15:40 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Failure      404 {object} errors.NotFound "The Image Set was not found."
Thanks @mgold1234

2023-07-10 15:41 UTC, ldjebran approved these changes
lgtm

2023-07-11 04:06 UTC, loadtheaccumulator approved these changes

2023-07-11 07:49 UTC, merged