add support for /devices end point in Swagger
RedHatInsights/edge-api pull request #2127
Opened 2023-07-06 11:02 UTC by mgold1234

# Description
add support for /devices end point

FIXES: related to ticket -https://issues.redhat.com/browse/THEEDGE-3345

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-07-06 13:53 UTC, ldjebran commented on pkg/models/imagesets_api.go
> +type ImageSetAPI struct {
but I saw this declaration in an other PR https://github.com/RedHatInsights/edge-api/pull/2113/files#diff-eaabaac0bfcb6ec915aa6575f6a85003e79d5d19dc2dd00ea399b5e60b03b944R3

2023-07-06 13:54 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Param		 per_page        query integer false "field: maximum devices per page"
indent with spaces and it will be uniform :)

2023-07-06 13:57 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Description  Get all image sets By ID.
we will have only one image-set returned so maybe

```text
Get image set by ID

```

2023-07-09 12:47 UTC, mgold1234 commented on go.mod
> +	github.com/swaggo/swag v1.16.1
done

2023-07-09 12:48 UTC, mgold1234 commented on pkg/models/imagesets_api.go
> +type ImageSetAPI struct {
this pr depends on other pr, it contains only devices files

2023-07-09 12:49 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param		 per_page        query integer false "field: maximum devices per page"
done

2023-07-09 12:51 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param		 page            query integer false "field: which page to query from"
only in devices_api file

2023-07-10 09:46 UTC, ldjebran commented on pkg/models/devices_api.go
> +	OrgID   string
Account and Org can be removed

2023-07-10 09:48 UTC, ldjebran commented on pkg/models/devices_api.go
> +	OrgID   string
the uuid, rhcclientid are important for device

2023-07-10 09:50 UTC, ldjebran commented on pkg/models/devices_api.go
> +	OrgID   string
not sure we should inherit from device , but put the most relevant fields here

2023-07-10 09:51 UTC, ldjebran commented on pkg/models/devices_api.go
> +}
not sure we should inherit from device , but put the most relevant fields here

2023-07-10 09:54 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Success      200 {object} models.Image
we are returning ImageUpdateAvailable and not image , can you recheck that?

2023-07-10 09:54 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Failure      500 {object} errors.InternalServerError "There was an internal server error."
Please check if we are returning 404 http status

2023-07-10 09:57 UTC, ldjebran commented on pkg/routes/devices.go
> -// @Summary      Placeholder summary
why you removed the api description, we are serving this endpoint, can you check again ?

2023-07-10 10:06 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Param		 sort_by            query string  false "fields: name, uuid, update_available, image_id. To sort DESC use - before the fields."
think we sort only by name and last_seen please check again ?

2023-07-10 10:07 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Param		 image_id           query string false "field: filter by image id"
type here should be integer

2023-07-10 10:10 UTC, ldjebran reviewed
reviewed only files devices_api.go and devices.go 
left some comment, please take a look/recheck

2023-07-10 10:13 UTC, ldjebran commented on pkg/routes/imagesets.go
> +// @Description  Get all image sets By ID.
this is part of an other PR, resolve here

2023-07-10 12:43 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Success      200 {object} models.Image
this is what we return:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Image:
                      $ref: "#/components/schemas/v1.Image"
                    PackageDiff:
                      $ref: "#/components/schemas/v1.PackageDiff"
     can you addvice me how to define that?

2023-07-10 12:45 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param		 image_id           query string false "field: filter by image id"
- name: image_id
          in: query
          description: 'field: filter by image id'
          schema:
            type: string

2023-07-11 08:18 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Success      200 {object} models.Image
can you look at the code, may be there is  an error in path.yaml file ?

2023-07-11 08:19 UTC, ldjebran commented on pkg/routes/devices.go
> +// @Param		 image_id           query string false "field: filter by image id"
that's an error in  path.yaml file

2023-07-11 09:33 UTC, mgold1234 commented on pkg/routes/devices.go
> -// @Summary      Placeholder summary
because I dont find this end point in path.yaml

2023-07-11 09:34 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param		 sort_by            query string  false "fields: name, uuid, update_available, image_id. To sort DESC use - before the fields."
operationId: getDevicesView
      parameters:
        - name: sort_by
          in: query
          description: "fields: name, uuid, update_available, image_id. To sort DESC use - before the fields."
          schema:
            type: string
        - name: name
          in: query
          description: "field: filter by name"
          schema:
            type: string
        - name: update_available
          in: query
          description: "field: filter by update_available"
          schema:
            type: boolean
        - name: uuid
          in: query
          description: 'field: filter by uuid'
          schema:
            type: string
        - name: created_at
          in: query
          description: 'field: filter by creation date'
          schema:
            type: string
        - name: image_id
          in: query
          description: 'field: filter by image id'
          schema:
            type: string
        - name: limit
          in: query
          description: "field: return number of devices until limit is reached. Default is 100."
          schema:
            type: integer
        - name: offset
          in: query
          description: "field: return number of devices begining at the offset."
          schema:
            type: integer

2023-07-11 09:35 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param		 image_id           query string false "field: filter by image id"
fixed

2023-07-11 20:55 UTC, de1987 commented on pkg/models/devices_api.go
> +	Devices         []Device         `gorm:"many2many:updatetransaction_devices;save_association:false" json:"Devices"`
since these changes are only for Swagger, should we keep the `gorm` annotation?

2023-07-12 04:58 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	Devices         []Device         `gorm:"many2many:updatetransaction_devices;save_association:false" json:"Devices"`
I am not sure, @ldjebran your thoughts?

2023-07-12 13:32 UTC, adeliaferreira submitted a review, later dismissed
lgtm

2023-07-13 13:24 UTC, ldjebran commented on pkg/models/devices_api.go
> +	Devices         []Device         `gorm:"many2many:updatetransaction_devices;save_association:false" json:"Devices"`
Good catch @de1987. This is strictly external api structs, gorm should not be present here.

2023-07-13 21:59 UTC, loadtheaccumulator requested changes
I think with all of the suggested changes it'll be good to go.

2023-07-13 21:59 UTC, loadtheaccumulator commented on pkg/models/devices_api.go
> +	Devices         []Device         `gorm:"many2many:updatetransaction_devices;save_association:false" json:"Devices"`
Yeah. @mgold1234 json and example field tags are all we need for these at this point.

2023-07-13 21:59 UTC, loadtheaccumulator commented on pkg/models/devices_api.go
> +	Account     string   `json:"Account" gorm:"index"`
Account and OrgID don't need to be passed in via the body of the request

2023-07-13 21:59 UTC, loadtheaccumulator commented on pkg/models/devices_api.go
> +	Account         string           `json:"Account"`
Account and OrgID don't need to be passed in via the body of the request

2023-07-13 21:59 UTC, loadtheaccumulator commented on pkg/routes/imagesets.go
> +// @Param		 image_set_id path      int       true   "the image-set id"
Not a stopper, but indent could be fixed with the other changes.

2023-07-18 03:21 UTC, loadtheaccumulator requested changes

2023-07-18 03:21 UTC, loadtheaccumulator commented on pkg/models/devices_api.go
> +	Model
Model is not necessary in these structs since they are only being used to generate API Docs.

2023-07-18 03:21 UTC, loadtheaccumulator commented on pkg/routes/devices.go
> +// @Param	 offset             query integer	false "field: return number of devices begining at the offset."
Should integer be replaced with int?

2023-07-18 03:21 UTC, loadtheaccumulator commented on pkg/routes/devices.go
> +// @Param	 page            query integer false "field: which page to query from"
integer or int here?

2023-07-18 03:21 UTC, loadtheaccumulator commented on pkg/models/devices_api.go
> +	LastSeen   string // TODO: Can be deleted when we start saving lastseen field on the Device object
General comment... Consider removing the comments when cutting and pasting from the original structs. Some of it shouldn't appear in the openapi.json file.

2023-07-18 09:26 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	Model
done

2023-07-18 09:27 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	LastSeen   string // TODO: Can be deleted when we start saving lastseen field on the Device object
thank you, remove it

2023-07-18 09:28 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param	 offset             query integer	false "field: return number of devices begining at the offset."
change thank you

2023-07-18 09:28 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Param	 page            query integer false "field: which page to query from"
change to int

2023-07-19 06:50 UTC, mgold1234 commented on pkg/routes/imagesets.go
> +// @Param		 image_set_id path      int       true   "the image-set id"
done

2023-07-20 17:16 UTC, loadtheaccumulator requested changes

2023-07-20 19:36 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	Devices     []Device `faker:"-" json:"Devices"`
removed

2023-07-20 19:38 UTC, mgold1234 commented
@loadtheaccumulator I think we should leave the deviceGroupAPI struct in this file

2023-07-24 09:53 UTC, ldjebran commented on pkg/routes/devices.go
> -// @Summary      Placeholder summary
OK it seems we are documenting that end point

2023-07-24 10:16 UTC, ldjebran commented on api/docs.go
remove this file

2023-07-24 10:16 UTC, ldjebran commented on api/swagger.json
remove this file

2023-07-24 10:16 UTC, ldjebran commented on api/swagger.yaml
remove this file

2023-07-24 10:20 UTC, ldjebran commented on pkg/models/devices_api.go
> +}
DeviceAPI and EdgeDeviceAPI looks identical are you sure ?

2023-07-24 10:21 UTC, ldjebran commented on pkg/models/devices_api.go
> +	Commit          *Commit          `json:"Commit"`
maybe 
```go
Commit *CommitAPI
```

2023-07-24 10:21 UTC, ldjebran commented on pkg/models/devices_api.go
> +	OldCommits      []Commit         `json:"OldCommits"`
maybe 
```go
OldCommits []CommitAPI
```

2023-07-24 10:22 UTC, ldjebran commented on pkg/models/devices_api.go
> +	DispatchRecords []DispatchRecord `json:"DispatchRecords"`
DispatchAPI ?

2023-07-24 10:24 UTC, ldjebran commented on pkg/models/devices_api.go
> +type EdgeDeviceAPI struct {
missing example in all the structs

2023-07-24 10:26 UTC, ldjebran commented on pkg/models/devices_api.go
> +type EdgeDeviceAPI struct {
ah OK you are adding them in an other PR

2023-07-24 10:59 UTC, mgold1234 commented on pkg/models/devices_api.go
> +}
edgeDevice struct is 
 -type EdgeDevice struct {
	*Device
	DeviceName string // TODO: Can be deleted when we start saving the name field on the Device object
	LastSeen   string // TODO: Can be deleted when we start saving lastseen field on the Device object
	// Booted status is referring to the LastDeployment of this device
	// TODO: Needs to be rethinked when we get to the greenbot epic
	Booted  bool
	Account string
	OrgID   string
}
and I replace device with device struct so now they look the same, remove one of them?

2023-07-24 11:01 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	Commit          *Commit          `json:"Commit"`
we have CommitAPI in images_api
// CommitAPI is  a struct ...
type CommitAPI struct {
	Arch string `json:"arch" example:"x86_64"` // The commit architecture
} // @name Commit
is it good enough?

2023-07-24 11:02 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	OldCommits      []Commit         `json:"OldCommits"`
same

2023-07-24 11:02 UTC, mgold1234 commented on pkg/models/devices_api.go
> +	DispatchRecords []DispatchRecord `json:"DispatchRecords"`
done

2023-07-24 11:10 UTC, mgold1234 commented on pkg/models/devices_api.go
> +}
I changed it to separate struct - edgeDeviceAPI

2023-07-24 11:17 UTC, mgold1234 commented on pkg/routes/devices.go
> +// @Success      200 {object} models.Image
this is from the yaml file 
  /updates/device/{DeviceUUID}/updates:
    get:
      operationId: GetUpdateAvailableForDevice
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type: string
        - name: latest
          in: query
          description: "query the latest or all updates"
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Image:
                      $ref: "#/components/schemas/v1.Image"
                    PackageDiff:
                      $ref: "#/components/schemas/v1.PackageDiff"

2023-07-24 18:19 UTC, loadtheaccumulator approved these changes
This is blocking another PR that is similar. @mgold1234 prefers not merging the two, so let's get this merged.

2023-07-24 18:29 UTC, acosferreira approved these changes
lgtm

2023-07-24 19:48 UTC, loadtheaccumulator commented
Mergify isn't merging it, so I am.

2023-07-24 19:48 UTC, merged