Update docs storage api
RedHatInsights/edge-api pull request #2135
Opened 2023-07-10 17:08 UTC by adeliaferreira

# Description
Update documentation tag for swaggo on /storage api requests

FIXES: THEEDGE-3394

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-07-11 04:27 UTC, loadtheaccumulator requested changes
Please double-check each of the @Param, @Success, and @Failure lines against the formatting in the documentation @ https://github.com/swaggo/swag

2023-07-11 04:27 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> +// @Success      303 {string} URL to redirect
Does this need to follow the same format as the others? For example...

// @Success  303 {string} string "URL to redirect"

2023-07-11 04:27 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> +// @Success      303 {string} URL signed to be redirect
Format question the same as the above 303.

2023-07-11 04:27 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> +// @Param		 updateTransactionID path integer true "Update Transaction Id"
Replace integer with int.

See https://github.com/swaggo/swag#attribute

2023-07-11 04:27 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> +// @Param		 installerID path string true "Id for the installer required"
Please line up the indents

2023-07-11 09:32 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
we do not have 500 http status

2023-07-11 09:32 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
we do not have 500 http status

2023-07-11 09:33 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
we do not have 500 http status

2023-07-11 09:33 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
we do not have 500 http status

2023-07-11 09:33 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Router       /storage/update-repos/{updateTransactionID}/content/{repoFilePath} [get]
missing 404 http status

2023-07-11 09:33 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
missing 404 http status

2023-07-11 09:33 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
missing 404 http status

2023-07-11 09:34 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Produce      json
// @Produce      octet-stream

2023-07-11 09:34 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Produce      json
// @Produce      octet-stream

2023-07-11 09:35 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Produce      json
// @Produce      octet-stream

2023-07-11 09:35 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Produce      json
// @Produce      octet-stream

2023-07-11 09:36 UTC, ldjebran commented on pkg/routes/storage.go
> +// @Description  This method will redirect request to a signed installer iso url
missing // @ID

2023-07-11 09:37 UTC, ldjebran commented on pkg/routes/storage.go
> +// @Description  Method will redirect to asigned url of an update-transaction based on repository content
missing
```go
 // @ID
 ```

2023-07-11 09:37 UTC, ldjebran commented on pkg/routes/storage.go
> +// @Description  Request will get access to content of an update-transaction file based on the path
missing
```go
 // @ID
 ```

2023-07-11 09:37 UTC, ldjebran commented on pkg/routes/storage.go
> +// @Description  Redirect request to a signed and valid url for an image commit repository from the path content
missing
```go
 // @ID
 ```

2023-07-11 12:38 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 updateTransactionID path integer true "id for update transaction id"
indent by spaces

2023-07-11 12:38 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 repoFilePath path string true "path to repository to be checked"
indent by spaces

2023-07-11 12:38 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 repoFilePath path integer true "path for repository file"
indent by spaces

2023-07-11 12:38 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 imageID path string true "Id to identify Image"
indent by spaces

2023-07-11 12:49 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 installerID path string true "Id for the installer required"
maybe better to write "Installer ID" instead of "Id for the installer required" WDYT?

2023-07-11 12:49 UTC, mgold1234 commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
"The request sent couldn't be processed."
--

2023-07-11 12:49 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Failure      404 {object} errors.NotFound	"the device update was not found"
```suggestion
// @Failure      404 {object} errors.NotFound	"installer not found.
--


" 
```

2023-07-12 11:49 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
On this method, on the line 204, we are creating a newInternalServerError, I navigated to inside this method and it returns a 500 http code. Is this part should not be covered on the documentation?

2023-07-12 11:50 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 installerID path string true "Id for the installer required"
changed

2023-07-12 11:52 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
this method use the method "redirectToStorageSignedURL" (Line: 65), inside this method, there's a newInternalServerError creation with code 500. Should we cover just the top method or all execution inside it?

2023-07-12 11:53 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
Similar as previous method, this one uses "serveStorageContent" (line:82) that contains a newInternalServerError.

2023-07-12 11:55 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
This method uses "redirectToStorageSignedURL" and inside it there's a internalServerError Creation

2023-07-12 11:56 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      500 {object} errors.InternalServerError
This method uses "serveStorageContent" (line:82) that contains a newInternalServerError.

2023-07-12 11:59 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Router       /storage/update-repos/{updateTransactionID}/content/{repoFilePath} [get]
I cannot found the path on this method that returns the 404, I just traced the respondWithAPIError with NewInternalServerError inside `redirectToStorageSignedURL` , Am I missing something?

2023-07-12 11:59 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
Added, Thanks

2023-07-12 12:00 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
cannot found the path on this method that returns the 404, I just traced the respondWithAPIError with NewInternalServerError inside redirectToStorageSignedURL , Am I missing something?

2023-07-12 12:01 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
Added, Thanks

2023-07-12 12:01 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Produce      json
Changed, Thanks

2023-07-12 12:02 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Produce      json
changed, Thanks

2023-07-12 12:02 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Produce      json
changed, Thanks

2023-07-12 12:02 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Produce      json
changed, thanks

2023-07-12 12:04 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Description  This method will redirect request to a signed installer iso url
added, Thanks

2023-07-12 12:05 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Description  Method will redirect to asigned url of an update-transaction based on repository content
added, thanks

2023-07-12 12:06 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Description  Request will get access to content of an update-transaction file based on the path
added, Thanks

2023-07-12 12:07 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Description  Bring the content for a image commit in a repository path
added, Thanks

2023-07-12 12:10 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 updateTransactionID path integer true "id for update transaction id"
changed, thanks

2023-07-12 12:10 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 repoFilePath path string true "path to repository to be checked"
changed, thanks

2023-07-12 12:12 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 repoFilePath path integer true "path for repository file"
changed, thanks

2023-07-12 12:14 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 imageID path string true "Id to identify Image"
changed, thanks

2023-07-12 12:15 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Failure      404 {object} errors.NotFound	"the device update was not found"
changed, thanks

2023-07-12 12:15 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
added, thanks

2023-07-12 12:16 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Success      303 {string} URL to redirect
changed according the example. Thanks

2023-07-12 12:16 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Success      303 {string} URL signed to be redirect
changed, thanks

2023-07-12 12:17 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 updateTransactionID path integer true "Update Transaction Id"
changed, thanks

2023-07-13 13:52 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
it's inside UpdateTransactionCtx function

2023-07-16 07:55 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 installerID path string true "Installer ID"
ident space

2023-07-16 07:55 UTC, mgold1234 commented on pkg/routes/storage.go
> +// @Param		 imageID path string true "Id to identify Image"
ident space

2023-07-20 02:07 UTC, loadtheaccumulator requested changes
I think it will be good to go after the comments Michal and I have made are addressed.

2023-07-20 02:07 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> +// @Failure		500 {object} errors.InternalServerError
Are there any failures for this endpoint path in the path.yml file?

2023-07-20 02:07 UTC, loadtheaccumulator commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
@adeliaferreira is it defined in the path.yml file?

2023-07-20 02:07 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetImageRepoFile return the content of an image commit repository path
The linter should complain about this line being removed.

2023-07-20 02:07 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetImageRepoFileContent redirect to a signed url of an image commit repository path content
The linter should complain about this line being removed.

2023-07-20 02:07 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetInstallerIsoStorageContent redirect to a signed installer iso url
The linter should complain about this line being removed.

2023-07-28 19:40 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetImageRepoFileContent redirect to a signed url of an image commit repository path content
Rephrasing. This comment needs to be there to pass the linter.

2023-07-28 19:40 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetImageRepoFile return the content of an image commit repository path
Rephrasing. This comment needs to be there to pass the linter.

2023-08-02 18:52 UTC, loadtheaccumulator commented on pkg/routes/storage.go
> -// GetInstallerIsoStorageContent redirect to a signed installer iso url
Rephrasing. This comment needs to be there to pass the linter.

2023-08-03 11:32 UTC, adeliaferreira commented on pkg/routes/storage.go
> -// GetInstallerIsoStorageContent redirect to a signed installer iso url
Re added , thanks

2023-08-03 11:33 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 installerID path string true "Installer ID"
changed, thanks

2023-08-03 11:33 UTC, adeliaferreira commented on pkg/routes/storage.go
> -// GetImageRepoFileContent redirect to a signed url of an image commit repository path content
re added, thanks

2023-08-03 11:34 UTC, adeliaferreira commented on pkg/routes/storage.go
> +// @Param		 imageID path string true "Id to identify Image"
changed, thanks

2023-08-03 11:35 UTC, adeliaferreira commented on pkg/routes/storage.go
> -// GetImageRepoFile return the content of an image commit repository path
re added, thanks

2023-08-03 11:36 UTC, adeliaferreira commented on pkg/routes/storage.go
>  // @Failure      400 {object} errors.BadRequest
Yes, added the error on documentation

2023-08-03 16:15 UTC, ldjebran commented on pkg/routes/storage.go
>  // @Router       /storage/update-repos/{updateTransactionID}/content/{repoFilePath} [get]
what error we are returning if updateTransactionID does not exist ?

2023-08-07 08:03 UTC, ldjebran approved these changes
/lgtm

2023-08-07 16:50 UTC, loadtheaccumulator approved these changes
lgtm

2023-08-07 17:03 UTC, merged