Implement the api doc for create device-groups
RedHatInsights/edge-api pull request #2152
Opened 2023-07-25 17:02 UTC by acosferreira

# Description
In the context of the swaggo lib implement the api doc for thirdpartyrepo endpoints.
FIXES:
THEEDGE-3379
THEEDGE-3386

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-07-25 20:11 UTC, de1987 approved these changes

2023-07-25 20:19 UTC, mgold1234 reviewed
looks good

2023-07-25 20:19 UTC, mgold1234 commented on .gitignore
> +api/
please remove this file from pr

2023-07-25 20:19 UTC, mgold1234 commented on pkg/routes/devicegroups.go
> +// @Param        body	body models.CreateDeviceGroupAPI	true	"request body"
those params are missing:
       parameters:
         - name: sort_by
           in: query
           description: "fields: created_at, name, updated_at. To sort DESC use - before the fields."
           schema:
             type: string
         - name: name
           in: query
           description: "field: filter by name"
           schema:
             type: string
         - name: created_at
           in: query
           description: "field: filter by create date"
           schema:
             type: string
         - name: updated_at
           in: query
           description: "field: filter by update date"
           schema:
             type: string
         - name: limit
           in: query
           description: 'field: return number of groups until limit is reached.'
           schema:
             type: integer
         - name: offset
           in: query
           description: 'field: return number of groups beginning at the offset.'
           schema:
             type: integer

2023-07-25 20:20 UTC, mgold1234 commented
I think its better to squash all commits to one commit

2023-07-25 20:24 UTC, acosferreira commented on pkg/routes/devicegroups.go
> +// @Param        body	body models.CreateDeviceGroupAPI	true	"request body"
@mgold1234 this is the endpoint to post
I dont use this parameters for the create, i believe should be added on the list of groups.
What do you think?

2023-07-25 20:27 UTC, acosferreira commented on .gitignore
> +api/
I've added once we should not submit the changed files after run the make swaggo. 
This will prevent us to submit wrong

2023-07-25 20:36 UTC, de1987 commented on .gitignore
> +api/
@mgold1234 As the `/api` directory should not be committed, I think it makes sense to be here.

2023-07-25 20:59 UTC, loadtheaccumulator requested changes
I just have the question about the Account and OrgID.

2023-07-25 20:59 UTC, loadtheaccumulator commented on .gitignore
> +api/
I'm thinking the .gitignore will work great. We can override it if we need to update the README file.

2023-07-25 20:59 UTC, loadtheaccumulator commented on pkg/routes/devicegroups.go
> +// @Param        body	body models.CreateDeviceGroupAPI	true	"request body"
@mgold1234 it looks like the query in your comment might have been copied from the GET section above this POST. While it's possible to use it in a POST, the query would typically be associated with a GET.

https://github.com/RedHatInsights/edge-api/blob/a2fa0f7fe2e078050f5f05dbd2d8eb474f9e5a18/cmd/spec/path.yaml#L1611-L1638

2023-07-25 20:59 UTC, loadtheaccumulator commented on pkg/models/devicegroups_api.go
> +	OrgID       string `json:"org_id"`
Is Account or OrgID necessary for a consumer of the endpoint?
It's typically provided via header.

2023-07-25 21:21 UTC, acosferreira commented on pkg/models/devicegroups_api.go
> +	OrgID       string `json:"org_id"`
the account and orgId is being exposed in the return of post.
This struct i for the 200 response, should we remove that?

2023-07-25 21:28 UTC, loadtheaccumulator approved these changes

2023-07-25 21:28 UTC, loadtheaccumulator commented on pkg/models/devicegroups_api.go
> +	OrgID       string `json:"org_id"`
awesome. thanks.

2023-07-25 21:29 UTC, loadtheaccumulator requested changes
Please squash the commits.

2023-07-26 12:48 UTC, loadtheaccumulator approved these changes
lgtm

2023-07-26 12:57 UTC, ldjebran approved these changes
/lgtm

2023-07-26 13:16 UTC, merged