Mergify squash
RedHatInsights/edge-api pull request #2158
Opened 2023-07-27 13:47 UTC by ldjebran

# Description
In the context to simplify git logs, and to escape some problems faced when merging a PR with many commits
- configure mergify to squash commit instead of merging
- configure mergify commit message to be the first commit message

do it in 2 commits to test the behavior. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `make pre-commit` to check fmt/vet/lint/test-no-fdo

2023-07-27 16:18 UTC, omaciel approved these changes
/lgtm

2023-07-27 16:27 UTC, ldjebran commented
@Mergifyio refresh

2023-07-27 16:37 UTC, ldjebran commented
@Mergifyio queue edge-api

2023-07-27 16:43 UTC, de1987 requested changes
should it be like I suggested?

2023-07-27 16:43 UTC, de1987 commented on .github/mergify.yml
> +        commit_message_template: "{{ commits[0] }}"
```suggestion
        commit_message_template: {{ commits[0] }}
```
I think should be without quotes

2023-07-27 16:46 UTC, ldjebran commented on .github/mergify.yml
> +        commit_message_template: "{{ commits[0] }}"
it does not work wihout quotes

2023-07-27 16:58 UTC, de1987 approved these changes

2023-07-27 17:47 UTC, acosferreira approved these changes
lgtm

2023-07-27 18:20 UTC, loadtheaccumulator commented
@mergify watcha waitin' for?

2023-07-31 08:52 UTC, lahavyuv86 approved these changes
lgtm

2023-07-31 08:55 UTC, merged