New api endpoint for image-sets
RedHatInsights/edge-api pull request #218
Opened 2021-08-31 11:11 UTC by Saurabh-Thakre

Signed-off-by: Saurabh Thakre sthakre@redhat.com

2021-09-01 21:06 UTC, biancarosa commented on pkg/routes/imagesets.go
> +	countResult := imageFilters(r, db.DB.Model(&models.Image{})).Where("images.parent_id is ?", image.ParentId).Count(&count)
Did you test those filters....? It sounds like things will get tricker with filters and image sets. If it doesn't work, I'd rather leave them out of the equation and come up with them in a second pull-request (after double-checking if we want the same filtering capabilities)

2021-09-01 21:06 UTC, biancarosa commented on pkg/services/imagesets.go
> +	imageBuilder imagebuilder.ClientInterface
I don't think we need imageBuilder as a dependency in this service.

2021-09-01 21:07 UTC, biancarosa requested changes
Couple of comments there, and we can add tests, what do you say?

2021-09-01 22:16 UTC, acosferreira commented on pkg/routes/imagesets.go
> +	countResult := imageFilters(r, db.DB.Model(&models.Image{})).Where("images.parent_id is ?", image.ParentId).Count(&count)
I think we can use the relationship between images and imageSet.

2021-09-01 22:18 UTC, acosferreira commented on pkg/services/imagesets.go
> +	imageBuilder imagebuilder.ClientInterface
Agreed with @biancarosa 
the imagebuilder will continue be handled on image creation. The imageSet is a kind of "images' aggregation"

2021-09-02 05:46 UTC, Saurabh-Thakre commented on pkg/routes/imagesets.go
> +	countResult := imageFilters(r, db.DB.Model(&models.Image{})).Where("images.parent_id is ?", image.ParentId).Count(&count)
I've tested those and it gives exact results for images with NULL ParentID and count of that. But I'd be happy to clean those and will put it another PR. It could get tricky at some point.

2021-09-02 05:50 UTC, Saurabh-Thakre commented on pkg/routes/imagesets.go
> +	countResult := imageFilters(r, db.DB.Model(&models.Image{})).Where("images.parent_id is ?", image.ParentId).Count(&count)
yeah, do we already have the relationship between those in place?

2021-09-02 05:56 UTC, Saurabh-Thakre commented on pkg/routes/imagesets.go
> +func GetAllImageSets(w http.ResponseWriter, r *http.Request) {
I liked the thought

![nasa-nasagif-nasahistory-eft1-238gVegOCUAYlR7jOR](https://media2.giphy.com/media/238gVegOCUAYlR7jOR/giphy.gif)

2021-09-02 13:50 UTC, Saurabh-Thakre commented on pkg/routes/imagesets.go
> +	countResult := imageFilters(r, db.DB.Model(&models.Image{})).Where("images.parent_id is ?", image.ParentId).Count(&count)
I think we will once your PR gets merged

2021-09-02 14:15 UTC, Saurabh-Thakre commented
> Couple of comments there, and we can add tests, what do you say?

Yeah, sounds good.

2021-09-06 06:28 UTC, Saurabh-Thakre commented
/retest

2021-09-08 19:31 UTC, biancarosa approved these changes
This is amazing! GJ! :)

2021-09-09 12:42 UTC, merged