add error description and ID to image api
RedHatInsights/edge-api pull request #2181
Opened 2023-08-13 10:13 UTC by mgold1234

# Description
add error description and ID to image api 

FIXES: https://issues.redhat.com/browse/THEEDGE-3347
https://issues.redhat.com/browse/THEEDGE-3381
https://issues.redhat.com/browse/THEEDGE-3401

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-08-13 22:45 UTC, loadtheaccumulator requested changes
I just have a handful of suggestions/changes. Otherwise, looks good.

2023-08-13 22:45 UTC, loadtheaccumulator commented on pkg/models/images_api.go
> +	SSHKey   string `json:"sshkey" example:"ssh-rsa lksjdkjkjsdlkjjds"` // SSh key of installer
typo /Ssh/SSH/

2023-08-13 22:45 UTC, loadtheaccumulator commented on pkg/models/images_api.go
> +	Username string `json:"username" example:"myuser"`                  // Username of installer
Suggesting...
// Username of administrative user

2023-08-13 22:45 UTC, loadtheaccumulator commented on pkg/models/images_api.go
> +	CustomPackages []CustomPackagesAPI `json:"customPackages" example:"Name:'customPackage'"`  // An optional list of custom repositories
This is probably a good time to correct the original cut/paste error :-)
// An optional list of custom packages

This is also of type []CustomePackagesAPI so the example will need to be a list.

2023-08-13 22:45 UTC, loadtheaccumulator commented on pkg/models/images_api.go
> -	Packages               []PackagesAPI        `json:"packages"`
CreateImage() loops through the Packages list, so the Packages line is needed.
https://github.com/loadtheaccumulator/edge-api/blob/e8f8d8b366a46e206ff7308e9b0338fb18b74baa/pkg/services/images.go#L315

2023-08-14 13:33 UTC, mgold1234 commented on pkg/models/images_api.go
> +	Username string `json:"username" example:"myuser"`                  // Username of installer
changed, thank you

2023-08-14 16:40 UTC, loadtheaccumulator approved these changes
lgtm

2023-08-15 12:10 UTC, acosferreira approved these changes
lgtm

2023-08-15 12:11 UTC, merged