Improve upload speed
RedHatInsights/edge-api pull request #219
Opened 2021-08-31 17:47 UTC by AaronH88

Created a pool of workers to upload files and improve the speed of uploading files. Jira ticket THEEDGE-973

Everything works locally, will need to calibrate the number of workers in stage.

2021-09-01 13:41 UTC, biancarosa requested changes
@AaronH88 awesome work, minor comments, other than that we're good!

2021-09-01 13:41 UTC, biancarosa commented on pkg/services/files/uploader.go
> +type filePathVar struct {
Thinking about code readability, can we rename this? I thought about repoSettings, localRepo, repoToUpload, a bunch of things that I'm not particularly happy either but at least it's clearer 😬  @maxamillion @acosferreira @loadtheaccumulator if you have better ideas that's the time

2021-09-01 13:41 UTC, biancarosa commented on pkg/services/files/uploader.go
> +		_, err := u.UploadFile(fname, uploadDest)
```suggestion
		_, err := u.UploadFile(p.filename, p.uploadDest)
```

Or just pass p right away, but that's a major refactor

2021-09-01 13:41 UTC, biancarosa commented on pkg/services/files/uploader.go
> +	var workWg sync.WaitGroup
workWg could also be something easier to read 😬 is this wait group used for files?

2021-09-01 14:21 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +type filePathVar struct {
How about "uploadDetails" ?

2021-09-01 14:30 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +	var workWg sync.WaitGroup
Yeah, and its a unique group for the provided repo,
perhaps "repoWaitGroup" ?

2021-09-01 15:30 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +func worker() {
Rename to uploadWorkers() ??

2021-09-01 20:09 UTC, biancarosa approved these changes
Most of my comments were regarding readability and I feel like they've been addressed, I'm good with this and I think it'll be an amazing improvement!

2021-09-01 20:10 UTC, biancarosa commented on pkg/services/files/uploader.go
> +func worker() {
nah, in this case maybe we don't need to worry too much, it's pretty clear to me

2021-09-02 10:36 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +	var workWg sync.WaitGroup
Changed to repoWaitGroup

2021-09-02 10:37 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +		_, err := u.UploadFile(fname, uploadDest)
I agree that P is a major refactor, however I changed this fucntion call to use the "p." notation you suggested

2021-09-02 14:43 UTC, merged