fix: concurrency stuff on upload repo
RedHatInsights/edge-api pull request #231
Opened 2021-09-02 22:42 UTC by biancarosa

2021-09-02 22:45 UTC, maxamillion approved these changes

2021-09-03 10:47 UTC, AaronH88 requested changes
I think the bool "workersCreated" needs to be removed, and some small var name changes.

Apart from that, it looks good to me :smile:

2021-09-03 10:47 UTC, AaronH88 commented on pkg/services/files/uploader.go
>  		workersCreated = true
Have you testing this locally?
I think this bool will prevent more than one repo to be uploaded, have you tried creating two or three upload requests?

This whole func can be removed, and creating 100 workers can fall back into the UploadRepo() func

2021-09-03 10:47 UTC, AaronH88 commented on pkg/services/files/uploader.go
>  var workersCreated = false
I think this bool is no longer needed

2021-09-03 10:47 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +	for i, u := range uploadDetailsList {
"u" is already defined in this function, can we rename this var please? I got confused for a min wondering why we are looking for "uploader"

2021-09-03 10:47 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +	for i, u := range uploadDetailsList {
Do we want to do some sort of conditional to ensure that i is equal to count (-1) at the end of this loop?

2021-09-03 12:56 UTC, biancarosa commented on pkg/services/files/uploader.go
>  		workersCreated = true
I tested but just with one request. I can see how the bool will be a problem and I'm removing it :)

2021-09-03 13:03 UTC, AaronH88 commented on pkg/services/files/uploader.go
> +	numberOfWorkers := cfg.UploadWorkers
NICE!

2021-09-03 13:05 UTC, AaronH88 commented
Looks good to me, lets give it a go and see what happens

2021-09-03 13:06 UTC, AaronH88 approved these changes
Great!

2021-09-03 13:07 UTC, biancarosa commented
I'm thinking IQE is not happy with some latest changes so I'm gonna merge this and see what happens.

2021-09-03 13:07 UTC, merged