Theedge 3815 notavailable
RedHatInsights/edge-api pull request #2381
Opened 2024-01-23 00:34 UTC by acosferreira

# Description
When edgeparity enable and no enforce group, we should return unauthorized feature

FIXES: THEEDGE-3815

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2024-01-23 08:16 UTC, ldjebran commented on pkg/routes/devicegroups.go
> +	if feature.EdgeParityInventoryGroupsEnabled.IsEnabled() && !feature.EnforceEdgeGroups.IsEnabled() {
feature.EnforceEdgeGroups.IsEnabled() is always enabled but using utility.EnforceEdgeGroups(orgID) will depend from orgid,  if orgid is in the list it's enabled if not it will disabled
```suggestion
	if feature.EdgeParityInventoryGroupsEnabled.IsEnabled() && !utility.EnforceEdgeGroups(orgID) {
```

Please update all similar conditions with this suggestion

2024-01-23 23:25 UTC, omaciel reviewed
I think it's worth considering creating an utility function instead of replicating the same code block multiple times.

2024-01-23 23:25 UTC, omaciel commented on pkg/routes/devicegroups.go
> +	orgID := readOrgID(w, r, ctxServices.Log)
This whole block is repeated multiple times, so much so that perhaps it would be worthwhile moving it to its own function under utilities. Thoughts?

2024-01-24 15:06 UTC, omaciel commented on pkg/routes/devicegroups.go
> +	orgID := readOrgID(w, r, ctxServices.Log)
To be more precise, I'm referring to the code block between getting the orgID and checking the feature flag and "special" organizations.

2024-01-30 21:27 UTC, de1987 submitted a review, later dismissed

2024-01-30 22:06 UTC, omaciel reviewed
Please look at comments and consider adding a test scenario where we have set an organization to `EnforceEdgeGroups` to ensure that the organization is able to perform the actions even when the `EdgeParityInventoryGroupsEnabled` is set to `True`.

2024-01-30 22:06 UTC, omaciel commented on pkg/routes/devicegroups_test.go
> +				// rr := httptest.NewRecorder()
Remove comments

2024-01-30 22:06 UTC, omaciel commented on pkg/routes/devicegroups_test.go
> +				// rr := httptest.NewRecorder()
Remove comments

2024-01-30 22:06 UTC, omaciel commented on pkg/routes/devicegroups_test.go
> +				// rr := httptest.NewRecorder()
Remove comments

2024-01-31 00:44 UTC, omaciel requested changes
You left some "debug" lines of code :)

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> +	fmt.Print("&&&&&&&&&&&&&&&&&")
Remove this line :)

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> +		fmt.Print("\n if \n")
Remove this line :)

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> +		fmt.Print("\n else \n")
Remove this line :)

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> +			fmt.Printf("\n err: %v \n", err)
Remove this line or log it? :)

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> -
Any reason for deleting the blank line?

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> -
Any reason for deleting the empty line?

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
>  	if orgID == "" {
So you still need to validate the orgID? I thought you said it would be done by the route itself...

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> -
Removing the empty line?

2024-01-31 00:44 UTC, omaciel commented on pkg/routes/devicegroups.go
> +	if orgID == "" {
Same comment about the discussion around needing to validate orgID.

2024-01-31 10:23 UTC, ldjebran commented on pkg/routes/devicegroups.go
>  	if orgID == "" {
I think that if there is any chance that orgID maybe empty we have to do the check especially when the function is a public function.

2024-01-31 10:37 UTC, ldjebran commented on pkg/routes/devicegroups_test.go
> +				_ = os.Unsetenv(feature.EnforceEdgeGroups.EnvVar)
prefer to check any error that may occur by adding in all skipped error checking 
```go
err := os.Unsetenv(feature.EnforceEdgeGroups.EnvVar)
Expect(err).ToNot(HaveOccurred())	
```

2024-01-31 10:42 UTC, ldjebran commented on pkg/routes/devicegroups_test.go
> +			It("should return Success on create Device", func() {
"should return Success on create Device when Edge Groups enforced"

2024-01-31 12:22 UTC, ldjebran commented on pkg/routes/devicegroups_test.go
> +			It("should return hide group:true NotAuthorized", func() {
"should return NotAuthorized hide group:true"

2024-01-31 16:31 UTC, ldjebran approved these changes
/lgtm

2024-01-31 17:05 UTC, omaciel approved these changes
/lgtm

2024-01-31 17:40 UTC, merged