refactor: job queue for more go routines
RedHatInsights/edge-api pull request #2563
Opened 2024-05-21 14:27 UTC by lzap

This refactors more unmanaged goroutines into the newly introduced job queue.

I am struggling with the gomock thing, I am unable to figure out, what this thing is trying to tell me. All it prints is this:

```
Summarizing 1 Failure:

[Fail] Images Route Tests Routes [AfterEach] CreateInstallerForImage should create installer successfully 
/home/lzap/edge-api/pkg/routes/images_test.go:1053

Ran 199 of 199 Specs in 0.060 seconds
FAIL! -- 198 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestRoutes (0.11s)
FAIL
FAIL    github.com/redhatinsights/edge-api/pkg/routes   0.164s
```

2024-05-22 08:01 UTC, lzap commented on pkg/jobs/job.go
> +
Some jobs do not need failure handler, so this noop function is used instead.

2024-05-22 08:02 UTC, lzap commented on pkg/jobs/memory.go
> +
Statistics are now a separate goroutine.

2024-05-22 08:03 UTC, lzap commented on pkg/routes/images_test.go
Since `CreateInstallerForImage` was introduced in the image interface and it is called from separate goroutine, this is needed in the mock.

2024-05-22 08:04 UTC, lzap commented on pkg/services/images.go
> +	ProcessInstaller(ctx context.Context, image *models.Image) error
The `CreateInstallerForImage` method was split into two, the `ProcessInstaller` is called asynchronously from some callsites.

2024-05-22 08:04 UTC, lzap commented on pkg/services/images.go
> +			}
The channel as a return value was a reason to split this. This was not good Go code at all.

2024-05-22 08:06 UTC, lzap commented on pkg/services/updates.go
> +	}(ctx, s.log, staticDelta.State)
This wait code could possibly loop forever, added timeout and cancel.

2024-05-22 08:07 UTC, lzap commented
Squash on merge.

2024-05-24 02:20 UTC, loadtheaccumulator requested changes
Thanks for diving in on that! I made a suggestion or two. Another overall suggestion is separate the jobqueue feature flag into a feature flag per major function (e.g., images, device/update, etc) if submitting changes to multiple features in a single PR. And maybe splitting the infinite loop code changes into a separate PR so they can be tested (and reverted/fixed) independently without getting mixed in with the original purpose of the PR.

2024-05-27 10:18 UTC, lzap commented on pkg/jobs/memory.go
> +	logrus.WithContext(ctx).Infof("Starting %d fast job workers", w.cfg.FastWorkers)
That is a great approach in general and why I believe this can be a dogma for error messages (because of sentry/glitchtip), I believe for info/debug messages the rule can be loosened a bit. Here I see no value in providing the "N" number in a separate field.

2024-05-27 10:21 UTC, lzap commented on pkg/services/updates.go
> +				edgelog.Error("timeout waiting for static delta to be ready")
Yeah adding.

2024-05-30 03:47 UTC, loadtheaccumulator commented
I'm sure https://github.com/RedHatInsights/edge-api/pull/2576 probably broke this one with removing static delta all together.

2024-05-30 11:54 UTC, lzap commented on pkg/jobs/job.go
> +
Yeah used AI to generate one.

2024-05-30 11:55 UTC, lzap commented on pkg/jobs/memory.go
> +	logrus.WithContext(ctx).Infof("Starting %d fast job workers", w.cfg.FastWorkers)
The rule of thumb in my books is that I want a separate field if I need to search or filter records in a log system like Kibana.

2024-05-30 11:56 UTC, lzap commented on pkg/jobs/memory.go
> +	}
There are two queues now, fast is used for quick jobs.

2024-05-30 11:58 UTC, lzap commented
Rebased Ready for re-review.

2024-05-31 01:48 UTC, loadtheaccumulator approved these changes

2024-05-31 07:52 UTC, lzap commented
Feel free to merge **after** we confirm prod is stable. This patch might break things. TY!

2024-06-06 03:01 UTC, merged