feat: add pulp client
RedHatInsights/edge-api pull request #2570
Opened 2024-05-27 17:51 UTC by lzap

Adds a pulp client and generation make target. I selected tags randomly, I will rebase once I finish with testing.

2024-06-25 14:28 UTC, avitova reviewed
Wow, so this is really a complex PR. I left just some nitpicks, no need to follow the comments, only if you feel like it. :)

2024-06-25 14:28 UTC, avitova commented on pkg/clients/identity.go
> +func currentToken(ctx context.Context, issuerUrl, clientId, clientSecret string) (string, error) {
The linter is right here, so we might want to be consistent with [this](https://go.dev/wiki/CodeReviewComments#initialisms). I am actually surprised that this got noticed by the linter!

2024-06-25 14:28 UTC, avitova commented on cmd/pulpcli/main.go
> +	//logrus.SetLevel(logrus.InfoLevel)
Is there a reason for this comment being here?

2024-06-25 14:28 UTC, avitova commented on pkg/clients/pulp/service.go
> +func (ps *PulpService) Domain() string {
You use ps only here. On all other places including domain.go, you use "c" as a receiver name. We should probably make this the same everywhere. You also use "c" in distribution.go and content_guards.go, and artifacts.go. :thinking:

2024-06-26 03:24 UTC, loadtheaccumulator requested changes
I had a couple of questions out of curiosity and then mostly receiver parm naming and whether or not things can/should/shouldn't be generated in the container/Dockerfile instead of pushed with the PR.

Thank you for this PR!!!

2024-06-26 03:24 UTC, loadtheaccumulator commented on cmd/pulpcli/main.go
Thank you for the cli!

2024-06-26 03:24 UTC, loadtheaccumulator commented on config/config.go
> -	if options.GetBool("Debug") {
Is this change related to this PR?

2024-06-26 03:24 UTC, loadtheaccumulator commented on config/config.go
> +		// S3: Tarball bucket
Is this necessary for this PR?

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/artifacts.go
> +func (c *PulpService) ArtifactsCreatePipe(ctx context.Context, filename string) (*ArtifactResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/artifacts.go
> +func (c *PulpService) ArtifactsCreate(ctx context.Context, filename string) (*ArtifactResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/artifacts.go
> +func (c *PulpService) ArtifactsRead(ctx context.Context, id uuid.UUID) (*ArtifactResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/artifacts.go
> +func (c *PulpService) ArtifactsList(ctx context.Context, sha256 string) ([]ArtifactResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/platform_client.go
> +func (c *LoggingDoer) Do(req *http.Request) (*http.Response, error) {
Prefer ld or d instead of c for the receiver var.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/platform_client.go
> +func (c *MetricsDoer) Do(req *http.Request) (*http.Response, error) {
Prefer md or d instead of c for the receiver var.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardCreate(ctx context.Context, jq, orgID string) (*HeaderContentGuardResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardRead(ctx context.Context, id uuid.UUID) (*HeaderContentGuardResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardReadByOrgID(ctx context.Context, orgID string) (*HeaderContentGuardResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardReadOrCreate(ctx context.Context, jq, orgID string) (*HeaderContentGuardResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardDelete(ctx context.Context, id uuid.UUID) error {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/content_guards.go
> +func (c *PulpService) HeaderGuardList(ctx context.Context, nameFilter string) ([]HeaderContentGuardResponse, error) {
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/distributions.go
> +func (c *PulpService) DistributionsCreate(ctx context.Context, name, basePath, repoHref, contentGuard string) (*OstreeOstreeDistributionResponse, error) {
Same with this file..
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/domains.go
> +func (c *PulpService) DomainsCreate(ctx context.Context, domain string) (*DomainResponse, error) {
Same with this file.
Prefer ps for the receiver parm.

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/pulp_client.gen.go
Can/should this be gen'd at container build time?

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/pulp_openapi.json
Can/should this be pull'd at container build time versus uploaded with PR?

2024-06-26 03:24 UTC, loadtheaccumulator commented on pkg/clients/pulp/repositories.go
> +func (c *PulpService) RepositoriesCreate(ctx context.Context, name string) (*OstreeOstreeRepositoryResponse, error) {
Same with this file...
Prefer ps for the receiver parm.

2024-06-26 12:11 UTC, lzap commented on pkg/clients/pulp/service.go
> +		}
Good points, you know what I like switch in this case.

2024-06-26 12:12 UTC, lzap commented on pkg/clients/pulp/service.go
> +func (ps *PulpService) Domain() string {
Sure, I do not mind.

2024-06-26 12:13 UTC, lzap commented on cmd/pulpcli/main.go
> +	//logrus.SetLevel(logrus.InfoLevel)
Not really, no.

2024-06-26 12:14 UTC, lzap commented on pkg/clients/pulp/artifacts.go
> +func (c *PulpService) ArtifactsRead(ctx context.Context, id uuid.UUID) (*ArtifactResponse, error) {
Sure.

2024-06-26 12:19 UTC, lzap commented on Makefile
> +	perl -i -pe 'BEGIN{undef $$/;} s/"additionalProperties": {\s*"type": "object"\s*}/"additionalProperties": true/g' pkg/clients/pulp/pulp_openapi.json
Added a comment with link to the bug: https://github.com/oapi-codegen/oapi-codegen/issues/243

2024-06-26 12:23 UTC, lzap commented on config/config.go
> +		// S3: Tarball bucket
This hunk I believe so, it is just a git diff shenanigan, I am only adding a comment, keeping the existing code and adding new code. The only update of existing code is instead nil error in case bucket is not set in clowder it panics with more appropriate message.

2024-06-26 12:26 UTC, lzap commented on pkg/clients/pulp/pulp_client.gen.go
Technically yes, but that would be clunky - your code would be not in state where it could be compiled with `go build`. This would break most people's IDEs. This is a good practice in Go project and it is actually what Go library does as well: https://go.dev/blog/generate

2024-06-26 12:31 UTC, lzap commented
Incorporated all comments, marked those as resolved. Left few comments opened for further discussion.

There is something left to do but I would rather prefer doing it in a separate PR if possible (might not finish today):

* A call to create IB content guard.
* A call to create composite content guard (orgID + IB).
* An update call for the same (when IB CN/DN changes or header is updated we want to update all content guards transparently).

2024-06-26 14:28 UTC, lzap commented
Oh initialization problem, wrong pointer checking, corrected:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1010e]

goroutine 1 [running]:
github.com/redhatinsights/edge-api/config.CreateEdgeAPIConfig()
	/src/github.com/RedHatInsights/edge-api/config/config.go:366 +0x2c4e
github.com/redhatinsights/edge-api/config.Get()
	/src/github.com/RedHatInsights/edge-api/config/config.go:446 +0x94
github.com/redhatinsights/edge-api/config.Init(...)
	/src/github.com/RedHatInsights/edge-api/config/config.go:436
main.main()
	/src/github.com/RedHatInsights/edge-api/cmd/migrate/main.go:26 +0x45
```

Just a note, the package name `cmd/pulpcli` is probably misleading, I haven’t created a full "CLI", instead, it is just a very simple "integration test". It only works for manual testing for now, but if needed I can add deletion calls and make it so it completely cleans up a full domain after a test so we can automate it. The other option is simply to delete this after we integrate Pulp.

It can only list domains and then create a new repo, this is how you call it:

```
go run cmd/pulpcli fixture_create 12345678 fixtures/small_repo/small_commit1.tar
```

Replace `12345678` with your org ID and the second argument must be an ostree archive repository tarball. I created two small commits, one is initial and the other is child commit based on that. Also the following environment variables are needed (vscode syntax):

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "fixture create",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/pulpcli/main.go",
            "args": [
                "fixture_create", "12345678", "${workspaceFolder}/fixtures/small_repo/small_commit1.tar",
            ],
            "env": {
                "PULPURL": "https://pulp.xxxxxxxxx.devshift.net",
                "PULPUSERNAME": "edge-api-dev",
                "PULPPASSWORD": "XXXXXXXXXXX",
                "PULPIDENTITYNAME": "edge-api-dev",
                "PULPS3BUCKETNAME": "edge-pulp-test",
                "PULPS3REGION": "us-east-1",
                "PULPS3ACCESSKEY": "AAAAAAAAAAAAAAAAAAAA",
                "PULPS3SECRETKEY": "BBBBBBBBBBBBBBBBBBBBB",
                "LOG_LEVEL": "TRACE",
                "DEV": "true",
                "LOCAL": "true"
            }
        }
    ]
}
```

2024-06-26 16:06 UTC, loadtheaccumulator approved these changes
Awesome! Thanks!

2024-06-26 17:07 UTC, merged

2024-06-28 17:09 UTC, ezr-ondrej commented on config/config.go
> -		edgeConfig.SecretKey = *bucket.SecretKey
Why did we do this change? I expect the AccessKey and SecretKey to be used :)

2024-06-28 17:13 UTC, ezr-ondrej commented on config/config.go
> -		edgeConfig.SecretKey = *bucket.SecretKey
It's used in https://github.com/RedHatInsights/edge-api/blob/78de0091b66be739f64b54bb5eddff5e803b600e/pkg/services/files/s3.go#L163

We need to get those lines back in (or fix usages, but this was just one I found, there might be others)

2024-06-28 17:25 UTC, loadtheaccumulator commented on config/config.go
> -		edgeConfig.SecretKey = *bucket.SecretKey
They are covered in the ok above lines 357-361

2024-06-28 17:42 UTC, ezr-ondrej commented on config/config.go
> -		edgeConfig.SecretKey = *bucket.SecretKey
Right, I've missed that! :)