WIP - adding a s3 uploader
RedHatInsights/edge-api pull request #28
Opened 2021-06-03 22:24 UTC by maxamillion

Signed-off-by: Adam Miller <admiller@redhat.com>

2021-06-10 15:17 UTC, jhjaggars requested changes

2021-06-10 15:17 UTC, jhjaggars commented on cmd/migrate/migrate.go
> +	err = db.DB.AutoMigrate(&commits.UpdateRecord{})
This can be combined with the previous AutoMigrate call fyi

2021-06-10 15:17 UTC, jhjaggars commented on pkg/commits/updates.go
> +var UPDATE_TMPPATH = "/tmp/updates/"
Stick this in config somehow, you'll thank me later :)

2021-06-10 15:17 UTC, jhjaggars commented on pkg/commits/uploader.go
> +	s3URL := fmt.Sprintf("https://%s.s3.%s.amazonaws.com/%s/%s", u.Bucket, region, account, strings.TrimPrefix(src, UPDATE_TMPPATH))
I assume this will be the proxy url later, is that the intention?

2021-06-10 15:45 UTC, maxamillion commented on pkg/commits/uploader.go
> +	s3URL := fmt.Sprintf("https://%s.s3.%s.amazonaws.com/%s/%s", u.Bucket, region, account, strings.TrimPrefix(src, UPDATE_TMPPATH))
Yes, definitely .... I wanted to talk to you about how we were going to glue those bits together but for the time being I wanted to have an entry and some information about what was uploaded and where it went.

2021-06-10 18:28 UTC, chambridge commented on config/config.go
> +	AccessKey      string
or maybe `objectstorage` since it should be able to be s3-compliant.

2021-06-10 18:32 UTC, chambridge commented
Certainly not required and not new to this PR, but would suggest the S3 interaction using the `minio` [golang client](https://docs.min.io/docs/golang-client-quickstart-guide.html) instead of the AWS SDK. If we ever want IVT test to run as part of the pr_check we would need this.

2021-06-11 11:39 UTC, jhjaggars commented on pkg/commits/updates.go
> +	if !(update.UpdateCommitID > 0) {
`if update.UpdateCommitID <= 0`?

2021-06-11 16:54 UTC, maxamillion commented on test_vpn.sh
> +#!/bin/bash
it was not

2021-06-11 16:56 UTC, maxamillion commented on config/config.go
> +	AccessKey      string
I didn't add those, they're included in my changelog because gofmt automatically shifted the spacing when I added `UpdateTempPath`.

2021-06-11 18:49 UTC, jhjaggars commented on config/config.go
> +	AccessKey      string
Let's clean this up in a later PR.

2021-06-11 18:59 UTC, maxamillion commented
> Certainly not required and not new to this PR, but would suggest the S3 interaction using the `minio` [golang client](https://docs.min.io/docs/golang-client-quickstart-guide.html) instead of the AWS SDK. If we ever want IVT test to run as part of the pr_check we would need this.

That sounds perfectly fine to me, I'd like to do that in a follow-up PR though.

2021-06-11 19:01 UTC, merged