Read from playbook-dispatcher's Kafka topic and logs the message
RedHatInsights/edge-api pull request #335
Opened 2021-11-01 15:28 UTC by biancarosa

2021-11-01 19:36 UTC, loadtheaccumulator commented on pkg/services/consumers.go
> +	"github.com/segmentio/kafka-go"
Curious on reasoning for going with segmentio vs the github.com/confluentinc/confluent-kafka-go package?

2021-11-01 19:49 UTC, biancarosa commented on pkg/services/consumers.go
> +	"github.com/segmentio/kafka-go"
No particular preference. Went for the first search, has 4k stars and looked safe, and by accident ended up finding more code at Red Hat using the same lib. Apparently we have other people using sarama, too, but didn't even knew about confluent-kafka-go. Any arguments in favor of it instead of kafka-go? Happy to change.

2021-11-01 19:52 UTC, biancarosa commented on pkg/services/consumers.go
> +	"github.com/segmentio/kafka-go"
No particular reason. Found in my first search, tried and liked and it worked, and found some red hat services using it and sarama too.

Any reasons why I should change? I'm happy to change if needed.

2021-11-03 02:05 UTC, loadtheaccumulator commented on pkg/services/consumers.go
> +	"github.com/segmentio/kafka-go"
The confluent lib is what I've used, seen other c.rh.c apps use, and the RH managed service leverages in their examples. No reason other than that. I haven't dived into a comparison and was curious.

2021-11-03 13:25 UTC, biancarosa commented
/retest

2021-11-03 15:34 UTC, thom-at-redhat commented on pkg/services/consumers.go
> +	"github.com/segmentio/kafka-go"
/lgtm

2021-11-03 15:40 UTC, loadtheaccumulator requested changes
Dropping this here to prompt a quick discussion.

2021-11-03 15:40 UTC, loadtheaccumulator commented on pkg/services/consumers.go
> +		GroupID: "edge-fleet-management",
We'll need to discuss groupid's as we consume for various functions. It might be useful to make it more specific now.

2021-11-03 15:43 UTC, biancarosa commented on pkg/services/consumers.go
> +		GroupID: "edge-fleet-management",
makes sense. let's add that discussion to event based meeting or arch meeting?

2021-11-03 20:36 UTC, loadtheaccumulator approved these changes

2021-11-03 20:37 UTC, loadtheaccumulator commented
/retest

2021-11-03 20:49 UTC, maxamillion approved these changes

2021-11-03 22:03 UTC, maxamillion commented
/retest

2021-11-03 22:16 UTC, merged