Poc/inventory endpoint
RedHatInsights/edge-api pull request #347
Opened 2021-11-05 22:50 UTC by acosferreira

2021-11-08 14:11 UTC, biancarosa commented on main.go
> +		s.Route("/inventory", routes.MakeInventoryRouter)
Can't we have this under our current devices route rather than creating a new one?

2021-11-08 19:47 UTC, biancarosa commented on pkg/clients/inventory/client.go
> +	UpdateAvailable bool
Can we keep the camel_case contract and add a `update_available` json tag here?

2021-11-08 19:51 UTC, biancarosa commented on pkg/clients/inventory/client.go
> +	OrderHow     string
This is normally called Sort

2021-11-08 19:51 UTC, biancarosa commented on pkg/clients/inventory/client.go
> +	HostnameOrId string
Identifier, maybe? With a comment saying it can be a Hostname or ID. We can also have the two fields for clarity and one is supposed to be always empty.

2021-11-08 19:51 UTC, biancarosa commented on pkg/routes/devices.go
> +	sub.With(InventoyCtx).Get("/", GetInventory)
Do we need InventoryCtx function? This function is normally for get by id endpoints. If this is for filtering, I suggest keeping on the GetInventory method.

2021-11-08 19:51 UTC, biancarosa commented on pkg/clients/inventory/client.go
> +	OrderHow     string
I just saw that Inventory uses OrderHow. We can rename it or keep it like that 🤷🏻

2021-11-08 19:59 UTC, acosferreira commented on pkg/routes/devices.go
> +	sub.With(InventoyCtx).Get("/", GetInventory)
we need to build the parameters that we will send to inventory api call

2021-11-08 20:00 UTC, acosferreira commented on pkg/clients/inventory/client.go
> +	HostnameOrId string
I'm using the exactly parameters that we send to inventory api call

2021-11-08 20:01 UTC, acosferreira commented on pkg/clients/inventory/client.go
> +	UpdateAvailable bool
this is the response that we are re-building to FE add the info with intentory and edgeapi joined

2021-11-09 13:56 UTC, biancarosa commented on pkg/routes/devices.go
> +	sub.With(InventoyCtx).Get("/", GetInventory)
Can we do that directly on the GetInventory function?

2021-11-11 14:18 UTC, biancarosa reviewed
To sum up, my suggestions are: 
- fix vet comments
- get rid of the InventoryCtx function and get the params straight on GetInventory for a more simpler logic on params retrieval since it's not used by another route

2021-11-16 15:16 UTC, biancarosa requested changes

2021-11-16 15:16 UTC, biancarosa commented on pkg/routes/devices.go
> +		fmt.Printf(":::: Device CTX %v\n ::::", uCtx)
a lost print has been found

2021-11-16 15:16 UTC, biancarosa commented on pkg/routes/inventory.go
> +// MakeDevicesRouter adds support for operations on invetory
comment doesnt match function name

2021-11-16 15:16 UTC, biancarosa commented on pkg/routes/inventory.go
> +// MakeDevicesRouter adds support for operations on invetory
also see github actions comments about for other structs :)

2021-11-16 15:16 UTC, biancarosa commented on pkg/routes/inventory.go
> +	// ctx := r.Context()
can we get rid of the comments?

2021-11-16 16:40 UTC, merged