Create FDO client
RedHatInsights/edge-api pull request #349
Opened 2021-11-08 14:02 UTC by Avielyo10

- Create FDO client
- Move ownership

2021-11-08 18:01 UTC, biancarosa requested changes

2021-11-08 18:01 UTC, biancarosa commented on config/config.go
> +	options.SetDefault("FDOHostURL", "fdo.redhat.com")
Can we set those variables on the clowapp.yaml already to avoid further commits in order to customize it for other environments?

2021-11-09 08:18 UTC, Avielyo10 commented on config/config.go
> +	options.SetDefault("FDOHostURL", "fdo.redhat.com")
Yes, done

2021-11-09 09:16 UTC, Avielyo10 commented
/hold

2021-11-10 09:08 UTC, Avielyo10 commented
@biancarosa Well for now the secret is empty, do you know where `PSK_DISPATCHER` value get received?

2021-11-10 14:47 UTC, thom-at-redhat commented
/lgtm

2021-11-15 15:30 UTC, thom-at-redhat commented
/lgtm

2021-11-15 19:48 UTC, maxamillion approved these changes
LGTM :+1:

2021-11-15 19:58 UTC, merged