Bug fix for 1310, 1200
RedHatInsights/edge-api pull request #353
Opened 2021-11-10 19:34 UTC by Saurabh-Thakre

**Now, PUT response returns the correct value for CreatedAt and UpdatedAt**
```
curl --request PUT --url http://localhost:3000/api/edge/v1/thirdpartyrepo/8/  --data '{                                                      
    "URL": "http://www.hmm.com/in/repo/hmmm",
    "Description": "I will have a nice sleep now",
    "Name": "Sleep time"                                                                                                         
}' | jq

{
  "ID": 8,
  "CreatedAt": "2021-11-10T15:52:33.683344213+05:30",
  "UpdatedAt": "2021-11-11T00:55:14.174617616+05:30",
  "DeletedAt": null,
  "Name": "Sleep time",
  "URL": "http://www.hmm.com/in/repo/hmmm",
  "Description": "I will have a nice sleep now",
  "Account": "0000000"
}

```
**Now, we have a better response for DELETE and GET requests for non-existent and deleted objects**
```
curl --request DELETE --url http://localhost:3000/api/edge/v1/thirdpartyrepo/8/ | jq      
 
"Successfully deleted third party repository with ID 8"

```
```
curl --request GET --url http://localhost:3000/api/edge/v1/thirdpartyrepo/10 | jq    

{
  "Code": "NOT_FOUND",
  "Status": 404,
  "Title": "Third Party Repository is not found"
}

```

2021-11-10 20:40 UTC, omaciel commented on cmd/spec/openapi.json
> +            "description": "Third Party Repository is not found."
s/is/was?

2021-11-10 20:42 UTC, omaciel commented
Change `is` to `was` and perhaps keep the same case for `third party repositories` as you have some written with capital letters and some in lowercase.

2021-11-10 20:50 UTC, biancarosa requested changes
I think that, just for that DELETE method, we could use Unscoped to return the deleted data and return a proper 200 for the operation:

https://gorm.io/docs/delete.html#Soft-Delete

2021-11-11 15:58 UTC, biancarosa approved these changes

2021-11-11 18:32 UTC, merged