Add pagination, sorting and filtering to thirdpartyrepo endpoint
RedHatInsights/edge-api pull request #362
Opened 2021-11-16 10:49 UTC by Saurabh-Thakre

2021-11-17 16:23 UTC, Saurabh-Thakre commented
Adding docs in some time

2021-11-17 17:22 UTC, biancarosa requested changes

2021-11-17 17:22 UTC, biancarosa commented on pkg/routes/thirdpartyrepo.go
> +			http.Error(w, err.Error(), http.StatusBadRequest)
Can we use the errors.NewBadRequest() wrapper to return in the correct API contract?

2021-11-17 17:22 UTC, biancarosa commented on pkg/routes/thirdpartyrepo.go
> +		http.Error(w, "this is not a valid filter. filter must be in name.parameter", http.StatusInternalServerError)
Can we use the errors.NewBadRequest() wrapper to return in the correct API contract? And not use fmt.Println?

2021-11-18 11:11 UTC, biancarosa approved these changes
LGTM

2021-11-18 11:19 UTC, merged