Bug fixes
RedHatInsights/edge-api pull request #368
Opened 2021-11-18 10:31 UTC by Saurabh-Thakre

Fixed :
- missing the ID in response, when creating a third party repository. fix to return correct value of created_at and updated_at
- fixing third party duplicate name issues

**Before :**

> curl --request POST --url http://localhost:3000/api/edge/v1/thirdpartyrepo/  --data '{                                                     
    "URL": "http://www.hmm.mmh/in/repo/hmmm",
    "Description": "hmm mmh hmm mmh",
    "Name": "X"                                                                                                         
}' | jq
{
  "CreatedAt": "0001-01-01T00:00:00Z",
  "UpdatedAt": "0001-01-01T00:00:00Z",
  "DeletedAt": null,
  "Name": "X",
  "URL": "http://www.hmm.mmh/in/repo/hmmm",
  "Description": "hmm mmh hmm mmh",
  "Account": ""
}

**After :** 

> curl --request POST --url http://localhost:3000/api/edge/v1/thirdpartyrepo/  --data '{                                                     
    "URL": "http://www.hmm.mmh/in/repo/hmmm",
    "Description": "hmm mmh hmm mmh",
    "Name": "XX"                                                                                                         
}' | jq
{
  "ID": 38,
  "CreatedAt": "2021-11-18T15:59:31.067563425+05:30",
  "UpdatedAt": "2021-11-18T15:59:31.067563425+05:30",
  "DeletedAt": null,
  "Name": "XX",
  "URL": "http://www.hmm.mmh/in/repo/hmmm",
  "Description": "hmm mmh hmm mmh",
  "Account": "0000000"
}

2021-11-18 11:13 UTC, biancarosa requested changes

2021-11-18 11:13 UTC, biancarosa commented on pkg/routes/thirdpartyrepo.go
> +		errors.NewInternalServerError()
Will this return the error? I think it just creates the variable, but doesn't change the response code or body

2021-11-18 11:15 UTC, biancarosa commented on pkg/services/thirdpartyrepo.go
> +			return errors.NewBadRequest("third party repository with already exists with same")
Can't we achieve this with some sort of unique index on the database? Check if GORM has some json tag for uniqueness, and then the db.Create should fail without any further logic

2021-11-18 11:23 UTC, Saurabh-Thakre commented on pkg/services/thirdpartyrepo.go
> +			return errors.NewBadRequest("third party repository with already exists with same")
I've to look if GORM has something for us. I'll see if I can find anything

2021-11-18 11:38 UTC, Saurabh-Thakre commented on pkg/routes/thirdpartyrepo.go
> +		errors.NewInternalServerError()
yeah actually the result doesn't return error.

2021-11-18 12:45 UTC, omaciel commented
Do we need a DeletedAt field?

2021-11-18 13:17 UTC, Saurabh-Thakre commented
> Do we need a DeletedAt field?

Good question, it comes from the Model struct, so we have it in all our endpoints. So when we delete an object, say a third party repo, we get a response with the DeletedAt field updated saying you've deleted this now at this time.

2021-11-18 13:24 UTC, biancarosa requested changes
Just realized what's going on there!

Suggestion is to make the method CreateThirdPartyRepo return the newly saved tprepo object and an error instead of just an error, in that case that query to retrieve the value is not necessary on the route.

2021-11-23 09:42 UTC, Avielyo10 commented
@Mergifyio refresh

2021-11-23 10:17 UTC, Avielyo10 commented
@Mergifyio refresh

2021-11-23 11:33 UTC, Avielyo10 commented
@Mergifyio refresh

2021-11-24 13:50 UTC, Saurabh-Thakre commented on pkg/routes/thirdpartyrepo.go
> +		errors.NewInternalServerError()
> Just realized what's going on there!
> 
> Suggestion is to make the method CreateThirdPartyRepo return the newly saved tprepo object and an error instead of just an error, in that case that query to retrieve the value is not necessary on the route.

![](https://media0.giphy.com/media/2OHYMJGnGoiVjVg55P/giphy.gif)

Your suggestion was perfect, and its done now :)

2021-11-24 14:10 UTC, Avielyo10 requested changes

2021-11-24 14:10 UTC, Avielyo10 commented on pkg/routes/thirdpartyrepo.go
> +	s, _ := r.Context().Value(dependencies.Key).(*dependencies.EdgeAPIServices)
I don't see a reason for not being explicit

2021-11-24 14:10 UTC, Avielyo10 commented on pkg/routes/thirdpartyrepo.go
> +	tprepo, err = s.ThirdPartyRepoService.CreateThirdPartyRepo(tprepo, account)
Can we change it to something readable like `thirdPartyRepo`?or at least `tpRepo` as Golang camel case notation?

2021-11-24 14:15 UTC, Avielyo10 commented on pkg/routes/main_test.go
> +	tprepo    models.ThirdPartyRepo
I don't see were this been used at the test

2021-11-24 14:29 UTC, Saurabh-Thakre commented on pkg/routes/main_test.go
> +	tprepo    models.ThirdPartyRepo
`mockThirdPartyRepoService.EXPECT().CreateThirdPartyRepo(gomock.Any(), gomock.Any()).Return(&tprepo, nil)`

This is getting used here :) @Avielyo10

2021-11-24 14:35 UTC, Saurabh-Thakre commented on pkg/routes/thirdpartyrepo.go
> +	tprepo, err = s.ThirdPartyRepoService.CreateThirdPartyRepo(tprepo, account)
thirdPartyRepo, sure I can make that happen o/

2021-11-24 14:41 UTC, Avielyo10 commented on pkg/routes/main_test.go
> +	tprepo    models.ThirdPartyRepo
Does this teats your fix?

2021-11-24 14:45 UTC, Saurabh-Thakre commented on pkg/routes/main_test.go
> +	tprepo    models.ThirdPartyRepo
yeah kinda, I had to modify services to return 2 values so yeah :)

2021-11-24 14:51 UTC, Avielyo10 commented on pkg/services/thirdpartyrepo.go
>  		tprepo = &models.ThirdPartyRepo{
ditto

2021-11-24 14:51 UTC, Avielyo10 commented on pkg/services/thirdpartyrepo.go
> +	return tprepo, nil
ditto

2021-11-24 15:04 UTC, Saurabh-Thakre commented on pkg/services/thirdpartyrepo.go
>  		tprepo = &models.ThirdPartyRepo{
cool , but then other functions will look different having tprepo haha. I will open new PR for those as well, tprepo is all around this endpoint

2021-11-24 17:27 UTC, biancarosa approved these changes
LGTM

2021-11-25 07:49 UTC, Avielyo10 approved these changes
lgtm

2021-11-25 07:50 UTC, merged