WIP - Add tests to commit class
RedHatInsights/edge-api pull request #37
Opened 2021-06-09 23:06 UTC by acosferreira

2021-06-10 17:16 UTC, chambridge requested changes
Some potential opportunities for code reuse and test structuring.
As well as suggestions for output testing to be certain we are returning valid JSON.

2021-06-10 17:16 UTC, chambridge commented on pkg/commits/commits_test.go
> +	}
I would pull this out into a common function that the test could use instead of it being copied an pasted into each test case.

2021-06-10 17:16 UTC, chambridge commented on pkg/commits/commits_test.go
> +		want := "[]\n"
Instead of string comparison Its probably worth processing this as [JSON](https://stackoverflow.com/a/31129967).

I would also make the response --> JSON processing a reusable function for each of the tests.

2021-06-10 17:16 UTC, chambridge commented on pkg/commits/commits_test.go
> +	db.DB.Delete(&cmt)
The initialize and delete db steps are a good candidate for a [setup/teardown flow](http://www.inanzzz.com/index.php/post/2t08/using-setup-and-teardown-in-golang-unit-tests).

2021-06-10 18:04 UTC, biancarosa commented on pkg/commits/commits_test.go
> +	}
We could also start taking a look at test suites and make use of SetUp / TearDown methods

2021-06-14 18:15 UTC, biancarosa approved these changes
This is the way.

2021-06-14 20:08 UTC, chambridge commented
Looks like just a minor **go vet** issue to resolve then good 👍 

```
Run make vet
go vet $(go list ./... | grep -v /vendor/)
# github.com/redhatinsights/edge-api/pkg/commits
pkg/commits/uploader.go:85:4: Warnf call has error-wrapping directive %w
make: *** [Makefile:50: vet] Error 2
Error: Process completed with exit code 2.
```

2021-06-15 18:07 UTC, chambridge approved these changes
LGTM

2021-06-17 16:14 UTC, merged