WIP - Feature: Create image
RedHatInsights/edge-api pull request #38
Opened 2021-06-10 20:58 UTC by biancarosa

bad bad request

`curl -v -H "Content-Type: application/json"  http://localhost:3000/api/edge/v1/images -d '{wrong json}'`

minimum valid request
`curl -v -H "Content-Type: application/json"  http://localhost:3000/api/edge/v1/images -d '{"Distribution": "rhel-8", "Architecture": "x86_64", "OutputType": "tar"}'`

still have to:
- find out how to annotate things properly to generate docs
- work on the todo's to actually do something
- write better tests

2021-06-10 21:21 UTC, maxamillion requested changes

2021-06-10 21:21 UTC, maxamillion commented on pkg/models/images.go
> +	OSTreeURL    string
Something we could do here is have `Architecture`, `OSTreeRef`, and `OSTreeURL`  be only stored in the [`Commit`](https://github.com/RedHatInsights/edge-api/blob/8bd239ed5ba1fbd0e82a6eabbe97cf7683785b18/pkg/commits/commits.go#L22) and the `Image` type then have a field that correlated to a `Commit` either as a `Commit.ID`, a `*Commit` or a foreign key in the table.

Thoughts?

2021-06-10 21:21 UTC, maxamillion commented on pkg/images/images.go
> +
@jhjaggars does need anything from the middleware here to deal with accounts?

2021-06-11 12:45 UTC, jhjaggars commented on pkg/images/images.go
> +
Yes, tenancy has to be built into the model itself (i.e. add an account/org field), and requests need to be filtered by the Identity object from middleware as in the other handlers.

2021-06-11 13:22 UTC, biancarosa commented on pkg/models/images.go
> +	OSTreeURL    string
I like that! Gonna update the code to reference a commit here

2021-06-11 20:11 UTC, biancarosa commented on pkg/images/images.go
> +
I did that, don't know exactly if I did it on the best possible way since Image has a Commit and both have an Account

2021-06-11 21:49 UTC, biancarosa commented
@maxamillion apart from tests, this is the best i could do right now 😓 

take a look, especially at the models, because I'm still not sure what goes into the image and what goes into the commit (maybe the packages have to move to the commit)

2021-06-14 18:56 UTC, maxamillion commented on pkg/models/images.go
> +	Packages     []Package `gorm:"many2many:image_packages;"`
The `Package`s manifest belongs to the `Commit` and the `Commit` to the `Image`.

Effectively "An `Image` contains a `Commit` and a `Commit` contains many `Packages`. Currently in the `Commit` struct there's a field `NEVRAManifest` which was a meant for that to specify that it was a NEVRA representation of the package manifest for the `Commit` (but I have zero preference on what we actually call the thing, "`Packages`" is perfectly fine).

2021-06-14 19:11 UTC, biancarosa commented on pkg/models/images.go
> +	Packages     []Package `gorm:"many2many:image_packages;"`
Will move that! I think we should be able to get the _NEVRAManifest_ field as a response from Image Builder at some point, so we could keep both fields for now and see if we really need that info duplicated or not. We were a bit a concerned about the size of the package list.

2021-06-14 20:04 UTC, maxamillion commented on pkg/models/commits.go
> +	Packages             []Package `gorm:"many2many:image_packages;"`
If we're going to use `Packages` here, we can remove the `NEVRAManifest` field since it's not longer needed (it's a duplicate with the introduction of `Packages`).

2021-06-14 22:17 UTC, maxamillion commented
If you can make the GitHub Actions checks happy, I'm good with the PR. LGTM :+1:

2021-06-15 14:21 UTC, biancarosa commented
@maxamillion i think we're good now! i still wanna make those tests look a little bit better but this is a blocker for the other tasks so we can do it in another PR

2021-06-16 13:46 UTC, biancarosa commented
Merging this since Adam's on PTO and already commented that he was good with the changes :)

2021-06-16 13:46 UTC, merged