add podmant to readme
RedHatInsights/edge-api pull request #412
Opened 2021-11-30 22:19 UTC by acosferreira

# Description

Add steps to run edge-api using podman and fix problem on fdo once we dont want compile it locally 

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Tests update

2021-11-30 22:44 UTC, loadtheaccumulator requested changes
Looks good with minor changes.

2021-11-30 22:44 UTC, loadtheaccumulator commented on README.md
> +From within your edge-api director
directory typo?

2021-11-30 22:44 UTC, loadtheaccumulator commented on README.md
> +Now the application should be running. You can test this by port-forwarding the app in one terminal and running a curl command in another as follows:
Is "port-forwarding the app" described somewhere, so I know what it should mean?

2021-11-30 22:44 UTC, loadtheaccumulator commented on README.md
> +Using podman you might encounter permission denied error, well that’s error is because of podman  rootless state.
typo /that's/that/

2021-12-01 06:09 UTC, Avielyo10 commented on README.md
> +run -p 3000 --security-opt label=disable --group-add tty --rm -ti -v $(pwd):/edge-api quay.io/cloudservices/edge-api:libfdo-data /bin/bash
I strongly advise not use `security-opt` and just run podman with `:Z` on it's volume since that's the podman way of doing it.

```shell
podman run --rm -ti -p 3000:3000 -v $(pwd):/edge-api:Z quay.io/cloudservices/edge-api:libfdo-data /bin/bash
```

2021-12-01 06:10 UTC, Avielyo10 commented on README.md
> +podman pull quay.io/cloudservices/edge-api:qa
Why pulling `:qa`?

2021-12-01 06:13 UTC, Avielyo10 commented on README.md
> +DEBUG=True AUTH=False go run main.go [remember your vars]
It can actually now being used the same way you were running it on your PC

```shell
DEBUG=true go run main.go
```

2021-12-01 06:15 UTC, Avielyo10 commented on README.md
> +Now the application should be running. You can test this by port-forwarding the app in one terminal and running a curl command in another as follows:
with `-p 3000:3000` there no need for port forwarding

2021-12-01 06:24 UTC, Avielyo10 commented on README.md
> +
The `:libfdo-data` is a bit special and can help with running tests, it contains a script that can help you run the tests from:
1.  edge-api upstream **(clone on each run)**
* `podman run --rm -ti quay.io/cloudservices/edge-api:libfdo-data`
2. your edge-api fork **(clone on each run)**
* `podman build -f ./test-container --build-arg GIT_BRANCH=fdo --build-arg GIT_REMOTE=https://github.com/Avielyo10/edge-api.git -t quay.io/ayosef/libfdo-data:test`
* `podman run --rm -ti quay.io/ayosef/libfdo-data:test`
3.  your localhost with volume
* `podman run --rm -ti -v $(pwd):/edge-api:Z quay.io/cloudservices/edge-api:libfdo-data`

2021-12-01 06:25 UTC, Avielyo10 requested changes
The `:libfdo-data` is a bit special and can help with running tests, it contains a script that can help you run the tests from:
1.  edge-api upstream **(clone on each run)**
* `podman run --rm -ti quay.io/cloudservices/edge-api:libfdo-data`
2. your edge-api fork **(clone on each run)**
* `podman build -f ./test-container --build-arg GIT_BRANCH=fdo --build-arg GIT_REMOTE=https://github.com/Avielyo10/edge-api.git -t quay.io/ayosef/libfdo-data:test`
* `podman run --rm -ti quay.io/ayosef/libfdo-data:test`
3.  your localhost with volume
* `podman run --rm -ti -v $(pwd):/edge-api:Z quay.io/cloudservices/edge-api:libfdo-data`

2021-12-01 14:40 UTC, biancarosa commented on README.md
> +DEBUG=True AUTH=False go run main.go [remember your vars]
I don't keep my vars on the go run main.go command, so it can be worthy to just mention that from there, you can just use same command as you would on your machine

2021-12-01 17:09 UTC, acosferreira commented on README.md
> +podman pull quay.io/cloudservices/edge-api:qa
I've tried with latest and others however was failing, the only one that didn't fails was qa? any suggestion?

2021-12-01 22:41 UTC, loadtheaccumulator commented on README.md
> +Now the application should be running. You can test this by port-forwarding the app in one terminal and running a curl command in another as follows:
Should the wording change?

2021-12-01 22:47 UTC, loadtheaccumulator approved these changes

2021-12-02 09:02 UTC, Avielyo10 commented on README.md
> +podman pull quay.io/cloudservices/edge-api:qa
What about `:libfdo-data`?

2021-12-02 09:04 UTC, Avielyo10 approved these changes
lgtm

2021-12-02 09:05 UTC, Avielyo10 commented
Thanks @acosferreira 🙏🏽

2021-12-02 14:32 UTC, Avielyo10 commented on README.md
> +podman pull quay.io/cloudservices/edge-api:qa
OK sorry now I get it, we will need to change it a bit now sorry

2021-12-02 14:33 UTC, Avielyo10 commented on README.md
> +
This can all be squashed into:
`podman run -p 3000:3000 --rm -ti quay.io/cloudservices/edge-api:qa`

2021-12-02 14:34 UTC, Avielyo10 commented on README.md
> +```
This can all be squashed into:
`podman run --rm -ti -p 3000:3000 quay.io/cloudservices/edge-api:qa`

2021-12-02 14:37 UTC, Avielyo10 commented
I just now figured what you were trying to do, so running `podman run --rm -ti -p 3000:3000 quay.io/cloudservices/edge-api:qa` will solve all of your problems without anything else needed.
The `:libfdo-data` can be used for testing locally 😄

2021-12-02 16:08 UTC, merged