Feat/return pkg info on image
RedHatInsights/edge-api pull request #434
Opened 2021-12-07 19:50 UTC by acosferreira

# Description

Added packages information to (updated, removed, added, total installed, aditional) to image endpoint.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [X] Tests update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2021-12-09 09:55 UTC, Avielyo10 requested changes
For new structs please use snake_case instead of CamelCase on JSON tags

2021-12-09 09:55 UTC, Avielyo10 commented on pkg/routes/images.go
> +}
Please use snake_case instead of CamelCase on JSON tags

2021-12-09 09:55 UTC, Avielyo10 commented on pkg/routes/images_test.go
> +	UpdateUpdated     int          `json:"UpdateUpdated"`
Please use snake_case instead of CamelCase on JSON tags

2021-12-09 09:55 UTC, Avielyo10 commented on pkg/routes/imagesets.go
> +	ImageBuildISOURL string          `json:"ImageBuildISOURL"`
Please use snake_case instead of CamelCase on JSON tags

2021-12-09 09:55 UTC, Avielyo10 commented on pkg/services/images.go
> +	UpdateUpdated     int           `json:"UpdateUpdated"`
Please use snake_case instead of CamelCase on JSON tags

2021-12-09 20:28 UTC, biancarosa commented on pkg/routes/images_test.go
> +	fmt.Printf(":: respBody :: %v\n", &ir)
👀

2021-12-09 20:28 UTC, biancarosa commented on pkg/routes/imagesets.go
> +	fmt.Printf("::: list :: %v\n", Imgs)
👁️

2021-12-09 20:28 UTC, biancarosa commented on pkg/routes/imagesets.go
> +		fmt.Printf("::: list last element:: %v\n", Imgs[len(Imgs)-1].Image.ID)
👀

2021-12-10 12:49 UTC, biancarosa approved these changes
I'm good with it.

2021-12-10 18:53 UTC, acosferreira commented
@Avielyo10 I'm merging to unblock FE Team, let me know if you see anything else that need to be changed or fixed.

2021-12-10 18:53 UTC, merged