Bug Fix THEEDGE-1051
RedHatInsights/edge-api pull request #453
Opened 2021-12-13 16:53 UTC by Saurabh-Thakre

# Description

Edge API allows many instances of the same version of the image.

Fixes THEEDGE-1051

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

2021-12-13 17:19 UTC, biancarosa reviewed
It'd be nice to have tests here and this logic moved to a service

2021-12-13 19:14 UTC, Avielyo10 requested changes
As @biancarosa mentioned, this logic should be under `services` , we want to keep the routes clean from the logic (modularity)

2021-12-13 19:14 UTC, Avielyo10 commented on pkg/routes/images.go
> +	var nextImageVersion *models.Image           // nextImageVersion is the next version of current image to which we are updating the image i.e if image3 is the next version of image2.
This explanation should be a multiline comment above the var declaration so this can be readable

2021-12-13 19:14 UTC, Avielyo10 commented on pkg/routes/images.go
> +	// log.Infof("currentHighestVersion: %v, nowImageVersion %v, nextImageVersion %v", currentHighestImageVersion.Version, nowImage.Version, nextImageVersion.Version) // we can delete this later
Unnecessary comment

2021-12-14 11:07 UTC, Saurabh-Thakre commented on pkg/routes/images.go
> +	// log.Infof("currentHighestVersion: %v, nowImageVersion %v, nextImageVersion %v", currentHighestImageVersion.Version, nowImage.Version, nextImageVersion.Version) // we can delete this later
I kept for debugging but yeah I can remove it :)

2021-12-16 08:24 UTC, Avielyo10 commented on pkg/services/images_test.go
> +	"github.com/redhatinsights/edge-api/pkg/services"
That's a loop, you don't need to import a package you're already in

2021-12-16 08:26 UTC, Avielyo10 commented on pkg/services/images.go
> +		// err := errors.NewBadRequest("only the latest updated image can be modified")
Unnecessary comment

2021-12-16 14:49 UTC, biancarosa approved these changes
LGTM!

2021-12-20 08:42 UTC, Avielyo10 reviewed
Can you add more test cases to cover `checkForDuplicateImageVersion`

2021-12-20 09:02 UTC, merged