add new scenarios to add and commitCtx
RedHatInsights/edge-api pull request #48
Opened 2021-06-17 23:29 UTC by acosferreira

2021-06-18 12:05 UTC, biancarosa commented on pkg/commits/commits_test.go
> +	err := db.DB.AutoMigrate(models.Commit{})
Can we run automigrate in `setUp`?

2021-06-23 17:51 UTC, boaz0 requested changes
Few small changes. But looks amazing! Thanks!

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
>  			t.Errorf("got %q", got)
Nitpick:
```go
t.Errorf("Expected status code to be %q but got %q", want, got)
```

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
:waffle:

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
:sunrise_over_mountains:

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
here 3 :smile:

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
here too :smiley:

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
same as above:

```go
t.Errorf("Expected status code to be %q but got %q", want, got)
```

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +			t.Errorf("got %q", got)
last one

2021-06-23 17:51 UTC, boaz0 commented on pkg/commits/commits_test.go
> +	// err := db.DB.AutoMigrate(models.Commit{})
should we remove these comments?

2021-06-23 18:55 UTC, boaz0 approved these changes

2021-06-23 19:44 UTC, biancarosa approved these changes

2021-06-23 19:44 UTC, merged