Make private Context api-edge services key.
RedHatInsights/edge-api pull request #499
Opened 2021-12-23 14:54 UTC by ldjebran

# Description
Make the context key of edge api services private, this will prevent future bugs. and simplify code reading.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes

2021-12-23 15:47 UTC, Avielyo10 requested changes
Thanks for it, this looks much better than before!

2021-12-23 15:47 UTC, Avielyo10 commented on pkg/dependencies/main.go
> +}
We should catch any errors as we can, I have 2 suggestions:
1. Return only `*EdgeAPIServices` and ignore the check of its existence, then on each `services, _ := dependencies.ServicesFromContext(r.Context())` we can write `services := dependencies.ServicesFromContext(r.Context())` & check `services` for nil.
  ```suggestion
  func ServicesFromContext(ctx context.Context) *EdgeAPIServices {
	      edgeAPIServices, _ := ctx.Value(servicesKey).(*EdgeAPIServices)
	      return edgeAPIServices
  }
  ```
2. Keep this function as it is & for each `services, _ := dependencies.ServicesFromContext(r.Context())` we should write `services, ok := dependencies.ServicesFromContext(r.Context())`, then try to see if `!ok`

I tend to go with the first suggestion, but this is up to you.

2021-12-23 16:45 UTC, ldjebran commented on pkg/dependencies/main.go
> +}
if context value does not exist a nil will be returned , and the cast will fail with ok = false , so the check will be from the side of the caller function.

2021-12-23 16:46 UTC, ldjebran commented on pkg/dependencies/main.go
> +}
Fixing caller function is not the purpose of this PR.

2021-12-23 16:48 UTC, ldjebran commented on pkg/dependencies/main.go
> +}
@Avielyo10 what do you think?

2021-12-23 17:15 UTC, Avielyo10 commented on pkg/dependencies/main.go
> +}
You are correct saying this is not the PR intention, but if we do a refactor don't you think we should make it all through it is done?so this won't need more refactoring on the same place?
You can create a separate PR for the check if you'd like, this will be very helpful for everyone

You are also correct that its the caller responsibility to check the output of a function, but then I'd suggest sending back an `error` instead of a boolean, this way static code analysis & security checks we want to add will fail since we have an unhandled error. (returning `bool` won't do that)

2021-12-23 17:24 UTC, ldjebran commented on pkg/dependencies/main.go
> +}
I think we should not modify ServicesFromContext to return an error , the caller function should generate it's proper error when receiving ok = false , perhaps the caller function will call init function and write a new value , some other function will generate a fatal error, and other function can pass silent if it's not critical, we cannot decide at this place.

2021-12-23 18:39 UTC, ldjebran commented on pkg/dependencies/main.go
> +}
Maybe there is a sync-up misunderstanding :) let me explain my point of view

When accessing Context values the code reader is waiting to see a boolean as in all the project we are using that pattern when accessing context values.

Returning errors is a good a idea , as we the caller function will have a ready to use error to return when necessary , but the error should be an instance so the caller can make comparisons.

But we not want to make services context value a special case.

I think If we should return an error let's do it by writing a global public function that access context and return standard project errors like 
ErtContextVaslueNotFound  - in case of key not found
ErrContextValueMismatch  - In case the cast fail

Let's discuss about it after the holidays, Happy Holidays :)

2021-12-23 19:35 UTC, Avielyo10 commented on pkg/dependencies/main.go
> +}
@ldjebran I think you are missing Golang's error concept, returning an error doesn't mean throwing an error. Errors are values, so each caller can handle it differently but as it comes to code quality check then the caller must handle it & can't ignore it.
```suggestion
func ServicesFromContext(ctx context.Context) (edgeAPIServices *EdgeAPIServices, err error) {
	edgeAPIServices, ok = ctx.Value(servicesKey).(*EdgeAPIServices)
	if !ok {
	    err = errors.New("Couldn't get services from Context")
	}
}
```

2021-12-27 09:12 UTC, Avielyo10 commented
@biancarosa why do we use `iota`? As each request has its own `Context` which derived from background we can have it a `const string`. I do afraid this can become a problem in the future (2^64 - 1 is actually infinity) do we want to pass those large numbers for each request? (they gets bigger & bigger without an actual necessity)

2021-12-27 10:06 UTC, Avielyo10 commented
I don't think we should use `iota` in this case, sure this should be unique but:

1. Different packages can still collide. (for example using hardcoded predefined values by other packages)
2. 2^64 - 1 is practically infinity, are we sure we want to pass those big integers as keys?

Referring https://pkg.go.dev/context#WithValue example, the best practice should follows something like:

```go
// edgeAPIKey is the context key for dependencies on the request context
type edgeAPIKey string

// Middleware is the dependencies Middleware that serves all Edge API services on the current request context
func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		services := Init(r.Context())
		ctx := context.WithValue(r.Context(), edgeAPIKey("services"), services)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func ServicesFromContext(ctx context.Context) (edgeAPIServices *EdgeAPIServices, err error) {
	edgeAPIServices, ok := ctx.Value(edgeAPIKey("services")).(*EdgeAPIServices)
	if !ok {
		err = errors.New("couldn't get services from Context")
	}
	return
}

```
@ldjebran @biancarosa WDYT?

2021-12-27 13:38 UTC, biancarosa commented on pkg/dependencies/main.go
> +}
I think we can catch the error here and log as log.Fatal. If something happens, the caller shouldn't have to handle it because this is core functionality.

2021-12-27 15:46 UTC, biancarosa commented
I'm good with the suggestion about not using iota, I think that was done before and we just kept the pattern but it's better indeed.

2021-12-27 15:56 UTC, Avielyo10 commented on pkg/dependencies/main.go
> +}
@biancarosa I was thinking maybe if there is an error there, then we can return immediately on `Middleware` without forwarding.

2022-01-03 19:43 UTC, ldjebran commented
@Avielyo10 @biancarosa all comments allied please review.

2022-01-04 08:35 UTC, Avielyo10 approved these changes
lgtm

2022-01-04 08:35 UTC, merged