Feat: Get image status after composing with a goroutine on the background
RedHatInsights/edge-api pull request #50
Opened 2021-06-22 17:24 UTC by biancarosa

2021-06-22 17:29 UTC, biancarosa commented
oh boy these test results are not looking good, i see data race and i'm sweating

2021-06-23 13:50 UTC, boaz0 requested changes

2021-06-23 13:50 UTC, boaz0 commented on pkg/images/images.go
> +		db.DB.First(&i, image.ID)
shouldn't `image.ID` be replaced with `id`?

2021-06-23 13:50 UTC, biancarosa commented on pkg/images/images.go
> +		db.DB.First(&i, image.ID)
yes! you're a life savior

2021-06-23 14:26 UTC, boaz0 approved these changes

2021-06-23 14:26 UTC, boaz0 commented
LGTM feel free to merge it.

2021-06-23 14:58 UTC, maxamillion commented
LGTM, merge!

2021-06-23 14:58 UTC, maxamillion approved these changes

2021-06-23 15:29 UTC, merged