Don't duplicate ImageSets when an Image with the same name attempts to be created twice
RedHatInsights/edge-api pull request #595
Opened 2022-02-02 21:41 UTC by maxamillion

Signed-off-by: Adam Miller <admiller@redhat.com>

# Description

Removes the ability to create a duplicate an ImageSet.

## Type of change

What is it?

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-02-03 12:12 UTC, Avielyo10 approved these changes
ltgm

2022-02-03 12:25 UTC, biancarosa requested changes

2022-02-03 12:25 UTC, biancarosa commented on pkg/services/images.go
> +		log.Errorf("ImageSet %s already exists, UpdateImage transaction expected and not CreateImage", image.Name)
```suggestion
		s.log.WithField("imageSetName", name).Error("ImageSet already exists, UpdateImage transaction expected and not CreateImage", image.Name)
```

2022-02-03 12:27 UTC, biancarosa commented on pkg/services/images.go
> +	if (err == nil) && imageSetExists {
shouldn't we check if err != nil before that block? if returning an image fails i think we should give an internal error, no?

2022-02-03 12:28 UTC, Avielyo10 commented
@Mergifyio refresh

2022-02-04 17:40 UTC, maxamillion commented on pkg/services/images.go
> +	if (err == nil) && imageSetExists {
oh, yes ... .yes we should, thanks!

2022-02-04 17:48 UTC, maxamillion commented
@Mergifyio refresh

2022-02-04 19:22 UTC, merged