Theedge 1591 create device groups
RedHatInsights/edge-api pull request #605
Opened 2022-02-03 17:35 UTC by acosferreira

# Description

Enable POST to create a device group for an account
Fixes # ([THEEDGE-1591](https://issues.redhat.com/browse/THEEDGE-1591))

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ X New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-02-03 17:52 UTC, biancarosa requested changes
One tiny question, but it overall looks really good

2022-02-03 17:52 UTC, biancarosa commented on pkg/services/devicegroups.go
> +		Type:    "Static",
Can we have enums for the different types of device groups?

2022-02-03 18:18 UTC, thom-at-redhat approved these changes
or services.Log.WithField("error", deviceGroup).Error("Error while trying to encode") should it include the error?
[13:16](https://ansible.slack.com/archives/D026HD66H47/p1643912194580729)
https://github.com/RedHatInsights/edge-api/pull/605/files#diff-48f6502941a54bb08d271267b7002cd524e07fade2ffb11ba7437baca89f781dR141
[13:17](https://ansible.slack.com/archives/D026HD66H47/p1643912221079169)
should this line really be fatal? https://github.com/RedHatInsights/edge-api/pull/605/files#diff-92650eeda9113d0189e6d4e3e6e06515793b0e6749da21f051115cefb92ad753R142

2022-02-04 14:26 UTC, biancarosa approved these changes

2022-02-04 14:40 UTC, merged