Main refactoring
RedHatInsights/edge-api pull request #706
Opened 2022-02-23 14:42 UTC by Avielyo10

# Description

* Use some functions for maintainability
* Remove unneeded channels & goroutines
* Register consumer closing in a graceful manner.
* Anonymouse consumers.
* Handle nil kafka config in the the service creation.
* Close() is a part of the ConsumerService

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [x] Refactor

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I run `go fmt ./...` to check that my code is properly formatted
- [x] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +func serveMetrics(port int) *http.Server {
Moving this to its own file might improve readability. Something like a `metrics.go`

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +func serveMetrics(port int) *http.Server {
I really like this idea, good job!

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +	route.Get("/", routes.StatusOK)
Love these more explicit var names

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +				consumer.Close()
Very nice

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +				go consumer.Start()
Very very nice!

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +	<-sigint
Humm, can we think of a more verbose name here?

2022-02-23 15:27 UTC, AaronH88 commented on pkg/services/consumers.go
> +	if config != nil {
If we change the condition here we can improve readability a bit, and also remove some nested `if`'s

e.g. `if config == nil { return nil }`

2022-02-23 15:27 UTC, AaronH88 commented on main.go
> +	<-sigint
Also, where was this `sigint` channel created?

2022-02-24 09:17 UTC, Avielyo10 commented on main.go
> +func serveMetrics(port int) *http.Server {
You mean separate the metrics & the web servers?

2022-02-24 09:19 UTC, Avielyo10 commented on main.go
> +	<-sigint
like `interruptSignal`?
Created at the beginning of `main()`

2022-02-24 09:19 UTC, Avielyo10 commented on pkg/services/consumers.go
> +	if config != nil {
Like that!

2022-02-24 13:55 UTC, AaronH88 commented on main.go
> +func serveMetrics(port int) *http.Server {
Exactly, I personally would expect to find this either under `pkg/routes/` or `pkg/services/` 
Just a thought :smile:

2022-02-24 13:55 UTC, AaronH88 commented on main.go
> +	<-sigint
Great choice

2022-02-24 15:20 UTC, Avielyo10 commented on main.go
> +func serveMetrics(port int) *http.Server {
Can this take place in a new PR?

2022-02-25 11:17 UTC, ldjebran reviewed
It looks good, waiting @AaronH88 response

2022-02-26 01:23 UTC, loadtheaccumulator requested changes
Do all of these commits have to go in at the same time, or can they be broken into separate PRs. We've been running into breakage issues with large refactors.

I think we might need to sync more on refactor plans versus new feature now that we're in squads and might be touching the same code.

2022-02-27 14:59 UTC, Avielyo10 commented
@loadtheaccumulator, actually they are all connected in some way.

This is not a feature, only improve readability & avoid goroutines leak on main (also implement a real graceful shutdown)

2022-02-27 15:02 UTC, Avielyo10 commented
@mergify rebase

2022-02-28 13:57 UTC, AaronH88 commented on main.go
> +func serveMetrics(port int) *http.Server {
Yes it can, Ok move this in a new PR.

2022-02-28 14:00 UTC, AaronH88 commented
Looks good to me, ok to merge as well as have that chat Jonathan is pointing out

2022-02-28 16:21 UTC, Avielyo10 commented
@loadtheaccumulator ?

2022-03-01 07:08 UTC, merged