remove update dd device from execution
RedHatInsights/edge-api pull request #709
Opened 2022-02-24 17:25 UTC by acosferreira

# Description

Remove wipe execution

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [X] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-02-24 19:25 UTC, acosferreira commented
/retest

2022-02-25 16:11 UTC, ldjebran approved these changes
LGMT

2022-02-25 16:11 UTC, ldjebran commented
/retest

2022-02-25 17:26 UTC, thom-at-redhat approved these changes

2022-02-27 12:32 UTC, Avielyo10 requested changes

2022-02-27 12:32 UTC, Avielyo10 commented on test-container/Dockerfile
> +    #cd fido-device-onboard-rs && cargo build --lib
why?

2022-02-27 15:01 UTC, Avielyo10 commented
@mergify rebase

2022-03-01 00:53 UTC, acosferreira commented on test-container/Dockerfile
> +    #cd fido-device-onboard-rs && cargo build --lib
was a try to fix the ci problem ;)

2022-03-01 07:07 UTC, Avielyo10 approved these changes

2022-03-01 07:24 UTC, merged