Endpoint upgrade
RedHatInsights/edge-api pull request #73
Opened 2021-07-07 18:37 UTC by acosferreira

Created endpoint to get the devices by tag or id
Returns the device metadata
Returns the current rpm-ostree commits (checksum)

2021-07-07 20:16 UTC, biancarosa commented on pkg/devices/devices.go
> +	fmt.Printf("Requesting url: %s\n", fullURL)
Can we use the logger instead of prints? :)

2021-07-07 20:17 UTC, biancarosa commented on pkg/devices/devices.go
> +	fmt.Printf("Requesting url: %s\n", fullURL)
`log.Infof....`

2021-07-08 13:18 UTC, chambridge requested changes
Need some updates to work when deployed and handle error cases.

2021-07-08 13:18 UTC, chambridge commented on pkg/devices/devices.go
> +	}
After reviewing the file, it feels like this section could be made into a common method for interacting with the host inventory.  Perhaps just taking a map of parameters to append to the path?

2021-07-08 13:18 UTC, chambridge commented on pkg/updates/updates.go
> +	}
Need to handle the error condition and still reply with a response, otherwise you are just going to end up with a timeout 503 from the 3scale gateway.

2021-07-08 13:18 UTC, chambridge commented on pkg/updates/updates.go
> +			//FIXME: Load results into DB
Are we really trying to store the results? Seems like we would just be duplicating the data in the host inventory, no?

2021-07-08 13:18 UTC, chambridge commented on pkg/updates/updates.go
> +		}
This should have an error response back, right? otherwise it will just time out rather than giving a 400 for bad request.

2021-07-08 13:18 UTC, chambridge commented on pkg/updates/updates.go
> +	sub.Route("/device_uuid={device_uuid}", func(r chi.Router) {
I could be wrong but I would think this would just be:

```suggestion
	sub.Route("/{device_uuid}", func(r chi.Router) {
```

2021-07-08 13:18 UTC, chambridge commented on pkg/updates/updates.go
> +	sub.Route("/tags={tags}", func(r chi.Router) {
Is this meant to be a route or are you really just trying to handle query parameters?

2021-07-08 16:47 UTC, acosferreira commented on main.go
> +		// s.Route("/devices", devices.MakeRouter)
No, I'll remove that, is not used route

2021-07-08 17:07 UTC, maxamillion commented on pkg/updates/updates.go
> +			//FIXME: Load results into DB
@chambridge we need a record of which update correlates to which devices and we also need to store the device uuids so we can send Playbook Dispatcher payloads. If there's a better way to accomplish this then that would be awesome, but I don't know of any way.

2021-07-08 17:32 UTC, maxamillion commented on pkg/devices/devices.go
> +	}
Agreed, let's move this to `pkg/common/`

2021-07-08 17:38 UTC, maxamillion commented on pkg/updates/updates.go
> +	sub.Route("/device_uuid={device_uuid}", func(r chi.Router) {
@chambridge I'd suggest it be namespaced like this:
```suggestion
	sub.Route("/device/{device_uuid}", func(r chi.Router) {
```

2021-07-08 17:39 UTC, maxamillion commented on pkg/updates/updates.go
> +	sub.Route("/device_uuid={device_uuid}", func(r chi.Router) {
actually on second thought it probably should just be
```suggestion
	sub.Route("/", func(r chi.Router) {
```
and handle params in the context manager

2021-07-08 17:41 UTC, chambridge commented on pkg/updates/updates.go
> +			//FIXME: Load results into DB
I'm good with storing device ids --> update relationship. The FIXME didn't give a lot of clarity around what is being stored. I didn't want to be storing duplicate data.

Depending on whether the update information can/will be contained in the inventory down the line you could look at 
[Host Data Syndication](https://clouddot.pages.redhat.com/docs/dev/services/inventory.html#cyndi) to give you this relationship.

2021-07-08 19:57 UTC, biancarosa commented on pkg/updates/updates.go
> +			err := errors.NewInternalServerError()
I'd do a errors.NewBadRequest here because it seems like an error related to the user input

2021-07-08 20:10 UTC, biancarosa approved these changes
It looks good to me, but I'd wait for @chambridge since he requested more changes :)

2021-07-08 20:23 UTC, boaz0 reviewed
All in all LGTM

2021-07-08 20:23 UTC, boaz0 commented on pkg/devices/devices.go
> +	fullURL := url + filterParams
small nitpick => replacing this two lines to
```go
url := fmt.Sprintf("%s/api/inventory/v1/hosts%s", config.Get().InventoryConfig.URL, filterParams)
```

2021-07-08 20:59 UTC, maxamillion commented
LGTM :+1:

2021-07-08 21:00 UTC, maxamillion commented on pkg/updates/updates.go
> +			//FIXME: Load results into DB
@chambridge ah, sounds good ... yeah, all we're doing is storing the UUID from inventory and then a couple bits of info that are edge-api centric -> https://github.com/RedHatInsights/edge-api/blob/655256c8230cb8efd0bd91f6563c923d83cb1203/pkg/models/updates.go#L18

2021-07-08 21:07 UTC, chambridge approved these changes

2021-07-08 21:20 UTC, chambridge commented
/retest

2021-07-08 21:25 UTC, chambridge commented
It appears to be crashlooping in the migrate.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85053e]

goroutine 1 [running]:
github.com/redhatinsights/edge-api/config.Init()
	/src/mypackage/myapp/config/config.go:109 +0xafe
main.main()
	/src/mypackage/myapp/cmd/migrate/migrate.go:12 +0x3
```

2021-07-08 21:45 UTC, maxamillion commented
> It appears to be crashlooping in the migrate.
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85053e]
> 
> goroutine 1 [running]:
> github.com/redhatinsights/edge-api/config.Init()
> 	/src/mypackage/myapp/config/config.go:109 +0xafe
> main.main()
> 	/src/mypackage/myapp/cmd/migrate/migrate.go:12 +0x3
> ```

This PR doesn't touch the migration though ... what could cause that? Is it angry at changes to a struct somewhere?

2021-07-08 22:04 UTC, chambridge commented on config/config.go
> +	options.SetDefault("InventoryUrl", "https://host-inventory-service:8080/")
```suggestion
	options.SetDefault("InventoryUrl", "http://host-inventory-service:8080/")
```

2021-07-08 22:06 UTC, chambridge commented
/retest

2021-07-08 23:37 UTC, acosferreira commented
/retest

2021-07-09 14:56 UTC, biancarosa commented
@acosferreira the ephemeral env is fine now, can you rebase? :)

2021-07-09 16:13 UTC, merged