Create Unit tests covering remove fleet Management device(s) from an existing device group
RedHatInsights/edge-api pull request #753
Opened 2022-03-07 12:40 UTC by Avielyo10

# Description

Create Unit tests covering remove fleet Management device(s) from an existing device group

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I run `go fmt ./...` to check that my code is properly formatted
- [ ] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-03-07 14:25 UTC, AaronH88 commented on pkg/services/devicegroups_test.go
> +			It("should not remove non existing devices from device-group", func() {
This description is the same as line 311, can this one of them be reworded so its easier to find if they fail?

2022-03-07 14:25 UTC, AaronH88 requested changes
One description change, then its good to merge

2022-03-07 19:19 UTC, Avielyo10 commented on pkg/services/devicegroups_test.go
> +			It("should not remove non existing devices from device-group", func() {
Done

2022-03-07 22:21 UTC, loadtheaccumulator approved these changes
/lgtm

2022-03-07 22:21 UTC, loadtheaccumulator commented on pkg/services/devicegroups_test.go
> +			It("should not delete non exsiting device from device-group", func() {
typo for existing

2022-03-07 23:24 UTC, acosferreira approved these changes
lgtm

2022-03-08 08:02 UTC, AaronH88 approved these changes

2022-03-08 08:02 UTC, AaronH88 commented
/lgtm

2022-03-08 08:03 UTC, merged