Validate create image name
RedHatInsights/edge-api pull request #80
Opened 2021-07-09 02:42 UTC by resoluteCoder

Added name validation for image with regex same as front end

2021-07-09 05:14 UTC, boaz0 requested changes
Please add unit tests as well!

2021-07-09 05:14 UTC, boaz0 commented on pkg/models/images.go
> +	NameCantBeInvalidMessage = "invalid input for name"
How about "name must start with alphanumeric characters and can contain underscore and hyphen characters"

2021-07-09 05:14 UTC, boaz0 commented on pkg/models/images.go
> +	if re := regexp.MustCompile(`^[A-Za-z0-9]+[A-Za-z0-9\s_-]*$`).FindString(i.Name); re == "" {
I would rather do something else than `regexp` but I guess `regexp` is much cleaner.
Anyway, why not using `MatchString(i.Name)`, that way you don't need `re`:
```go
 	if regexp.MustCompile(`^[A-Za-z0-9]+[A-Za-z0-9\s_-]*$`).MatchString(i.Name) {
```

2021-07-09 14:24 UTC, resoluteCoder commented on pkg/models/images.go
> +	if re := regexp.MustCompile(`^[A-Za-z0-9]+[A-Za-z0-9\s_-]*$`).FindString(i.Name); re == "" {
With FindString I can get a value back that can be checked for false.

Well, I suppose I can write `MatchString(i.Name) == false` or 
` if !regexp.MustCompile(pattern).MatchString(i.Name) {` and adding the `!`

What do you think?

2021-07-11 05:58 UTC, boaz0 commented on pkg/models/images.go
> +	if re := regexp.MustCompile(`^[A-Za-z0-9]+[A-Za-z0-9\s_-]*$`).FindString(i.Name); re == "" {
Yes that's what I meant.

2021-07-12 16:09 UTC, biancarosa approved these changes

2021-07-12 16:09 UTC, merged