Incorporate Ana"s changed from PR 86
RedHatInsights/edge-api pull request #953
Opened 2022-04-14 15:53 UTC by thom-at-redhat

# Description

Add many2many back reference for devicegroups/devices

Fixes # THEEDGE-1928

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-04-14 16:54 UTC, acosferreira commented on pkg/services/devices.go
> +	db.DB.Model(&device).Association("DevicesGroups").Find(&device.DevicesGroups)
Add a error handling please.

2022-04-14 16:55 UTC, acosferreira requested changes

2022-04-14 16:55 UTC, acosferreira commented on pkg/services/devices.go
> +	db.DB.Model(&device).Association("DevicesGroups").Find(&device.DevicesGroups)
Add a error handling please.

2022-04-14 16:55 UTC, acosferreira commented on pkg/services/devices.go
> +		db.DB.Where("id=?", dbDeviceID).First(&storeDevice)
Add a error handling please.

2022-04-15 02:00 UTC, loadtheaccumulator commented
/retest

2022-04-18 19:45 UTC, loadtheaccumulator approved these changes
lgtm

2022-04-18 21:12 UTC, merged