[DRAFT ]first try to generate RHEL9 image
RedHatInsights/edge-api pull request #963
Opened 2022-04-19 23:00 UTC by acosferreira

# Description
Changes to enable RHEL-9 image generation.
First try to map the responses from image-builder and make sure we can do it.

Local (RHEL-9|https://image-builder-service-stage.s3.amazonaws.com/composer-api-4030b5ff-bd18-43f4-ad31-7e3225a096c3-installer.iso?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA5M2E27MOEYHZAQUP%2F20220419%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220419T223626Z&X-Amz-Expires=604800&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEE8aCXVzLWVhc3QtMSJHMEUCIQCmREOcmpku6DorGzwnsYM1h8Oq%2F4jtmSykh0Dhl49zzwIgGOMoZ9k1B6muE3cSGjzTmEe6suIVmsHLaiFTONoqnYIqgwQI%2BP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw5MjA4Nzc5ODg2MzYiDEH3g26hsJTdzA6iHirXAyduMbXICgJuRl8fFcVLf0hVMx0Nxl%2B73GlU2fqDLCUoy36JNOMiop1yDz8ScYz%2BuyQy7PTlrupzYp1bJ6pPtwtwHgXwQupjzMGkKnqMZm8lbAo0x%2BfAbdhClu4NzsGUa8%2BADtE7GgM2HE7kAuUVcCcKpAYHaW94wsamr0yHzeJ%2B2stVAeQrwztCASLfX9EV6FJeBaqXpBRUK5FEg8xXv%2FBR7t23%2BF%2Bqvh8%2FyC5EZCJi7RE8GCYhpyXxFNjJBrD0DPsGJlgrfxyN4IQ34OBuUoU4m%2FHODY0CR0rxG1IymAb%2BCsotfoVbLWBmv2xIJHOt3OmQ0xuTz0XFAwKTyDpjkoAKH6Nk2z4P3SB4zEYGCYvt5Nopu6Aw%2Bz49A3%2BAu1DMDmaGhg1ljvaeMcF3OxIZ3bpYIXeXjZrjKN88EwIo1MilvbRha1jgB8SN%2Bm%2BbxhELabwUxcZbyw%2BMyN08PNWVOjtNC2l1Jo%2FQoujOGRyZqdqLhtJO0fRTIbc6fzZ3xf3F1XV%2BGylXwcLBV7%2FUfoRRN1N4iVgvOZpeSiDpjOLJeDzohVJXla5ztVC40D3XFNRC7L0FTamYcXD75qH1LMJH2nr6cd%2BDirL3OxXwfvzmE1fMhUaPKUv8jjDQ7PySBjqlAQj7qZb%2ByAVeKSu3d%2Bk8fOoxmozmc4zvQp%2Fc6Gt1YFfwgWrkuWJgcJXRkNsbhai6N6DZUx1aQ06FHFvwCKCLMeqloOT0Cui03l%2FAH44bSpYuXeCqLZo7%2BsiUcphxkC00MIoBhcB6aeZ1qSwl8kMwKcTM5Ae2yfwB11zDbt9mzO%2BFIRBeXIxOqyWmfU0tm7G1weJyc2N4oYynHJ3tXcIyOEFdar%2BuvA%3D%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=7a0f9942da1609759a0ec45587f46caee09a0302db81752814b5f8e091de5530)

2022-04-20 11:36 UTC, ldjebran commented on pkg/clients/imagebuilder/client.go
> +					Ref: "rhel/9/x86_64/edge", //image.Commit.OSTreeRef,
we need to support both 8 and 9 rhel major version 
as 8.6 is in beta and 9.0 in beta too 
so we should support both refs "rhel/9/x86_64/edge"  and "rhel/8/x86_64/edge"

2022-04-20 13:45 UTC, omaciel commented on pkg/models/images.go
> -	ImageTypeInstaller = "rhel-edge-installer"
We don't need to do this anymore as Sanne has another PR to reintroduce the 'RHEL-' alias for RHEL 9 too.

2022-04-20 13:46 UTC, omaciel commented on templates/templateKickstart.ks
> +	&& echo "ostreesetup --nogpg --osname=rhel-edge --remote=rhel-edge --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/edge" > /tmp/ostreesetup \
This has to handle both `8` and `9`.

2022-04-21 13:07 UTC, loadtheaccumulator requested changes

2022-04-21 13:07 UTC, loadtheaccumulator commented on templates/templateKickstart.ks
> +	&& echo "ostreesetup --nogpg --osname=rhel-edge --remote=rhel-edge --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/edge" > /tmp/ostreesetup \
Yeah. this will break the install on 8, but it should be easily distinguishable with another line here...

2022-04-24 18:59 UTC, loadtheaccumulator commented on templates/templateKickstart.ks
> +	&& echo "ostreesetup --nogpg --osname=rhel-edge --remote=rhel-edge --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/edge" > /tmp/ostreesetup \
Line 22 should stay 8. Line 23 applies to both 8 and 9 and the full ref path can be grabbed with...
ostree refs --repo=/ostree/repo

```
e.g.,
**$ ostree refs --repo=ostree/repo**
rhel/9/x86_64/edge
```

2022-04-24 19:00 UTC, loadtheaccumulator commented on templates/templateKickstart.ks
> +	&& echo "ostreesetup --nogpg --osname=rhel-edge --remote=rhel-edge --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/edge" > /tmp/ostreesetup \
SIDENOTE: I left off the leading slash in the example above, because I'm mounted to /mnt and cd'd into /mnt to run the command /ostree/repo is at the root of the ISO at kick.

2022-05-08 19:05 UTC, closed without merging