Added device group data to /devicesview endpoint.
RedHatInsights/edge-api pull request #966
Opened 2022-04-20 11:02 UTC by AaronH88

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I run `go fmt ./...` to check that my code is properly formatted
- [X] I run `go vet ./...` to check that my code is free of common Go style mistakes

2022-04-20 16:13 UTC, thom-at-redhat approved these changes

2022-04-20 16:21 UTC, thom-at-redhat requested changes
Clearing approval due to timing

2022-04-21 11:08 UTC, thom-at-redhat approved these changes

2022-04-21 11:25 UTC, ldjebran commented on pkg/models/devices.go
> +	DeviceGroupName []string `json:"DeviceGroupName"`
maybe create a struct 
```go
type DeviewDevioceGroup struct {
    ID uint
    Name string
}
```
and after 
```go
type DeviceView struct {
    ...
    DeviceGroups []DeviewDevioceGroup
    ...
```

2022-04-21 11:27 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
43c9ec0f-03e7-473f-b152-765bd3885977
ccfbc295-4059-4d5b-b7a7-2f838f2963cf

2022-04-21 11:40 UTC, thom-at-redhat commented on pkg/models/devices.go
> +	DeviceGroupName []string `json:"DeviceGroupName"`
fixing typos:
`type DeviceDeviceGroup struct {
    ID uint
    Name string
}`
and after
`type DeviceView struct {
    ...
    DeviceGroups []DeviceDeviceGroup
    ...`

2022-04-21 11:46 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
35de4c0d-c575-4a2f-a1b1-cd472228cd33
ca5101df-b316-49fc-89a7-c77906514714

2022-04-21 11:48 UTC, ldjebran commented on pkg/services/devices.go
> +	if res := tx.Limit(limit).Offset(offset).Where("account = ? AND image_id IS NOT NULL", account).Preload("UpdateTransaction").Preload("DevicesGroups").Find(&storedDevices); res.Error != nil {
we do not need "AND image_id IS NOT NULL" any more , as we have a more general get device view the main filter controlled by tx

2022-04-21 11:49 UTC, ldjebran commented on pkg/services/devices.go
> +	if res := tx.Limit(limit).Offset(offset).Where("account = ? AND image_id IS NOT NULL", account).Preload("UpdateTransaction").Preload("DevicesGroups").Find(&storedDevices); res.Error != nil {
the "AND image_id IS NOT NULL" is in the router now

2022-04-21 11:53 UTC, merged

2022-04-21 12:27 UTC, AaronH88 commented on pkg/models/devices.go
> +	DeviceGroupName []string `json:"DeviceGroupName"`
I understand this point, However, we currently do not need to keep the relationship between the ID and the Name in this view. We just need to display the names in the table. 

Is keeping this relationship something you think we should have in this view?

Regardless, the return json object will not change, unless I further indent the return json object. 

e.g.

```
data": {
        "total": 28,
        "devices": [
            {
                "DeviceID": 1,
                "DeviceName": "",
                "DeviceUUID": "",
                "ImageID": 1,
                "ImageName": "",
                "LastSeen": "0001-01-01 00:00:00 +0000 UTC",
                "UpdateAvailable": false,
                "Status": "RUNNING",
                "ImageSetID": 0,
                "deviceGroupData": [
                  {
                    "DeviceGroupID": null,
                    "DeviceGroupName": null,
                }
                ]
            },
```

Is this what you want?

2022-04-21 12:30 UTC, AaronH88 commented on pkg/services/devices.go
> +	if res := tx.Limit(limit).Offset(offset).Where("account = ? AND image_id IS NOT NULL", account).Preload("UpdateTransaction").Preload("DevicesGroups").Find(&storedDevices); res.Error != nil {
removed :smile: