Playbook template
RedHatInsights/edge-api pull request #98
Opened 2021-07-14 00:28 UTC by acosferreira

Init version

2021-07-15 17:42 UTC, maxamillion commented
This is great, this is without a doubt the groundwork for what we need. Thank you! :+1:

2021-07-20 16:07 UTC, maxamillion commented on pkg/updates/template/template.go
> +func main() {
I've been thinking about this lately and I think we might want this to be a library function ... something like `TemplatePlaybook` that will accept in the `remoteName`, `remoteURL`, and `contentURL` as parameters, then template the playbook and upload it into our S3 bucket under some new path ... `/templates/` or something. We'll probably want a database table to keep tabs on these things by ID and their resulting URL in the S3 bucket.

2021-07-21 20:22 UTC, biancarosa commented on pkg/playbooks/playbooks.go
> +func WriteTemplate(tempalteInfo TemplateRemoteInfo) (string, error) {
```suggestion
func WriteTemplate(templateInfo TemplateRemoteInfo) (string, error) {
```

2021-07-21 20:22 UTC, biancarosa commented on pkg/playbooks/playbooks.go
> +		GoTemplateRemoteName: tempalteInfo.RemoteName,
Instead of copying all of those fields, can you just create a templateInfo field that receives directly the templateInfo object?

2021-07-21 20:23 UTC, maxamillion requested changes

2021-07-21 20:23 UTC, maxamillion commented on pkg/commits/commits_test.go
> +	db.DB.Exec("DELETE FROM commits")
the `db.DB.Delete(&cmt)` appears to be referencing an existing commit but `db.DB.Exec("DELETE FROM commits")` is not .... is this missing a param passed to it or am I confused on what that `Exec` does?

2021-07-21 20:23 UTC, maxamillion commented on pkg/playbooks/playbooks.go
> +type TemplateRemoteInfo struct {
Comments on exported types to make `go vet` happy please. :)

2021-07-21 20:23 UTC, maxamillion commented on pkg/playbooks/playbooks.go
> +		return "Playbook::WriteTemplate::Error::", err
I think this should be:
```go
if err != nil {
    log.Errorf("Playbook::WriteTemplate::Error: %#v", err)
    return "", err
}
```

2021-07-21 20:23 UTC, maxamillion commented on pkg/playbooks/playbooks.go
> +		return "Playbook::WriteTemplate::Error::", err
Same here as above to log the error and `return "", err`

2021-07-21 20:23 UTC, maxamillion commented on pkg/playbooks/playbooks.go
> +		return "Playbook::WriteTemplate::Error::", err
Same here as above to log the error and `return "", err`

2021-07-21 20:23 UTC, biancarosa commented on pkg/playbooks/playbooks.go
> +		return "Playbook::WriteTemplate::Error::", err
Is that string used for something in the code that calls it? Best practice is to normally return empty object (nil or "") and err when a method returns an error.

2021-07-21 21:16 UTC, acosferreira commented on pkg/commits/commits_test.go
> +	db.DB.Exec("DELETE FROM commits")
for some reason (that I don't know) the data wasn't being deleted and the test was failing. The exec will delete everything from this table.

2021-07-21 21:21 UTC, acosferreira commented on pkg/playbooks/playbooks.go
> +		GoTemplateRemoteName: tempalteInfo.RemoteName,
This is the way to parse the values inside of the template file.

2021-07-21 23:06 UTC, maxamillion commented on pkg/commits/commits_test.go
> +	db.DB.Exec("DELETE FROM commits")
👍

2021-07-21 23:06 UTC, merged